package formats

import "github.com/neokapi/neokapi/core/registry"

// Built-in format identifiers. These constants are the canonical names used
// for format registration and lookup. Using these instead of raw strings
// provides compile-time safety.
const (
	Plaintext     registry.FormatID = "plaintext"
	HTML          registry.FormatID = "html"
	XML           registry.FormatID = "xml"
	XLIFF         registry.FormatID = "xliff"
	XLIFF2        registry.FormatID = "xliff2"
	YAML          registry.FormatID = "yaml"
	JSON          registry.FormatID = "json"
	PO            registry.FormatID = "po"
	Properties    registry.FormatID = "properties"
	Markdown      registry.FormatID = "markdown"
	CSV           registry.FormatID = "csv"
	TSV           registry.FormatID = "tsv"
	MosesText     registry.FormatID = "mosestext"
	SRT           registry.FormatID = "srt"
	TTML          registry.FormatID = "ttml"
	VTT           registry.FormatID = "vtt"
	TMX           registry.FormatID = "tmx"
	OpenXML       registry.FormatID = "openxml"
	DTD           registry.FormatID = "dtd"
	TS            registry.FormatID = "ts"
	Wiki          registry.FormatID = "wiki"
	TeX           registry.FormatID = "tex"
	Regex         registry.FormatID = "regex"
	Doxygen       registry.FormatID = "doxygen"
	MessageFormat registry.FormatID = "messageformat"
	PHPContent    registry.FormatID = "phpcontent"
	ICML          registry.FormatID = "icml"
	IDML          registry.FormatID = "idml"
	FixedWidth    registry.FormatID = "fixedwidth"
	TransTable    registry.FormatID = "transtable"
	ParaPlainText registry.FormatID = "paraplaintext"
	SplicedLines  registry.FormatID = "splicedlines"
	VersifiedText registry.FormatID = "versifiedtext"
	Vignette      registry.FormatID = "vignette"
	ODF           registry.FormatID = "odf"
	EPUB          registry.FormatID = "epub"
	RTF           registry.FormatID = "rtf"
	MIF           registry.FormatID = "mif"
	TTX           registry.FormatID = "ttx"
	TXML          registry.FormatID = "txml"
	XCStrings     registry.FormatID = "xcstrings"
	ARB           registry.FormatID = "arb"
	RESX          registry.FormatID = "resx"
	AndroidXML    registry.FormatID = "androidxml"
	AppleStrings  registry.FormatID = "applestrings"
	I18next       registry.FormatID = "i18next"
	DesignTokens  registry.FormatID = "designtokens"
	MDX           registry.FormatID = "mdx"
)
