//go:build parity

package roundtrip_test

// idmlBridgeSkips and openxmlBridgeSkips list the upstream IDML and
// OpenXML fixtures where bridge's pseudo-translated output diverges
// from tikal's reference. Native is included on every entry because
// each format already format-default-skips native; the per-file entry
// extends that to bridge for these specific files.
//
// The lists are extracted from a real round-trip suite run against
// the okapi-testdata-1.48.0 release. As bridge bugs get fixed
// upstream, drop entries from these maps and the corresponding
// sub-tests start asserting again.

func idmlBridgeSkips() map[string]fileSkip {
	const reason = "bridge inline-code/run-marker divergence in IDML Stories XML vs tikal"
	return map[string]fileSkip{
		"00-primary-text-frame-with-different-breaking-symbols.idml": {Engines: []string{"bridge", "native"}, Reason: reason},
		"01-pages-with-text-frames-2.idml":                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"01-pages-with-text-frames-3.idml":                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"01-pages-with-text-frames-4.idml":                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"01-pages-with-text-frames-5.idml":                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"01-pages-with-text-frames-6.idml":                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"01-pages-with-text-frames.idml":                             {Engines: []string{"bridge", "native"}, Reason: reason},
		"03-hyperlink-and-table-content.idml":                        {Engines: []string{"bridge", "native"}, Reason: reason},
		"04-complex-formatting.idml":                                 {Engines: []string{"bridge", "native"}, Reason: reason},
		"06-hello-world-14.idml":                                     {Engines: []string{"bridge", "native"}, Reason: reason},
		"09-footnotes.idml":                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"10-tables.idml":                                             {Engines: []string{"bridge", "native"}, Reason: reason},
		"1016.idml":                                                  {Engines: []string{"bridge", "native"}, Reason: reason},
		"11-xml-structures.idml":                                     {Engines: []string{"bridge", "native"}, Reason: reason},
		"1139.idml":                                                  {Engines: []string{"bridge", "native"}, Reason: reason},
		"1179-0.idml":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"1179-1.idml":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"1179-2.idml":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"1179-3.idml":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"1179-4.idml":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"1369-empty-paragraph-in-table-cell-styles.idml":             {Engines: []string{"bridge", "native"}, Reason: reason},
		"1412-math-zones.idml":                                       {Engines: []string{"bridge", "native"}, Reason: reason},
		"1415-adjacent-codes.idml":                                   {Engines: []string{"bridge", "native"}, Reason: reason},
		"1418-styles-exclusion.idml":                                 {Engines: []string{"bridge", "native"}, Reason: reason},
		"175-special-characters.idml":                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"618-MBE3.idml":                                              {Engines: []string{"bridge", "native"}, Reason: reason},
		"618-anchored-frame-without-path-points.idml":                {Engines: []string{"bridge", "native"}, Reason: reason},
		"756-character-baseline-shift.idml":                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"756-character-kerning.idml":                                 {Engines: []string{"bridge", "native"}, Reason: reason},
		"756-character-leading.idml":                                 {Engines: []string{"bridge", "native"}, Reason: reason},
		"756-character-tracking.idml":                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"777-character-kerning-method.idml":                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"779-reference-and-tag-styles.idml":                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"856-1.idml":                                                 {Engines: []string{"bridge", "native"}, Reason: reason},
		"856-2.idml":                                                 {Engines: []string{"bridge", "native"}, Reason: reason},
		"923-baselined-formatting.idml":                              {Engines: []string{"bridge", "native"}, Reason: reason},
		"Bindestrich.idml":                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"Test00.idml":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"Test01.idml":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"Test02.idml":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"Test03.idml":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"TextPathTest04.idml":                                        {Engines: []string{"bridge", "native"}, Reason: reason},
		"change-tracking-3.idml":                                     {Engines: []string{"bridge", "native"}, Reason: reason},
		"idmltest.idml":                                              {Engines: []string{"bridge", "native"}, Reason: reason},
		"tabsAndWhitespaces.idml":                                    {Engines: []string{"bridge", "native"}, Reason: reason},
		"testWithSpecialChars.idml":                                  {Engines: []string{"bridge", "native"}, Reason: reason},
	}
}

func openxmlBridgeSkips() map[string]fileSkip {
	const reason = "bridge inline-run/code divergence in OpenXML document parts vs tikal"
	return map[string]fileSkip{
		"1083-date-and-hyperlink-instructions.docx":                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"1083-empty-and-hyperlink-instructions.docx":                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"1083-hyperlink-and-date-instructions.docx":                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"1083-hyperlink-and-empty-instructions.docx":                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"1102.docx":                                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"1145-colors-aggressive.docx":                                         {Engines: []string{"bridge", "native"}, Reason: reason},
		"1145-colors.docx":                                                    {Engines: []string{"bridge", "native"}, Reason: reason},
		"1157.docx":                                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"1172.docx":                                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"1200-1.docx":                                                         {Engines: []string{"bridge", "native"}, Reason: reason},
		"1200-2.docx":                                                         {Engines: []string{"bridge", "native"}, Reason: reason},
		"1200-3.docx":                                                         {Engines: []string{"bridge", "native"}, Reason: reason},
		"1200-4.docx":                                                         {Engines: []string{"bridge", "native"}, Reason: reason},
		"1200-5.docx":                                                         {Engines: []string{"bridge", "native"}, Reason: reason},
		"1306.docx":                                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"1312-fonts-info-2.docx":                                              {Engines: []string{"bridge", "native"}, Reason: reason},
		"1312-fonts-info.docx":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"1341-textbox-with-a-hyperlink.docx":                                  {Engines: []string{"bridge", "native"}, Reason: reason},
		"1370-same-nested-revisions.docx":                                     {Engines: []string{"bridge", "native"}, Reason: reason},
		"1385-whitespace-styles.docx":                                         {Engines: []string{"bridge", "native"}, Reason: reason},
		"1394-highlights.docx":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"1394-styles.docx":                                                    {Engines: []string{"bridge", "native"}, Reason: reason},
		"1406-code-finding.docx":                                              {Engines: []string{"bridge", "native"}, Reason: reason},
		"1413-notes.docx":                                                     {Engines: []string{"bridge", "native"}, Reason: reason},
		"1421-line-break.docx":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"1433-text-for-masking.docx":                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"1437-color-exclusion.docx":                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"768-2.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"768.docx":                                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"830-1.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"830-2.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"830-3.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"830-4.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"830-5.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"830-6.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"830-7.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"834.docx":                                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"847-2.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"847-3.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"851.docx":                                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"859.docx":                                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"884.docx":                                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"887.docx":                                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"899.docx":                                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"947-non-cs-and-cs.docx":                                              {Engines: []string{"bridge", "native"}, Reason: reason},
		"952-1.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"952-2.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"952-3.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"956.docx":                                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"992.docx":                                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"Addcomments.docx":                                                    {Engines: []string{"bridge", "native"}, Reason: reason},
		"AltContentEscaping.docx":                                             {Engines: []string{"bridge", "native"}, Reason: reason},
		"AlternateContent.docx":                                               {Engines: []string{"bridge", "native"}, Reason: reason},
		"AlternateContentTest.docx":                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"BoldWorld.docx":                                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"Deli.docx":                                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"Document-with-custom-tabs.docx":                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"Document-with-formula-and-tabs.docx":                                 {Engines: []string{"bridge", "native"}, Reason: reason},
		"Document-with-soft-linebreaks.docx":                                  {Engines: []string{"bridge", "native"}, Reason: reason},
		"Document-with-tabs-2.docx":                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"Document-with-tabs-3.docx":                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"Document-with-tabs-4.docx":                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"Document-with-tabs-5.docx":                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"Document-with-tabs-at-EOL.docx":                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"Document-with-tabs.docx":                                             {Engines: []string{"bridge", "native"}, Reason: reason},
		"DrawingML_Test.docx":                                                 {Engines: []string{"bridge", "native"}, Reason: reason},
		"EndGroup.docx":                                                       {Engines: []string{"bridge", "native"}, Reason: reason},
		"Escapades.docx":                                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"GraphicInTextBox.docx":                                               {Engines: []string{"bridge", "native"}, Reason: reason},
		"Hangs.docx":                                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"HelloWorld.docx":                                                     {Engines: []string{"bridge", "native"}, Reason: reason},
		"HiddenExcluded.docx":                                                 {Engines: []string{"bridge", "native"}, Reason: reason},
		"HiddenTablesApachePoi.docx":                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"MissingPara.docx":                                                    {Engines: []string{"bridge", "native"}, Reason: reason},
		"N_001_Auswertung_Part4.docx":                                         {Engines: []string{"bridge", "native"}, Reason: reason},
		"OkapiMarkers.docx":                                                   {Engines: []string{"bridge", "native"}, Reason: reason},
		"OpenXML_text_reference_v1_2.docx":                                    {Engines: []string{"bridge", "native"}, Reason: reason},
		"OpenXmlRoundtripSoftLineBreaksDoNotTranslateTestCharacterStyle.docx": {Engines: []string{"bridge", "native"}, Reason: reason},
		"OpenXmlRoundtripSoftLineBreaksDoNotTranslateTestParagraphStyle.docx": {Engines: []string{"bridge", "native"}, Reason: reason},
		"OpenXmlRoundtripTabDoNotTranslateTestCharacterStyle.docx":            {Engines: []string{"bridge", "native"}, Reason: reason},
		"OpenXmlRoundtripTabDoNotTranslateTestParagraphStyle.docx":            {Engines: []string{"bridge", "native"}, Reason: reason},
		"OutOfTheTextBox.docx":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"Practice2.docx":                                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"StartsWithLineSeparator.docx":                                        {Engines: []string{"bridge", "native"}, Reason: reason},
		"TabAtEnd.docx":                                                       {Engines: []string{"bridge", "native"}, Reason: reason},
		"TabAtEndAfterNewRun.docx":                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"TestDako2.docx":                                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"TestLTinsideBoxFails.docx":                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"TextboxNumber.docx":                                                  {Engines: []string{"bridge", "native"}, Reason: reason},
		"apissue.docx":                                                        {Engines: []string{"bridge", "native"}, Reason: reason},
		"br.docx":                                                             {Engines: []string{"bridge", "native"}, Reason: reason},
		"br2.docx":                                                            {Engines: []string{"bridge", "native"}, Reason: reason},
		"chartAmpersand.docx":                                                 {Engines: []string{"bridge", "native"}, Reason: reason},
		"content_category_test.docx":                                          {Engines: []string{"bridge", "native"}, Reason: reason},
		"delTextAmp.docx":                                                     {Engines: []string{"bridge", "native"}, Reason: reason},
		"document-revision-information-stripping.docx":                        {Engines: []string{"bridge", "native"}, Reason: reason},
		"document-style-definitions.docx":                                     {Engines: []string{"bridge", "native"}, Reason: reason},
		"document-with-run-fonts-variations.docx":                             {Engines: []string{"bridge", "native"}, Reason: reason},
		"docxsegtest.docx":                                                    {Engines: []string{"bridge", "native"}, Reason: reason},
		"docxtest.docx":                                                       {Engines: []string{"bridge", "native"}, Reason: reason},
		"external_hyperlink.docx":                                             {Engines: []string{"bridge", "native"}, Reason: reason},
		"gettysburg_en.docx":                                                  {Engines: []string{"bridge", "native"}, Reason: reason},
		"graphicdata.docx":                                                    {Engines: []string{"bridge", "native"}, Reason: reason},
		"highlight_in_style.docx":                                             {Engines: []string{"bridge", "native"}, Reason: reason},
		"highlights.docx":                                                     {Engines: []string{"bridge", "native"}, Reason: reason},
		"highlights_block.docx":                                               {Engines: []string{"bridge", "native"}, Reason: reason},
		"hyperlink.docx":                                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"lang.docx":                                                           {Engines: []string{"bridge", "native"}, Reason: reason},
		"large-attribute.docx":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"multiple_tabs.docx":                                                  {Engines: []string{"bridge", "native"}, Reason: reason},
		"neverendingloop.docx":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"picture.docx":                                                        {Engines: []string{"bridge", "native"}, Reason: reason},
		"sample.docx":                                                         {Engines: []string{"bridge", "native"}, Reason: reason},
		"shape with text.docx":                                                {Engines: []string{"bridge", "native"}, Reason: reason},
		"simple_chart.docx":                                                   {Engines: []string{"bridge", "native"}, Reason: reason},
		"smart_art.docx":                                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"spacing.docx":                                                        {Engines: []string{"bridge", "native"}, Reason: reason},
		"special-chars-and-linebreaks.docx":                                   {Engines: []string{"bridge", "native"}, Reason: reason},
		"styles_color.docx":                                                   {Engines: []string{"bridge", "native"}, Reason: reason},
		"tabstyles.docx":                                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"textarea.docx":                                                       {Engines: []string{"bridge", "native"}, Reason: reason},
		"vertAlign.docx":                                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"watermark.docx":                                                      {Engines: []string{"bridge", "native"}, Reason: reason},
		"word art.docx":                                                       {Engines: []string{"bridge", "native"}, Reason: reason},
	}
}
