// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as flow$0 from "../flow/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gate$0 from "../gate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AnnotationDefaults narrows which annotation types a writer draws into the
 * document as inline marks: a located term as an XLIFF <mrk>, as an HTML
 * <span>.
 * 
 * A format declares the ceiling. Its writer names the types it knows how to
 * draw (format.InlineAnnotationWriter, recorded on
 * registry.FormatInfo.InlineAnnotations), and a recipe can only narrow that
 * set. Two things follow, both wanted: a format that gains the capability
 * starts projecting without anyone editing a recipe, and a project that wants
 * a clean export with no marks in it can still say so.
 */
export class AnnotationDefaults {
    /**
     * Creates a new AnnotationDefaults instance.
     * @param {Partial<AnnotationDefaults>} [$$source = {}] - The source object to create the AnnotationDefaults.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Write names the annotation types to draw, out of what the format
             * declares it can carry. Empty means the declaration stands: every type
             * the writer can draw, it draws.
             * 
             * Naming a type the format cannot carry asks for nothing rather than
             * failing. The recipe is one document describing many formats, and a
             * project that wants terms marked wherever they can be should not have to
             * enumerate which of its outputs happen to support it.
             * @member
             * @type {string[] | undefined}
             */
            this["write"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnnotationDefaults instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AnnotationDefaults}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("write" in $$parsedSource) {
            $$parsedSource["write"] = $$createField0_0($$parsedSource["write"]);
        }
        return new AnnotationDefaults(/** @type {Partial<AnnotationDefaults>} */($$parsedSource));
    }
}

/**
 * Channel is one surface a product ships on. The short form is the slug
 * itself; the long form adds the concept that names it:
 * 
 * 	profiles:
 * 	  bowrain:
 * 	    channels:
 * 	      - id: docs
 * 	        concept: term:9a1c0f42b7
 * 	      - app
 */
export class Channel {
    /**
     * Creates a new Channel instance.
     * @param {Partial<Channel>} [$$source = {}] - The source object to create the Channel.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * ID is the slug: the channel as a collection's `channel:` writes it.
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Concept optionally references the concept that names this channel, for
             * display. Carried and shape-checked; never resolved during matching.
             * @member
             * @type {string | undefined}
             */
            this["concept"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Channel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Channel}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Channel(/** @type {Partial<Channel>} */($$parsedSource));
    }
}

/**
 * Collection is either a bare content entry or a named collection of content
 * items.
 * 
 * Bare entry (has path, no content):
 * 
 *   - path: "src/** /*"
 *     target: "output/{lang}/** /*"
 * 
 * Named collection (the ordinary form):
 * 
 *   - name: bowrain-docs
 *     channel: bowrain/docs
 *     base: bowrain/web/docs
 *     content:
 *   - path: "docs/** /*.mdx"
 *     target: "i18n/{lang}/{path}.mdx"
 */
export class Collection {
    /**
     * Creates a new Collection instance.
     * @param {Partial<Collection>} [$$source = {}] - The source object to create the Collection.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {model$0.LocaleID | undefined}
             */
            this["source_language"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {model$0.LocaleID[] | undefined}
             */
            this["target_languages"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ContentItem[] | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Base is the directory this collection lives in: every content path,
             * target and item base below is written relative to it, so a collection
             * reads as the tree it governs rather than as a repeated prefix. Empty
             * means the paths are project-relative.
             * @member
             * @type {string | undefined}
             */
            this["base"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Channel places this collection's content at a point in the project's
             * context space, written as the qualified `profile/channel`. A bare channel
             * name is rejected, and the error spells out the qualified form(s) to write
             * (ResolveChannel). The point selects the profile whose governance —
             * voice, terms — a run carries over this content, and the channel then
             * selects the matching override inside that voice. Empty means the
             * project's default point governs it. Named collections only: a point is
             * resolved by collection name, so an unnamed entry has nothing to resolve.
             * @member
             * @type {string | undefined}
             */
            this["channel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Coordinates places this collection on the DECLARED axes — the ones a
             * project names for itself, brand among them. It overlays
             * `defaults.coordinates`, per axis, so a collection moves on the one axis
             * it differs on and inherits the rest.
             * 
             * The structural axes come from `channel:` above and are not written here.
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["coordinates"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SourceOnly declares that this collection has no target language and is
             * never translated: a run reads it, checks it, and writes nothing back.
             * Package descriptions and installer strings are the usual case.
             * 
             * It is an assertion, not a mode. Naming no target already made a
             * collection source-only, so this flag adds no behaviour — what it adds is
             * the difference between meaning it and forgetting. Validate rejects a
             * collection that sets it and also carries a target, so the declaration and
             * the items cannot drift into disagreeing.
             * @member
             * @type {boolean | undefined}
             */
            this["source_only"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Bare entry fields (short form — promoted from ContentItem).
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FormatSpec | null | undefined}
             */
            this["format"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["target"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Collection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Collection}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target_languages" in $$parsedSource) {
            $$parsedSource["target_languages"] = $$createField2_0($$parsedSource["target_languages"]);
        }
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField3_0($$parsedSource["content"]);
        }
        if ("coordinates" in $$parsedSource) {
            $$parsedSource["coordinates"] = $$createField6_0($$parsedSource["coordinates"]);
        }
        if ("format" in $$parsedSource) {
            $$parsedSource["format"] = $$createField9_0($$parsedSource["format"]);
        }
        return new Collection(/** @type {Partial<Collection>} */($$parsedSource));
    }
}

/**
 * ContentItem is a single content pattern within a collection.
 */
export class ContentItem {
    /**
     * Creates a new ContentItem instance.
     * @param {Partial<ContentItem>} [$$source = {}] - The source object to create the ContentItem.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FormatSpec | null | undefined}
             */
            this["format"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["target"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["base"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {model$0.LocaleID | undefined}
             */
            this["source_language"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {model$0.LocaleID[] | undefined}
             */
            this["target_languages"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Channel overrides the collection's `channel:` for the files this item
             * matches — the one place a single file, or a sub-pattern, sits at a
             * different point in the context space than the rest of its collection. It
             * takes the same qualified `profile/channel` form and the same validator as
             * a collection's channel; empty inherits the collection's. A run resolves it
             * per file through ResolveGovernanceForPath.
             * @member
             * @type {string | undefined}
             */
            this["channel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Redaction overrides the project-wide redaction spec for this item.
             * nil means inherit defaults.
             * @member
             * @type {RedactionSpec | null | undefined}
             */
            this["redaction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContentItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContentItem}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType6;
        const $$createField5_0 = $$createType1;
        const $$createField7_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("format" in $$parsedSource) {
            $$parsedSource["format"] = $$createField1_0($$parsedSource["format"]);
        }
        if ("target_languages" in $$parsedSource) {
            $$parsedSource["target_languages"] = $$createField5_0($$parsedSource["target_languages"]);
        }
        if ("redaction" in $$parsedSource) {
            $$parsedSource["redaction"] = $$createField7_0($$parsedSource["redaction"]);
        }
        return new ContentItem(/** @type {Partial<ContentItem>} */($$parsedSource));
    }
}

/**
 * Defaults holds project-wide processing defaults.
 */
export class Defaults {
    /**
     * Creates a new Defaults instance.
     * @param {Partial<Defaults>} [$$source = {}] - The source object to create the Defaults.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {model$0.LocaleID | undefined}
             */
            this["source_language"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {model$0.LocaleID[] | undefined}
             */
            this["target_languages"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Flow names the project's default flow — the one `kapi run` (with no flow
             * argument) executes to bring the project's content up to date across every
             * target language. It is a built-in composed flow name or a key in `flows:`.
             * Empty means there is no default; `kapi run` then requires an explicit flow.
             * @member
             * @type {string | undefined}
             */
            this["flow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Materialize governs whether the convergence loop (`kapi up`) owns
             * delivery of the localized target files (#1078 C2/C3).
             * 
             * "on-converge" makes the run responsible for them, under the ship gate:
             * its passes draft into a run-local tree and only a locale whose gated
             * scopes are all shippable has its files written to the collection's
             * `target:` path. "manual" (the default) leaves delivery to an explicit
             * `kapi merge` (or `up --materialize`) and claims no gate — its passes
             * write where the recipe points as they produce each unit.
             * @member
             * @type {string | undefined}
             */
            this["materialize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Jobs is how many target languages one convergence pass (`kapi up`)
             * runs concurrently. 0 (the default) leaves it to the runner's default;
             * `up --jobs` overrides per run.
             * @member
             * @type {number | undefined}
             */
            this["jobs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SourceGate is the source-first convergence gate: the SourceStatus a
             * source block must reach before its translations are produced. Source-first
             * convergence settles the source (terminology + voice + source hygiene) and gates
             * the fan-out on it, so an unsettled, non-compliant, un-term-checked source is
             * never translated into N locales only to be redone when it changes
             * (strategy 2026-07-dogfood doc 07 / roadmap epic 019).
             * 
             * Values:
             *   ""         — unset; the runner applies the default gate (`checked`).
             *   "authored" — the presence baseline (any non-empty source qualifies).
             *   "checked"  — the DEFAULT: source cleared its automated terminology,
             *                voice, and source hygiene checks (no human bottleneck).
             *   "approved" — a human/agent signed off the source (voice-critical or
             *                regulated projects).
             *   "none"     — the deliberate opt-out: no gate, raw MT / fan-out on push
             *                exactly as before source-first. You have to choose it.
             * 
             * It is the level-based, per-project counterpart of the coverage-bar
             * SourceGate on KapiProject (which `kapi check --ship` evaluates); this one
             * governs the convergence fan-out.
             * @member
             * @type {string | undefined}
             */
            this["source_gate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "bcp-47" (default) or "posix"
             * @member
             * @type {string | undefined}
             */
            this["locale_format"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["concurrency"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["parallel_blocks"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["encoding"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: FormatDefaults } | undefined}
             */
            this["formats"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Exclude is a list of glob patterns skipped during content scanning.
             * @member
             * @type {string[] | undefined}
             */
            this["exclude"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Merge governs kapi merge behavior (AD-017).
             * @member
             * @type {MergeDefaults | undefined}
             */
            this["merge"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * content memory governs content memory pre-fill on kapi extract and content memory write-back on kapi merge (AD-017).
             * @member
             * @type {MemoryDefaults | undefined}
             */
            this["memory"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Segmentation governs the opt-in sentence-level segmentation overlay
             * applied on extract (AD-017).
             * @member
             * @type {SegmentationDefaults | undefined}
             */
            this["segmentation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Annotations governs which of a block's stand-off annotations a writer
             * draws into the document as inline marks. Zero leaves each format's own
             * declaration standing.
             * @member
             * @type {AnnotationDefaults | undefined}
             */
            this["annotations"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Redaction governs replacing sensitive content with protected
             * placeholders before processing and restoring it afterwards. nil means
             * no redaction.
             * @member
             * @type {RedactionSpec | null | undefined}
             */
            this["redaction"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Voice binds a voice profile as standing project context. When set,
             * project-scoped commands (voice check/rewrite/guide and project
             * translation flows) honor it with no profile flag. nil means no bound
             * voice profile.
             * 
             * This is the framework binding under `defaults:`. It is distinct from
             * bowrain's top-level `brand_voice` extension (decoded from Extras),
             * which is a platform-level policy with collection scoping.
             * @member
             * @type {VoiceBinding | null | undefined}
             */
            this["voice"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Coordinates is the project's default point in the context space: the axes
             * every collection sits at unless it says otherwise.
             * 
             * It exists because most axes default. A project has one brand far more
             * often than one per collection, so stating it per entry is noise that
             * drifts — the same reason Voice above is a default with a per-collection
             * override rather than a field repeated on every entry.
             * 
             * The structural axes (product, channel) are NOT written here: they are
             * derived from a collection's `channel:`, and a default that could shadow
             * them would let a recipe contradict its own point. Declared axes only.
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["coordinates"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TermsSource binds the committed, git-tracked native source artifact
             * (a .terms.json document) the project terms store is compiled from. This is the
             * authored, reviewable form: `kapi apply` edits the .terms.json here and then
             * re-imports it into the gitignored terms tables inside `.kapi/work/store.db`,
             * so the store is written by exactly one path and `git diff` is the review
             * surface. The path resolves relative to the project root. Empty means no
             * bound source (whatever the store already holds is the only artifact).
             * @member
             * @type {string | undefined}
             */
            this["terms_source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * MemorySource binds the committed, git-tracked native source artifact (a
             * .memory.json document) the project content memory is compiled from, the content memory
             * analogue of TermsSource. `kapi apply` edits the .memory.json here and
             * re-imports it into the project store. The path resolves relative to the
             * project root. Empty means no bound content memory source.
             * @member
             * @type {string | undefined}
             */
            this["memory_source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Tools holds project-level tool presets: per-tool config defaults applied
             * wherever the tool runs in a project flow. A flow step's own config
             * overrides the preset per key (step wins), so a project can pin, say,
             * redaction rules or a pseudo-translate prefix once while an individual
             * flow refines them. Resolution happens at tool construction and feeds the
             * same merged config to data-flow and placement validation, so a preset
             * that enables redact's entity detection makes the entity port required
             * exactly as an inline config would.
             * @member
             * @type {{ [_ in string]?: { [_ in string]?: any } } | undefined}
             */
            this["tools"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Locales holds per-target-language overrides, keyed by locale. Each entry's
             * tool presets merge on top of the project-wide Tools presets (and under a
             * flow step's own config) whenever a flow runs for that target locale — so a
             * project can declare an advanced feature once per locale ("de needs
             * redaction, others don't") without forking the flow. Convergence and any
             * targeted run honor it; locales with no entry use the project defaults.
             * @member
             * @type {{ [_ in string]?: LocaleDefaults } | undefined}
             */
            this["locales"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Defaults instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Defaults}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        const $$createField10_0 = $$createType10;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType11;
        const $$createField13_0 = $$createType12;
        const $$createField14_0 = $$createType13;
        const $$createField15_0 = $$createType14;
        const $$createField16_0 = $$createType8;
        const $$createField17_0 = $$createType16;
        const $$createField18_0 = $$createType4;
        const $$createField21_0 = $$createType18;
        const $$createField22_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target_languages" in $$parsedSource) {
            $$parsedSource["target_languages"] = $$createField1_0($$parsedSource["target_languages"]);
        }
        if ("formats" in $$parsedSource) {
            $$parsedSource["formats"] = $$createField10_0($$parsedSource["formats"]);
        }
        if ("exclude" in $$parsedSource) {
            $$parsedSource["exclude"] = $$createField11_0($$parsedSource["exclude"]);
        }
        if ("merge" in $$parsedSource) {
            $$parsedSource["merge"] = $$createField12_0($$parsedSource["merge"]);
        }
        if ("memory" in $$parsedSource) {
            $$parsedSource["memory"] = $$createField13_0($$parsedSource["memory"]);
        }
        if ("segmentation" in $$parsedSource) {
            $$parsedSource["segmentation"] = $$createField14_0($$parsedSource["segmentation"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField15_0($$parsedSource["annotations"]);
        }
        if ("redaction" in $$parsedSource) {
            $$parsedSource["redaction"] = $$createField16_0($$parsedSource["redaction"]);
        }
        if ("voice" in $$parsedSource) {
            $$parsedSource["voice"] = $$createField17_0($$parsedSource["voice"]);
        }
        if ("coordinates" in $$parsedSource) {
            $$parsedSource["coordinates"] = $$createField18_0($$parsedSource["coordinates"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField21_0($$parsedSource["tools"]);
        }
        if ("locales" in $$parsedSource) {
            $$parsedSource["locales"] = $$createField22_0($$parsedSource["locales"]);
        }
        return new Defaults(/** @type {Partial<Defaults>} */($$parsedSource));
    }
}

/**
 * FlowValidationIssue describes a problem with a tool reference in a project flow.
 */
export class FlowValidationIssue {
    /**
     * Creates a new FlowValidationIssue instance.
     * @param {Partial<FlowValidationIssue>} [$$source = {}] - The source object to create the FlowValidationIssue.
     */
    constructor($$source = {}) {
        if (!("flow_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["flow_name"] = "";
        }
        if (!("step_tool" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["step_tool"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "unknown" or "undeclared_plugin"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * plugin name (for undeclared_plugin)
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlowValidationIssue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FlowValidationIssue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlowValidationIssue(/** @type {Partial<FlowValidationIssue>} */($$parsedSource));
    }
}

/**
 * FormatDefaults holds project-level default settings for a specific format.
 */
export class FormatDefaults {
    /**
     * Creates a new FormatDefaults instance.
     * @param {Partial<FormatDefaults>} [$$source = {}] - The source object to create the FormatDefaults.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["preset"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["config"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["priority"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormatDefaults instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FormatDefaults}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new FormatDefaults(/** @type {Partial<FormatDefaults>} */($$parsedSource));
    }
}

/**
 * FormatSpec is the per-item format override.
 * Supports short form (scalar string → just the name) and long form (mapping).
 * 
 * Short form: format: okf_html
 * Long form:
 * 
 * 	format:
 * 	  name: okf_html
 * 	  preset: lenient
 * 	  config: {escapeGT: false}
 */
export class FormatSpec {
    /**
     * Creates a new FormatSpec instance.
     * @param {Partial<FormatSpec>} [$$source = {}] - The source object to create the FormatSpec.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["preset"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["config"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormatSpec instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FormatSpec}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new FormatSpec(/** @type {Partial<FormatSpec>} */($$parsedSource));
    }
}

/**
 * GateRef is a rule's gate value: either an inline threshold map
 * (`gate: {translated: 100}`) or a name into the `gates:` registry
 * (`gate: machine`).
 */
export class GateRef {
    /**
     * Creates a new GateRef instance.
     * @param {Partial<GateRef>} [$$source = {}] - The source object to create the GateRef.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * set when the YAML value is a scalar (a registry name)
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Inline" in $$source)) {
            /**
             * set when the YAML value is a map (inline thresholds)
             * @member
             * @type {gate$0.Gate}
             */
            this["Inline"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GateRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GateRef}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Inline" in $$parsedSource) {
            $$parsedSource["Inline"] = $$createField1_0($$parsedSource["Inline"]);
        }
        return new GateRef(/** @type {Partial<GateRef>} */($$parsedSource));
    }
}

/**
 * KapiProject is the root type for a .kapi project file.
 */
export class KapiProject {
    /**
     * Creates a new KapiProject instance.
     * @param {Partial<KapiProject>} [$$source = {}] - The source object to create the KapiProject.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: PluginSpec } | undefined}
             */
            this["plugins"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Defaults | undefined}
             */
            this["defaults"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Collection[] | undefined}
             */
            this["collections"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["preset"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: flow$0.StepsSpec | null } | undefined}
             */
            this["flows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Profiles binds governance to a product, keyed by the product's name. A
             * project is not always one voice: a repository holding both a framework
             * and the platform built on it carries two, and one project-wide binding
             * governs the wrong one half the time. Each profile declares the channels
             * its product ships on, and a collection names the point its content sits
             * at with one `channel:` reference (Collection.Channel). Empty means the
             * whole project sits at one point, under defaults.voice /
             * defaults.terms_source. See profiles.go.
             * @member
             * @type {{ [_ in string]?: Profile } | undefined}
             */
            this["profiles"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Ship gates decide when localized content is shippable, as coverage
             * thresholds over the lifecycle ladder (see core/gate). Three optional,
             * additive forms:
             *   ShipGate  — a single catch-all gate ({translated: 100, reviewed: 100}).
             *   ShipGates — a when/gate rule list; most-specific rule wins.
             *   Gates     — a named registry referenced by a rule's `gate: <name>`.
             * BuildShipGates resolves these into an evaluatable gate.RuleSet.
             * @member
             * @type {gate$0.Gate | undefined}
             */
            this["ship_gate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ShipGateRule[] | undefined}
             */
            this["ship_gates"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: gate$0.Gate } | undefined}
             */
            this["gates"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Verified gates decide when localized content is "human-verified": the
             * second gate, evaluated exactly like the ship gate but against a bar that
             * implies a person reviewed or signed off the work (e.g. {reviewed: 100}).
             * A locale that clears its ship gate but not its verified gate ships flagged
             * AI in a language picker; a verified locale carries no badge. The two gates
             * are independent — being verified is not a prerequisite for shipping. Same
             * additive forms and precedence as the ship gate, resolving a rule's
             * `gate: <name>` reference against the same Gates registry:
             *   VerifiedGate  — a single catch-all gate.
             *   VerifiedGates — a when/gate rule list; most-specific rule wins.
             * With NO verified gate configured, nothing is verified: BuildVerifiedGates
             * returns an empty RuleSet, so every locale reads unverified (the honest
             * default — a project opts in to "verified" by declaring the bar).
             * @member
             * @type {gate$0.Gate | undefined}
             */
            this["verified_gate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ShipGateRule[] | undefined}
             */
            this["verified_gates"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SourceGate is the source-readiness bar: a single coverage gate over the
             * source authoring ladder (authored → checked → approved), e.g.
             * {checked: 100}. It is the source-side counterpart of ShipGate — it gates
             * the author's own content, not the translations. BuildSourceGate
             * resolves it; evaluated by `kapi check --ship` (never an ordinary
             * build).
             * @member
             * @type {gate$0.Gate | undefined}
             */
            this["source_gate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Requires lists plugin dependencies as a map of plugin name → version
             * constraint. Validation fails if any named plugin (or extension group
             * of the same name) has no registered extension in the loading process.
             * A recipe with `requires: { bowrain: "^1.0" }` will refuse to load in a
             * binary that has not registered the bowrain extension.
             * 
             * Version constraints follow semver (`^1.0`, `>=1.47.0`, `~1.4.2`,
             * `1.4.0` exact-match, `*` any). The map form is mandatory — a bare-list
             * form (`requires: [bowrain]`) is rejected with an actionable error.
             * @member
             * @type {RequiresMap | undefined}
             */
            this["requires"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KapiProject instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KapiProject}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType24;
        const $$createField3_0 = $$createType25;
        const $$createField4_0 = $$createType27;
        const $$createField6_0 = $$createType30;
        const $$createField7_0 = $$createType32;
        const $$createField8_0 = $$createType21;
        const $$createField9_0 = $$createType34;
        const $$createField10_0 = $$createType35;
        const $$createField11_0 = $$createType21;
        const $$createField12_0 = $$createType34;
        const $$createField13_0 = $$createType21;
        const $$createField14_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField2_0($$parsedSource["plugins"]);
        }
        if ("defaults" in $$parsedSource) {
            $$parsedSource["defaults"] = $$createField3_0($$parsedSource["defaults"]);
        }
        if ("collections" in $$parsedSource) {
            $$parsedSource["collections"] = $$createField4_0($$parsedSource["collections"]);
        }
        if ("flows" in $$parsedSource) {
            $$parsedSource["flows"] = $$createField6_0($$parsedSource["flows"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField7_0($$parsedSource["profiles"]);
        }
        if ("ship_gate" in $$parsedSource) {
            $$parsedSource["ship_gate"] = $$createField8_0($$parsedSource["ship_gate"]);
        }
        if ("ship_gates" in $$parsedSource) {
            $$parsedSource["ship_gates"] = $$createField9_0($$parsedSource["ship_gates"]);
        }
        if ("gates" in $$parsedSource) {
            $$parsedSource["gates"] = $$createField10_0($$parsedSource["gates"]);
        }
        if ("verified_gate" in $$parsedSource) {
            $$parsedSource["verified_gate"] = $$createField11_0($$parsedSource["verified_gate"]);
        }
        if ("verified_gates" in $$parsedSource) {
            $$parsedSource["verified_gates"] = $$createField12_0($$parsedSource["verified_gates"]);
        }
        if ("source_gate" in $$parsedSource) {
            $$parsedSource["source_gate"] = $$createField13_0($$parsedSource["source_gate"]);
        }
        if ("requires" in $$parsedSource) {
            $$parsedSource["requires"] = $$createField14_0($$parsedSource["requires"]);
        }
        return new KapiProject(/** @type {Partial<KapiProject>} */($$parsedSource));
    }
}

/**
 * LocaleDefaults holds per-target-language overrides applied when a flow runs
 * for that locale. Tool presets are the lever: they merge on top of the
 * project-wide defaults.tools (per-locale wins) and under a flow step's own
 * config (the step still wins), the same precedence as the project presets.
 */
export class LocaleDefaults {
    /**
     * Creates a new LocaleDefaults instance.
     * @param {Partial<LocaleDefaults>} [$$source = {}] - The source object to create the LocaleDefaults.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: { [_ in string]?: any } } | undefined}
             */
            this["tools"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocaleDefaults instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocaleDefaults}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField0_0($$parsedSource["tools"]);
        }
        return new LocaleDefaults(/** @type {Partial<LocaleDefaults>} */($$parsedSource));
    }
}

/**
 * MemoryDefaults governs content memory pre-fill on extract and content memory write-back on merge (AD-017).
 */
export class MemoryDefaults {
    /**
     * Creates a new MemoryDefaults instance.
     * @param {Partial<MemoryDefaults>} [$$source = {}] - The source object to create the MemoryDefaults.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * FuzzyThreshold is the minimum fuzzy match score (0..100) to pre-fill
             * the target on extract. Defaults to DefaultFuzzyThreshold when zero.
             * @member
             * @type {number | undefined}
             */
            this["fuzzy_threshold"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryDefaults instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MemoryDefaults}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryDefaults(/** @type {Partial<MemoryDefaults>} */($$parsedSource));
    }
}

/**
 * MergeDefaults governs kapi merge behavior (AD-017).
 */
export class MergeDefaults {
    /**
     * Creates a new MergeDefaults instance.
     * @param {Partial<MergeDefaults>} [$$source = {}] - The source object to create the MergeDefaults.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * ConflictPolicy governs how merge applies a translator's target when
             * an existing on-disk target or content memory TU already has a translation. Valid
             * values: "translator-wins" (default), "existing-wins", "newest-wins".
             * @member
             * @type {string | undefined}
             */
            this["conflict_policy"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeDefaults instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeDefaults}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeDefaults(/** @type {Partial<MergeDefaults>} */($$parsedSource));
    }
}

/**
 * PluginIssue describes a single plugin requirement that is not met.
 */
export class PluginIssue {
    /**
     * Creates a new PluginIssue instance.
     * @param {Partial<PluginIssue>} [$$source = {}] - The source object to create the PluginIssue.
     */
    constructor($$source = {}) {
        if (!("plugin" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["plugin"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "missing" or "version_mismatch"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["required"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["installed_version"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginIssue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginIssue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginIssue(/** @type {Partial<PluginIssue>} */($$parsedSource));
    }
}

/**
 * PluginSpec describes a plugin dependency with version constraints and settings.
 * Supports short form (bare string → version range) and long form (struct).
 * 
 * Short form: okapi: "^1.47.0"
 * Long form:
 * 
 * 	okapi:
 * 	  version: "^0.38.0"
 * 	  framework_version: "^1.47.0"
 * 	  format_priority: 200
 */
export class PluginSpec {
    /**
     * Creates a new PluginSpec instance.
     * @param {Partial<PluginSpec>} [$$source = {}] - The source object to create the PluginSpec.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["framework_version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["format_priority"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginSpec instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginSpec}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginSpec(/** @type {Partial<PluginSpec>} */($$parsedSource));
    }
}

/**
 * PluginStatus reports whether a project's plugin requirements are satisfied
 * by the locally installed plugins.
 */
export class PluginStatus {
    /**
     * Creates a new PluginStatus instance.
     * @param {Partial<PluginStatus>} [$$source = {}] - The source object to create the PluginStatus.
     */
    constructor($$source = {}) {
        if (!("satisfied" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["satisfied"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PluginIssue[] | undefined}
             */
            this["issues"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginStatus}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField1_0($$parsedSource["issues"]);
        }
        return new PluginStatus(/** @type {Partial<PluginStatus>} */($$parsedSource));
    }
}

/**
 * Profile binds governance to one product, and declares the channels that
 * product ships on.
 * 
 * The map key under `profiles:` is the profile's name: the product-axis value
 * its collections carry, and the directory under `.kapi/profiles/` holding the
 * files it overrides. A profile that binds neither a voice nor a vocabulary is
 * still a profile — that directory is the binding, and a project keeping its
 * overrides there should not have to restate every one of them in the recipe.
 */
export class Profile {
    /**
     * Creates a new Profile instance.
     * @param {Partial<Profile>} [$$source = {}] - The source object to create the Profile.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Channels are the surfaces this product's content ships on. A
             * collection binds to one of them through its `channel:`.
             * @member
             * @type {Channel[] | undefined}
             */
            this["channels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Voice is the voice profile governing this product's content, in the
             * same forms as defaults.voice (a bare path, or profile_file / profile /
             * pack). nil keeps defaults.voice.
             * @member
             * @type {VoiceBinding | null | undefined}
             */
            this["voice"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TermStore is a STANDALONE terms store governing this product's content —
             * a file the recipe points at, resolved relative to the project root. Empty
             * is the ordinary case: the project's own store governs.
             * 
             * Spelled `termstore:` rather than `terms:` because a store is not its
             * contents, and because `terms` is already the dnt-check tool's own key for
             * a list of strings. It matches the `--termstore` selector.
             * @member
             * @type {string | undefined}
             */
            this["termstore"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Concept optionally references the concept that names this product, for
             * display. Carried and shape-checked; never resolved during matching.
             * @member
             * @type {string | undefined}
             */
            this["concept"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ValidFrom and ValidTo bound the profile's governance in time — from when
             * until when this profile is the one in force. Recipe-declared as a date
             * (`YYYY-MM-DD`) or an RFC3339 instant, parsed and range-checked at load;
             * empty is unbounded. The window is the same half-open model terms and graph
             * edges carry (ValidFrom inclusive, ValidTo exclusive). ResolveGovernanceAt
             * honours it and `kapi context search` surfaces it.
             * @member
             * @type {string | undefined}
             */
            this["valid_from"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["valid_to"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Profile}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType40;
        const $$createField1_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField0_0($$parsedSource["channels"]);
        }
        if ("voice" in $$parsedSource) {
            $$parsedSource["voice"] = $$createField1_0($$parsedSource["voice"]);
        }
        return new Profile(/** @type {Partial<Profile>} */($$parsedSource));
    }
}

/**
 * RedactionSpec configures content redaction. The sensitive term list itself
 * lives in a dedicated rules file (so it can be gitignored) referenced by
 * Rules; this spec only points at it and selects detection backends. Declared
 * under defaults: project-wide and overridable per content item.
 */
export class RedactionSpec {
    /**
     * Creates a new RedactionSpec instance.
     * @param {Partial<RedactionSpec>} [$$source = {}] - The source object to create the RedactionSpec.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Enabled turns redaction on for extract/merge.
             * @member
             * @type {boolean | undefined}
             */
            this["enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Rules is the path to a redaction rules YAML file.
             * @member
             * @type {string | undefined}
             */
            this["rules"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Detectors selects detection backends: "rules" and/or "entities".
             * @member
             * @type {string[] | undefined}
             */
            this["detectors"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Placeholder overrides the visible stand-in template, e.g.
             * "[REDACTED:{category}]".
             * @member
             * @type {string | undefined}
             */
            this["placeholder"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RedactionSpec instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RedactionSpec}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("detectors" in $$parsedSource) {
            $$parsedSource["detectors"] = $$createField2_0($$parsedSource["detectors"]);
        }
        return new RedactionSpec(/** @type {Partial<RedactionSpec>} */($$parsedSource));
    }
}

/**
 * RequiresMap is the type of KapiProject.Requires — a map of plugin name to
 * semver-style version constraint. It defines a custom UnmarshalYAML that
 * rejects the legacy bare-list form (`requires: [bowrain]`) with an
 * actionable migration hint.
 * @typedef {{ [_ in string]?: string }} RequiresMap
 */

/**
 * SegmentationDefaults governs the opt-in SRX segmentation overlay (AD-017).
 */
export class SegmentationDefaults {
    /**
     * Creates a new SegmentationDefaults instance.
     * @param {Partial<SegmentationDefaults>} [$$source = {}] - The source object to create the SegmentationDefaults.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Source toggles sentence-level segmentation of source text on extract.
             * @member
             * @type {boolean | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SRX optionally points at an SRX rules file. When empty, built-in
             * default rules are used.
             * @member
             * @type {string | undefined}
             */
            this["srx"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SegmentationDefaults instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SegmentationDefaults}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SegmentationDefaults(/** @type {Partial<SegmentationDefaults>} */($$parsedSource));
    }
}

/**
 * ShipGateRule is one recipe `ship_gates` entry: a selector (`when:`) plus the
 * gate that applies where it matches (`gate:`). A bare entry with no `when:` is
 * the catch-all default.
 */
export class ShipGateRule {
    /**
     * Creates a new ShipGateRule instance.
     * @param {Partial<ShipGateRule>} [$$source = {}] - The source object to create the ShipGateRule.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {gate$0.Selector | null | undefined}
             */
            this["when"] = undefined;
        }
        if (!("gate" in $$source)) {
            /**
             * @member
             * @type {GateRef}
             */
            this["gate"] = (new GateRef());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShipGateRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShipGateRule}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType42;
        const $$createField1_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("when" in $$parsedSource) {
            $$parsedSource["when"] = $$createField0_0($$parsedSource["when"]);
        }
        if ("gate" in $$parsedSource) {
            $$parsedSource["gate"] = $$createField1_0($$parsedSource["gate"]);
        }
        return new ShipGateRule(/** @type {Partial<ShipGateRule>} */($$parsedSource));
    }
}

/**
 * VoiceBinding binds a voice profile — to the project under `defaults.voice`,
 * or to a region of the context space under a profile's `voice:`. Exactly one
 * source is expected: a standalone profile YAML (ProfileFile, resolved relative
 * to the project root), a profile in the local voice store (Profile), or a
 * built-in starter pack (Pack).
 * 
 * The short form is the profile file itself — `voice: context/kapi-voice.yaml`
 * — which is what a recipe writes when the profile is a file in the project,
 * as it usually is.
 */
export class VoiceBinding {
    /**
     * Creates a new VoiceBinding instance.
     * @param {Partial<VoiceBinding>} [$$source = {}] - The source object to create the VoiceBinding.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * ProfileFile is the path to a standalone profile YAML, resolved
             * relative to the project root.
             * @member
             * @type {string | undefined}
             */
            this["profile_file"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Profile names a profile in the local voice store.
             * @member
             * @type {string | undefined}
             */
            this["profile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Pack names a built-in starter pack.
             * @member
             * @type {string | undefined}
             */
            this["pack"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VoiceBinding instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VoiceBinding}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VoiceBinding(/** @type {Partial<VoiceBinding>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = ContentItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = FormatSpec.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = RedactionSpec.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = FormatDefaults.createFrom;
const $$createType10 = $Create.Map($Create.Any, $$createType9);
const $$createType11 = MergeDefaults.createFrom;
const $$createType12 = MemoryDefaults.createFrom;
const $$createType13 = SegmentationDefaults.createFrom;
const $$createType14 = AnnotationDefaults.createFrom;
const $$createType15 = VoiceBinding.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
const $$createType18 = $Create.Map($Create.Any, $$createType17);
const $$createType19 = LocaleDefaults.createFrom;
const $$createType20 = $Create.Map($Create.Any, $$createType19);
var $$createType21 = /** @type {(...args: any[]) => any} */(function $$initCreateType21(...args) {
    if ($$createType21 === $$initCreateType21) {
        $$createType21 = $$createType22;
    }
    return $$createType21(...args);
});
const $$createType22 = $Create.Map($Create.Any, $Create.Any);
const $$createType23 = PluginSpec.createFrom;
const $$createType24 = $Create.Map($Create.Any, $$createType23);
const $$createType25 = Defaults.createFrom;
const $$createType26 = Collection.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = flow$0.StepsSpec.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = $Create.Map($Create.Any, $$createType29);
const $$createType31 = Profile.createFrom;
const $$createType32 = $Create.Map($Create.Any, $$createType31);
const $$createType33 = ShipGateRule.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = $Create.Map($Create.Any, $$createType21);
var $$createType36 = /** @type {(...args: any[]) => any} */(function $$initCreateType36(...args) {
    if ($$createType36 === $$initCreateType36) {
        $$createType36 = $$createType4;
    }
    return $$createType36(...args);
});
const $$createType37 = PluginIssue.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = Channel.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = gate$0.Selector.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
const $$createType43 = GateRef.createFrom;
