// GENERATED by scripts/walkthrough-gen from web/walkthroughs/kapi-word-count.scene.yaml.
// Do not edit by hand — change the .scene.yaml and regenerate.
import type { WalkthroughEmbedConfig } from "./types";

const config: WalkthroughEmbedConfig = {
  id: "kapi-word-count",
  scene: "word-count",
  mode: "interactive",
  seed: ["messages.json"],
  files: [],
  steps: [
    {
      command: "kapi stats messages.json",
      narration:
        "Report block, word, character and segment counts to help estimate translation work.",
    },
  ],
};

export default config;
