// GENERATED by scripts/walkthrough-gen from web/walkthroughs/kapi-terminology-pretranslation.scene.yaml.
// Do not edit by hand — change the .scene.yaml and regenerate.
import type { WalkthroughEmbedConfig } from "./types";

const config: WalkthroughEmbedConfig = {
  id: "kapi-terminology-pretranslation",
  scene: "terms-pretranslation",
  mode: "interactive",
  seed: [],
  files: [
    {
      path: "project.memory.json",
      content:
        '{\n  "schemaVersion": "1.0",\n  "kind": "kapi-memory",\n  "entries": [\n    {\n      "id": "mem:en-fr:file-upload",\n      "hintSrcLang": "en",\n      "variants": {\n        "en": [\n          {\n            "text": "File upload"\n          }\n        ],\n        "fr": [\n          {\n            "text": "Téléversement de fichier"\n          }\n        ]\n      },\n      "created": "2026-01-01T00:00:00Z",\n      "updated": "2026-01-01T00:00:00Z"\n    },\n    {\n      "id": "mem:en-fr:settings",\n      "hintSrcLang": "en",\n      "variants": {\n        "en": [\n          {\n            "text": "Settings"\n          }\n        ],\n        "fr": [\n          {\n            "text": "Paramètres"\n          }\n        ]\n      },\n      "created": "2026-01-01T00:00:00Z",\n      "updated": "2026-01-01T00:00:00Z"\n    }\n  ]\n}\n',
    },
    {
      path: "messages_en.json",
      content:
        '{\n  "login_title": "Log in to your dashboard",\n  "login_prompt": "Enter your username and password",\n  "settings_label": "Settings",\n  "upload_heading": "File upload",\n  "encryption_note": "All files use encryption"\n}\n',
    },
  ],
  steps: [
    {
      command: "kapi memory import project.memory.json",
      narration:
        "Load the committed content memory — the store `kapi up` leverages before any AI is asked.",
    },
    {
      command:
        "kapi exec recycle messages_en.json -o step1_tm.json --source-lang en --target-lang fr",
      narration:
        "recycle is the first step of up's default flow. Exact and fuzzy matches fill from the content memory; the rest stay untranslated.",
    },
    {
      command: "kapi pseudo-translate step1_tm.json -o step2_translated.json",
      narration:
        "Everything the content memory did not cover gets a locale-shaped placeholder — in up's default flow, this is where AI translation runs instead.",
    },
    {
      command: "kapi exec term-check step2_translated.json --source-lang en --target-lang fr",
      narration:
        "The same terminology check up runs over each pass's output. Pre-flag violations before any vendor sees the content.",
    },
  ],
};

export default config;
