// GENERATED by scripts/walkthrough-gen from web/walkthroughs/kapi-explain-prompts.scene.yaml.
// Do not edit by hand — change the .scene.yaml and regenerate.
import type { WalkthroughEmbedConfig } from "./types";

const config: WalkthroughEmbedConfig = {
  id: "kapi-explain-prompts",
  scene: "explain-prompts",
  mode: "interactive",
  seed: ["messages.json"],
  files: [
    {
      path: "notice.html",
      content:
        "<html>\n  <body>\n    <p>Click <b>Save</b> to keep your changes</p>\n  </body>\n</html>\n",
    },
  ],
  steps: [
    {
      command:
        "kapi translate messages.json --source-lang en --target-lang fr --provider demo --explain-prompts",
      narration:
        "Start bare. The system turn carries the framework's task and its placeholder constraint. The user turn carries the source text and nothing else — content is data, never instruction.",
    },
    {
      command:
        'kapi translate messages.json --source-lang en --target-lang fr --provider demo --instruction "Informal register. Keep product names in English." --explain-prompts',
      narration:
        "Add an instruction. A new section appears, attributed to the flag that produced it. This is how you steer the model — by adding to the prompt, not by replacing it.",
    },
    {
      command:
        "kapi translate notice.html --source-lang en --target-lang fr --provider demo --explain-prompts",
      narration:
        "This block carries an inline tag, so the prompt gains the tag-fidelity rule — reproduce every tag exactly. A block with no markup never sees it. Note the content turn is still pure content, with the tags rendered as placeholders.",
    },
  ],
};

export default config;
