// GENERATED by scripts/walkthrough-gen from web/walkthroughs/kapi-under-the-hood.scene.yaml.
// Do not edit by hand — change the .scene.yaml and regenerate.
import type { WalkthroughEmbedConfig } from "./types";

const config: WalkthroughEmbedConfig = {
  id: "kapi-under-the-hood",
  scene: "under-the-hood",
  mode: "interactive",
  seed: ["messages.json"],
  files: [
    {
      path: "project.tmx",
      content:
        '<?xml version="1.0" encoding="UTF-8"?>\n<tmx version="1.4">\n  <header creationtool="neokapi" creationtoolversion="1.0"\n          segtype="sentence" o-tmf="unknown" adminlang="en"\n          srclang="en" datatype="plaintext"/>\n  <body>\n    <tu>\n      <tuv xml:lang="en"><seg>Hello, World!</seg></tuv>\n      <tuv xml:lang="fr"><seg>Bonjour le monde !</seg></tuv>\n    </tu>\n    <tu>\n      <tuv xml:lang="en"><seg>See you tomorrow</seg></tuv>\n      <tuv xml:lang="fr"><seg>À demain</seg></tuv>\n    </tu>\n    <tu>\n      <tuv xml:lang="en"><seg>Your cart is empty</seg></tuv>\n      <tuv xml:lang="fr"><seg>Votre panier est vide</seg></tuv>\n    </tu>\n  </body>\n</tmx>\n',
    },
    {
      path: "kapi.yaml",
      content:
        'version: v1\nname: demo\ndefaults:\n  source_language: en\n  target_languages: [fr]\n  flow: tm-recycle\ncontent:\n  - path: messages.json\n    target: "messages.{lang}.json"\nflows:\n  tm-recycle:\n    steps:\n      - tool: recycle\n  leverage-check:\n    steps:\n      - tool: recycle\n      - tool: qa\n',
    },
  ],
  steps: [
    {
      command: "kapi memory import project.tmx",
      narration:
        "Seed the project TM so the plumbing has leverage to work with. up tops up the same store on every merge.",
    },
    {
      command: "kapi exec recycle messages.json -o step1.json --source-lang en --target-lang fr",
      narration:
        "exec runs exactly one registry tool, nothing around it. recycle is the TM step of up's default flow — exact and fuzzy matches fill the targets; the rest stay untranslated.",
    },
    {
      command: "kapi run leverage-check -i messages.json",
      narration:
        "run executes a composed flow once — recycle, then the deterministic qa checks. In a project the pass commits to the project store. up is this pass, looped until every gate is met or the rest parks.",
    },
    {
      command: "kapi extract --target-lang fr",
      narration:
        "extract emits one bilingual XLIFF per source and target pair, pre-filled from the TM — the handoff a human translator works in.",
    },
    {
      command: "kapi merge -i out/messages.en-to-fr.xliff",
      narration:
        "merge applies the returned file back onto the source and writes messages.fr.json. Applied targets also land in the TM, so the next pass starts further ahead.",
    },
  ],
};

export default config;
