// GENERATED by scripts/walkthrough-gen. Do not edit by hand.
//
// Shared shape for the per-walkthrough embed configs. The docs-layer
// KapiGuidedEmbed component reads these to seed + script a <KapiEmbed>; the
// GuidedSteps rail renders the numbered "run the next command" list.

import type { KapiFile } from "@neokapi/kapi-playground";

export interface WalkthroughEmbedStep {
  /** A runnable kapi command, e.g. "kapi word-count messages.json". */
  command: string;
  /** Optional one-line explanation shown beside the step. */
  narration?: string;
}

export interface WalkthroughEmbedConfig {
  /** Walkthrough id (matches the .scene.yaml / .mdx). */
  id: string;
  /** Scene id (the single terminal scene). */
  scene: string;
  /** Whether the page treats the embed (interactive) or video as primary. */
  mode: "interactive" | "video";
  /** Built-in kit fixture names seeded into the cwd (see fixtures.ts). */
  seed: string[];
  /** Inline files written to the cwd before the commands run. */
  files: KapiFile[];
  /** Ordered offline commands the embed runs / the guided rail lists. */
  steps: WalkthroughEmbedStep[];
}
