# Lightweight dev image: base Keycloak + Apple identity provider extension.
#
# The theme JAR and realm.json are mounted as volumes in compose.yaml,
# so they don't need to be baked into this image.

FROM quay.io/keycloak/keycloak:26.1

# Install Apple identity provider extension (Sign in with Apple).
# https://github.com/klausbetz/apple-identity-provider-keycloak
ADD --chmod=644 https://github.com/klausbetz/apple-identity-provider-keycloak/releases/download/1.14.0/apple-identity-provider-1.14.0.jar /opt/keycloak/providers/apple-identity-provider.jar
