//go:build integration

package plaintext_test

// Code generated by gen-test-stubs from Surefire XML. DO NOT EDIT.
// To implement a test, move it to the appropriate test file and
// replace t.Skip("pending") with test logic.

import "testing"

// ---- ParaPlainTextFilterTest (13 tests) ----

// okapi: ParaPlainTextFilterTest#testCancel
func TestRead_Cancel(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testEmptyInput
func TestRead_EmptyInput(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testEvents
func TestRead_Events(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testFiles
func TestRead_Files(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testFiles2
func TestRead_Files2(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testLineNumbers
func TestRead_LineNumbers(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testNameAndMimeType
func TestRead_NameAndMimeType(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testParagraphs
func TestRead_Paragraphs(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testSkeleton
func TestRead_Skeleton(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testSkeleton2
func TestRead_Skeleton2(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testSkeleton3
func TestRead_Skeleton3(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testSkeleton4
func TestRead_Skeleton4(t *testing.T) {
	t.Skip("pending")
}

// okapi: ParaPlainTextFilterTest#testSkeleton5
func TestRead_Skeleton5(t *testing.T) {
	t.Skip("pending")
}

// ---- PlainTextFilterTest (5 tests) ----

// okapi: PlainTextFilterTest#testConfigurations
func TestRead_Configurations(t *testing.T) {
	t.Skip("pending")
}

// okapi: PlainTextFilterTest#testDoubleExtraction
func TestRoundTrip_DoubleExtraction(t *testing.T) {
	t.Skip("pending")
}

// okapi: PlainTextFilterTest#testLoadParams
func TestRead_LoadParams(t *testing.T) {
	t.Skip("pending")
}

// okapi: PlainTextFilterTest#testStartDocument
func TestRead_StartDocument(t *testing.T) {
	t.Skip("pending")
}

// okapi: PlainTextFilterTest#testSynchronization
func TestRead_Synchronization(t *testing.T) {
	t.Skip("pending")
}

// ---- RegexPlainTextFilterTest (1 tests) ----

// okapi: RegexPlainTextFilterTest#testParameters
func TestRead_Parameters(t *testing.T) {
	t.Skip("pending")
}

// ---- SplicedLinesFilterTest (1 tests) ----

// okapi: SplicedLinesFilterTest#testCombinedLines
func TestRead_CombinedLines(t *testing.T) {
	t.Skip("pending")
}
