// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Bowrain UI backend. It exposes methods that can be
 * bound to a Wails frontend or called from tests.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jsontext$0 from "../../../../../../../encoding/json/jsontext/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../../core/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as locale$0 from "../../../../core/locale/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbandonChangeset abandons a change-set.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function AbandonChangeset(workspaceSlug, changesetID) {
    return $Call.ByID(2548870795, workspaceSlug, changesetID);
}

/**
 * AddConcept adds a new concept to the terms store.
 * @param {$models.AddConceptRequest} req
 * @returns {$CancellablePromise<$models.ConceptInfo | null>}
 */
export function AddConcept(req) {
    return $Call.ByID(1629877469, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AddConceptComment posts a comment to a concept thread.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @param {$models.AddCommentArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function AddConceptComment(workspaceSlug, conceptID, req) {
    return $Call.ByID(1021175558, workspaceSlug, conceptID, req);
}

/**
 * AddConceptRelation adds a typed edge from a concept.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @param {$models.AddConceptRelationArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function AddConceptRelation(workspaceSlug, conceptID, req) {
    return $Call.ByID(1519794041, workspaceSlug, conceptID, req);
}

/**
 * AddItems imports items into a project. Local file ingest is a server-side
 * concern (CLAUDE.md): when connected, files are uploaded to the server, which
 * parses and extracts blocks — the local store is a cache filled lazily on
 * read. Only offline does the desktop parse locally, seeding the cache and
 * queueing the upload for replay on reconnect.
 * 
 * This one stays hand-written rather than using writeThroughResult: it does
 * pre-work (collectUploadFiles) that can short-circuit before any server call,
 * and the file paths, not the collected bytes, drive the local fallback — a
 * shape the generic helper deliberately does not model.
 * @param {string} projectID
 * @param {string[]} filePaths
 * @returns {$CancellablePromise<$models.ProjectInfo | null>}
 */
export function AddItems(projectID, filePaths) {
    return $Call.ByID(3605832733, projectID, filePaths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * AddMember adds a user to a workspace with the given role.
 * @param {string} workspaceSlug
 * @param {string} userID
 * @param {string} role
 * @returns {$CancellablePromise<void>}
 */
export function AddMember(workspaceSlug, userID, role) {
    return $Call.ByID(892954425, workspaceSlug, userID, role);
}

/**
 * AddMemoryEntry adds a new entry to the content memory.
 * @param {string} projectID
 * @param {string} source
 * @param {string} target
 * @param {string} sourceLocale
 * @param {string} targetLocale
 * @returns {$CancellablePromise<$models.MemoryEntryInfo | null>}
 */
export function AddMemoryEntry(projectID, source, target, sourceLocale, targetLocale) {
    return $Call.ByID(1337082584, projectID, source, target, sourceLocale, targetLocale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * AddObservation attaches a piece of external evidence to a concept.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @param {$models.AddObservationArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function AddObservation(workspaceSlug, conceptID, req) {
    return $Call.ByID(3494012171, workspaceSlug, conceptID, req);
}

/**
 * AddPilot binds a change-set to a project's content stream.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @param {$models.StartPilotArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function AddPilot(workspaceSlug, changesetID, req) {
    return $Call.ByID(3466861303, workspaceSlug, changesetID, req);
}

/**
 * AppendChangesetOp appends an ordered op to a draft change-set.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @param {$models.AddChangesetOpArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function AppendChangesetOp(workspaceSlug, changesetID, req) {
    return $Call.ByID(1794848911, workspaceSlug, changesetID, req);
}

/**
 * ApproveChangeset records an approving review verdict.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @param {$models.ReviewArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ApproveChangeset(workspaceSlug, changesetID, req) {
    return $Call.ByID(330321919, workspaceSlug, changesetID, req);
}

/**
 * BulkApplyMemory writes the best content-memory match above the threshold
 * into each selected block's target. The match is resolved against the
 * workspace memory the server holds, so offline every block is skipped rather
 * than matched against a different corpus.
 * @param {string} projectID
 * @param {$models.BulkApplyMemoryArgs} req
 * @returns {$CancellablePromise<$models.BulkApplyMemoryView | null>}
 */
export function BulkApplyMemory(projectID, req) {
    return $Call.ByID(357518507, projectID, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * BulkReviewBlocks applies one review decision across a selection of blocks.
 * Connected it is one request; offline each block goes through the same local
 * review path a single decision takes, so a block that refuses is reported in
 * its own result either way.
 * @param {string} projectID
 * @param {$models.BulkReviewArgs} req
 * @returns {$CancellablePromise<$models.BulkReviewView | null>}
 */
export function BulkReviewBlocks(projectID, req) {
    return $Call.ByID(1195520622, projectID, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * CancelLogin cancels any active PKCE login flow.
 * @returns {$CancellablePromise<void>}
 */
export function CancelLogin() {
    return $Call.ByID(3730504007);
}

/**
 * ChangesetCounts returns the workspace's change-sets bucketed by lifecycle
 * status.
 * @param {string} workspaceSlug
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ChangesetCounts(workspaceSlug) {
    return $Call.ByID(3801625284, workspaceSlug);
}

/**
 * CloseProject closes a project and releases its resources.
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function CloseProject(projectID) {
    return $Call.ByID(3843799473, projectID);
}

/**
 * ConceptLocaleCoverage returns per-locale concept coverage over the whole
 * workspace, most complete locale first.
 * @param {string} workspaceSlug
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ConceptLocaleCoverage(workspaceSlug) {
    return $Call.ByID(1584689220, workspaceSlug);
}

/**
 * ConceptStatusCounts returns the workspace vocabulary counted by term
 * lifecycle status. A concept counts under every status one of its terms
 * carries, so the buckets overlap and do not sum to the total.
 * @param {string} workspaceSlug
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ConceptStatusCounts(workspaceSlug) {
    return $Call.ByID(3349924666, workspaceSlug);
}

/**
 * ConfigureConnector creates and stores a connector instance.
 * @param {string} connectorType
 * @param {{ [_ in string]?: string }} config
 * @returns {$CancellablePromise<$models.ConnectorInfo | null>}
 */
export function ConfigureConnector(connectorType, config) {
    return $Call.ByID(4176435679, connectorType, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ConnectToServer establishes a REST/SSE connection to the given server URL
 * using stored credentials. The URL should be the HTTP base URL
 * (e.g. "http://localhost:8080").
 * @param {string} serverURL
 * @returns {$CancellablePromise<void>}
 */
export function ConnectToServer(serverURL) {
    return $Call.ByID(2777579616, serverURL);
}

/**
 * CreateChangeset opens a new draft change-set.
 * @param {string} workspaceSlug
 * @param {$models.CreateChangesetArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function CreateChangeset(workspaceSlug, req) {
    return $Call.ByID(162210356, workspaceSlug, req);
}

/**
 * CreateConcept creates a concept via the REST /concepts surface. The body
 * reuses the AddConceptRequest shape (project_id, domain, definition, terms).
 * @param {string} workspaceSlug
 * @param {$models.AddConceptRequest} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function CreateConcept(workspaceSlug, req) {
    return $Call.ByID(2351091952, workspaceSlug, req);
}

/**
 * CreateInvite creates a workspace invitation.
 * @param {string} workspaceSlug
 * @param {string} email
 * @param {string} role
 * @param {number} maxUses
 * @returns {$CancellablePromise<$models.InviteInfo>}
 */
export function CreateInvite(workspaceSlug, email, role, maxUses) {
    return $Call.ByID(1479401621, workspaceSlug, email, role, maxUses).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * CreateMarket defines a new market scope.
 * @param {string} workspaceSlug
 * @param {$models.MarketArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function CreateMarket(workspaceSlug, req) {
    return $Call.ByID(145657116, workspaceSlug, req);
}

/**
 * CreateProject creates a new translation project.
 * @param {string} name
 * @param {string} sourceLang
 * @param {string[]} targetLangs
 * @returns {$CancellablePromise<$models.ProjectInfo | null>}
 */
export function CreateProject(name, sourceLang, targetLangs) {
    return $Call.ByID(4069855585, name, sourceLang, targetLangs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CreateStoreVersion creates a version snapshot in the content store.
 * @param {string} projectID
 * @param {string} label
 * @param {string} description
 * @returns {$CancellablePromise<store$0.Version | null>}
 */
export function CreateStoreVersion(projectID, label, description) {
    return $Call.ByID(1139403919, projectID, label, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * DeleteConcept removes a concept from the terms store.
 * @param {string} projectID
 * @param {string} conceptID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConcept(projectID, conceptID) {
    return $Call.ByID(3557611909, projectID, conceptID);
}

/**
 * DeleteConceptComment removes a comment from a concept thread.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @param {string} commentID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConceptComment(workspaceSlug, conceptID, commentID) {
    return $Call.ByID(584017598, workspaceSlug, conceptID, commentID);
}

/**
 * DeleteConceptRelation removes a typed edge from a concept.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @param {string} relationID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConceptRelation(workspaceSlug, conceptID, relationID) {
    return $Call.ByID(728159105, workspaceSlug, conceptID, relationID);
}

/**
 * DeleteFlowDefinition removes a project flow definition on the server.
 * @param {string} projectID
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFlowDefinition(projectID, id) {
    return $Call.ByID(1213282658, projectID, id);
}

/**
 * DeleteInvite revokes a workspace invitation.
 * @param {string} workspaceSlug
 * @param {string} inviteID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteInvite(workspaceSlug, inviteID) {
    return $Call.ByID(2213394222, workspaceSlug, inviteID);
}

/**
 * DeleteMarket removes a market scope.
 * @param {string} workspaceSlug
 * @param {string} marketID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMarket(workspaceSlug, marketID) {
    return $Call.ByID(1340556279, workspaceSlug, marketID);
}

/**
 * DeleteMemoryEntry deletes a content-memory entry by ID.
 * @param {string} projectID
 * @param {string} entryID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMemoryEntry(projectID, entryID) {
    return $Call.ByID(3893874464, projectID, entryID);
}

/**
 * DeleteObservation removes an observation from a concept.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @param {string} observationID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteObservation(workspaceSlug, conceptID, observationID) {
    return $Call.ByID(3297455731, workspaceSlug, conceptID, observationID);
}

/**
 * DeleteProviderConfig removes a provider configuration on the server.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProviderConfig(id) {
    return $Call.ByID(1970959020, id);
}

/**
 * DetectFormat detects the format of a file by its extension.
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function DetectFormat(filePath) {
    return $Call.ByID(661014944, filePath);
}

/**
 * Disconnect closes the server connection.
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(668361826);
}

/**
 * EvaluateRule computes the blast radius of promoting a candidate rule across a
 * project's content (how many blocks it newly flags / resolves, per collection).
 * @param {string} workspaceSlug
 * @param {string} profileID
 * @param {$models.EvaluateRuleArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function EvaluateRule(workspaceSlug, profileID, req) {
    return $Call.ByID(913799173, workspaceSlug, profileID, req);
}

/**
 * ExportTermsJSON exports the terms store as JSON.
 * @param {string} projectID
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportTermsJSON(projectID, name) {
    return $Call.ByID(2197315403, projectID, name);
}

/**
 * ExportTranslatedItem is no longer supported in the desktop app.
 * Source bytes are no longer stored in the Item model. Use the CLI
 * ('kapi pull') for translated file export.
 * @param {string} $0
 * @param {string} itemName
 * @param {string} $2
 * @returns {$CancellablePromise<string>}
 */
export function ExportTranslatedItem($0, itemName, $2) {
    return $Call.ByID(794357047, $0, itemName, $2);
}

/**
 * FetchContent fetches content from a connector into the content store.
 * @param {string} connectorID
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.ContentItemInfo[]>}
 */
export function FetchContent(connectorID, projectID) {
    return $Call.ByID(704585525, connectorID, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetBlock returns one block in the same shape the block page returns its
 * elements: server-side when connected, from the local working copy offline.
 * 
 * It is what a surface reads after writing a target, instead of rebuilding the
 * block from its own request — the demotion an edit triggers is the store's
 * decision on both paths (applyTargetTextEdit locally, the server's
 * demoteStaleReviewOnEdit remotely), and a second copy of that rule in
 * TypeScript is a copy that can disagree.
 * @param {string} projectID
 * @param {string} blockID
 * @returns {$CancellablePromise<$models.BlockInfo | null>}
 */
export function GetBlock(projectID, blockID) {
    return $Call.ByID(1186645613, projectID, blockID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetBlockCounts answers an item's progress with one aggregate query. The
 * filter's Status is ignored — the histogram is what the call reports.
 * @param {string} projectID
 * @param {string} itemName
 * @param {$models.EditorBlockFilter} filter
 * @returns {$CancellablePromise<$models.BlockCountsView | null>}
 */
export function GetBlockCounts(projectID, itemName, filter) {
    return $Call.ByID(1836546701, projectID, itemName, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetChangeset returns a single change-set with its ops, reviews, and pilots.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetChangeset(workspaceSlug, changesetID) {
    return $Call.ByID(2747190700, workspaceSlug, changesetID);
}

/**
 * GetChangesetBlastRadius returns the impact of a change-set over stored content.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetChangesetBlastRadius(workspaceSlug, changesetID) {
    return $Call.ByID(3628701404, workspaceSlug, changesetID);
}

/**
 * GetCollabSession returns the presence-collaboration session info for the
 * currently connected server + workspace. It surfaces the keychain auth token,
 * the HTTP server URL, the active workspace slug, and the current user so the
 * frontend can open the Yjs awareness WebSocket (params.token) just like the
 * web translate view.
 * 
 * Returns an error when not connected to a server — presence is a server
 * feature, so there is nothing to join in local/standalone mode.
 * @returns {$CancellablePromise<$models.CollabSession>}
 */
export function GetCollabSession() {
    return $Call.ByID(1897887727).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * GetConcept returns a single concept by id.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetConcept(workspaceSlug, conceptID) {
    return $Call.ByID(2000513960, workspaceSlug, conceptID);
}

/**
 * GetConceptBlastRadius returns the where-used footprint of a concept.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetConceptBlastRadius(workspaceSlug, conceptID) {
    return $Call.ByID(3260453664, workspaceSlug, conceptID);
}

/**
 * GetConceptProjects returns which projects use a concept, from the workspace
 * context graph — two hops out of one vocabulary node rather than a scan over
 * every stored block. query is the already-encoded narrowing (project, at,
 * market, limit), empty for the whole workspace at now.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @param {string} query
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetConceptProjects(workspaceSlug, conceptID, query) {
    return $Call.ByID(4138382154, workspaceSlug, conceptID, query);
}

/**
 * GetConceptStory returns a concept's merged chronological timeline.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetConceptStory(workspaceSlug, conceptID) {
    return $Call.ByID(4032379005, workspaceSlug, conceptID);
}

/**
 * GetConnectionState returns the current connection info.
 * If BOWRAIN_TOKEN is set and no connection exists, auto-connects to the
 * server (for CI/headless mode where interactive login is not possible).
 * @returns {$CancellablePromise<$models.ConnectionInfo>}
 */
export function GetConnectionState() {
    return $Call.ByID(3416146777).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetConnectorStatus returns the sync status of a connector.
 * @param {string} connectorID
 * @returns {$CancellablePromise<$models.SyncStatusInfo | null>}
 */
export function GetConnectorStatus(connectorID) {
    return $Call.ByID(2803823489, connectorID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GetCurrentWorkspace returns the active workspace.
 * @returns {$CancellablePromise<$models.WorkspaceInfo>}
 */
export function GetCurrentWorkspace() {
    return $Call.ByID(1584343218).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * GetDefaultServerURL returns the default server URL for the desktop app.
 * It checks the BOWRAIN_SERVER_URL environment variable first, falling back
 * to the Bowrain SaaS instance URL.
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultServerURL() {
    return $Call.ByID(3615231647);
}

/**
 * GetFailedChangesCount returns the number of queued offline changes the
 * server permanently rejected on replay (4xx). Exposed to the frontend so it
 * can surface that some offline edits did not apply.
 * @returns {$CancellablePromise<number>}
 */
export function GetFailedChangesCount() {
    return $Call.ByID(1119355181);
}

/**
 * GetFlowDefinition returns a specific flow definition by id from the server.
 * @param {string} projectID
 * @param {string} id
 * @returns {$CancellablePromise<$models.FlowDefinitionInfo | null>}
 */
export function GetFlowDefinition(projectID, id) {
    return $Call.ByID(1916918101, projectID, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetItem returns one item's metadata without the project's whole item list.
 * @param {string} projectID
 * @param {string} itemName
 * @returns {$CancellablePromise<$models.ItemView | null>}
 */
export function GetItem(projectID, itemName) {
    return $Call.ByID(3534021163, projectID, itemName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * @param {string} projectID
 * @param {string} itemName
 * @returns {$CancellablePromise<$models.BlockInfo[]>}
 */
export function GetItemBlocks(projectID, itemName) {
    return $Call.ByID(3766337077, projectID, itemName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetKnownLocales returns a curated list of well-known BCP-47 locales with display names.
 * @returns {$CancellablePromise<locale$0.LocaleInfo[]>}
 */
export function GetKnownLocales() {
    return $Call.ByID(2350617666).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GetLocaleDisplayName returns the English display name for a BCP-47 locale code.
 * @param {string} code
 * @returns {$CancellablePromise<string>}
 */
export function GetLocaleDisplayName(code) {
    return $Call.ByID(4205376439, code);
}

/**
 * GetMemoryCount returns the total number of entries in the content memory.
 * @param {string} projectID
 * @returns {$CancellablePromise<number>}
 */
export function GetMemoryCount(projectID) {
    return $Call.ByID(653942830, projectID);
}

/**
 * GetMemoryEntries searches the content memory with optional query and locale filters.
 * @param {string} projectID
 * @param {string} query
 * @param {string} sourceLocale
 * @param {string} targetLocale
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<$models.MemorySearchResult | null>}
 */
export function GetMemoryEntries(projectID, query, sourceLocale, targetLocale, offset, limit) {
    return $Call.ByID(3771097165, projectID, query, sourceLocale, targetLocale, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * GetPendingChangesCount returns the number of queued offline changes.
 * Exposed to the frontend so it can show a pending sync indicator.
 * @returns {$CancellablePromise<number>}
 */
export function GetPendingChangesCount() {
    return $Call.ByID(3204097911);
}

/**
 * GetPendingReview pages the translation review queue: server-side when
 * connected, from the local store offline — the same predicate either way.
 * @param {string} projectID
 * @param {string[]} locales
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.PendingReviewPageView | null>}
 */
export function GetPendingReview(projectID, locales, limit, offset) {
    return $Call.ByID(883386567, projectID, locales, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * GetProject returns the current project info.
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.ProjectInfo | null>}
 */
export function GetProject(projectID) {
    return $Call.ByID(999425817, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetServerWorkspaces returns workspaces from the connected server.
 * @returns {$CancellablePromise<$models.WorkspaceInfo[]>}
 */
export function GetServerWorkspaces() {
    return $Call.ByID(3159397869).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * GetSuggestedRules returns the candidate rules a profile's corrections have
 * produced. minCount filters by correction count (0 = server default); all,
 * when true, includes already-decided candidates (promoted/rejected) as history.
 * @param {string} workspaceSlug
 * @param {string} profileID
 * @param {number} minCount
 * @param {boolean} all
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetSuggestedRules(workspaceSlug, profileID, minCount, all) {
    return $Call.ByID(3867399110, workspaceSlug, profileID, minCount, all);
}

/**
 * GetTermCount returns the total number of concepts in the terms store.
 * @param {string} projectID
 * @returns {$CancellablePromise<number>}
 */
export function GetTermCount(projectID) {
    return $Call.ByID(2826518989, projectID);
}

/**
 * GetTerms searches the terms store.
 * @param {string} projectID
 * @param {string} query
 * @param {string} sourceLocale
 * @param {string} targetLocale
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<$models.TermSearchResult | null>}
 */
export function GetTerms(projectID, query, sourceLocale, targetLocale, offset, limit) {
    return $Call.ByID(3424415079, projectID, query, sourceLocale, targetLocale, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * GetToolSchema returns a tool's option schema as the connected server's
 * registry holds it (GET /api/v1/tools/{name}/schema), so a flow step edited
 * on the desktop offers the options the server will run the flow with. A tool
 * without a schema is nil. Offline, the desktop's own registry answers, the
 * way ListFlowDefinitions falls back to the built-in flows.
 * @param {string} name
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetToolSchema(name) {
    return $Call.ByID(3975622697, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * GetVersion returns the application version information.
 * @returns {$CancellablePromise<$models.VersionInfo>}
 */
export function GetVersion() {
    return $Call.ByID(663291304).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * GetVoiceDrift returns the voice compliance drift analysis for a project.
 * @param {string} workspaceSlug
 * @param {string} projectID
 * @param {number} recentDays
 * @param {number} minScore
 * @param {number} dropPoints
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetVoiceDrift(workspaceSlug, projectID, recentDays, minScore, dropPoints) {
    return $Call.ByID(2179001685, workspaceSlug, projectID, recentDays, minScore, dropPoints);
}

/**
 * GetVoiceProfile returns a single voice profile.
 * @param {string} workspaceSlug
 * @param {string} profileID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetVoiceProfile(workspaceSlug, profileID) {
    return $Call.ByID(1784809427, workspaceSlug, profileID);
}

/**
 * GetVoiceRollup returns the workspace voice compliance rollup from the
 * connected server.
 * 
 * The rollup is the server's aggregation: it reads stored per-project scores
 * and resolves each project's effective profile through a ladder (collection →
 * stream → project → workspace default) that lives server-side. Composing it
 * from per-project reads produces a different board — a blank profile column
 * and a trend derived from a different window — so offline this returns the
 * empty rollup marked Offline rather than a locally computed one.
 * @param {string} workspaceSlug
 * @param {$models.VoiceRollupArgs} args
 * @returns {$CancellablePromise<$models.VoiceRollupResult>}
 */
export function GetVoiceRollup(workspaceSlug, args) {
    return $Call.ByID(647021252, workspaceSlug, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * GetVoiceScores returns stored voice compliance scores for a project.
 * @param {string} workspaceSlug
 * @param {string} projectID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetVoiceScores(workspaceSlug, projectID) {
    return $Call.ByID(1804370781, workspaceSlug, projectID);
}

/**
 * GetVoiceTrends returns voice compliance score trends for a project.
 * @param {string} workspaceSlug
 * @param {string} projectID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetVoiceTrends(workspaceSlug, projectID) {
    return $Call.ByID(1940966638, workspaceSlug, projectID);
}

/**
 * GetWordCount returns word and character counts for an item.
 * @param {string} projectID
 * @param {string} itemName
 * @returns {$CancellablePromise<$models.WordCountResult | null>}
 */
export function GetWordCount(projectID, itemName) {
    return $Call.ByID(1179732963, projectID, itemName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * HandleAuthURL processes a bowrain:// URL received via the OS protocol handler.
 * Expected format: bowrain://auth/callback?token=...&refresh_token=...&user=...&name=...
 * @param {string} rawURL
 * @returns {$CancellablePromise<void>}
 */
export function HandleAuthURL(rawURL) {
    return $Call.ByID(3257686637, rawURL);
}

/**
 * HandleDeepLink processes a deep link web URL (after stripping the "bowrain:" prefix).
 * The URL is a standard web URL like https://bowrain.cloud/ws/acme/projects/proj_123.
 * It parses path components and emits a "deep-link-project" event to the frontend.
 * @param {string} webURL
 * @returns {$CancellablePromise<void>}
 */
export function HandleDeepLink(webURL) {
    return $Call.ByID(2634747220, webURL);
}

/**
 * ImportTermsCSV imports terms from CSV content into the terms store.
 * @param {string} projectID
 * @param {string} csvContent
 * @param {string} sourceLocale
 * @param {string} targetLocale
 * @param {string} domain
 * @param {boolean} hasHeader
 * @returns {$CancellablePromise<number>}
 */
export function ImportTermsCSV(projectID, csvContent, sourceLocale, targetLocale, domain, hasHeader) {
    return $Call.ByID(1757479876, projectID, csvContent, sourceLocale, targetLocale, domain, hasHeader);
}

/**
 * ImportTermsJSON imports terms from JSON content into the terms store.
 * @param {string} projectID
 * @param {string} jsonContent
 * @returns {$CancellablePromise<number>}
 */
export function ImportTermsJSON(projectID, jsonContent) {
    return $Call.ByID(2593803262, projectID, jsonContent);
}

/**
 * InitContentStore re-initializes the content store with the given database path.
 * @param {string} dbPath
 * @returns {$CancellablePromise<void>}
 */
export function InitContentStore(dbPath) {
    return $Call.ByID(2593375276, dbPath);
}

/**
 * JudgeChannelAliasProposal settles one proposal. Both verdicts are records:
 * neither rewrites a slug in any recipe, because a project resolves its own
 * coordinates offline.
 * @param {string} workspaceSlug
 * @param {$models.ChannelAliasJudgementArgs} args
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function JudgeChannelAliasProposal(workspaceSlug, args) {
    return $Call.ByID(1653313632, workspaceSlug, args);
}

/**
 * ListChangesets returns the workspace change-sets, optionally filtered by status.
 * @param {string} workspaceSlug
 * @param {string} status
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListChangesets(workspaceSlug, status) {
    return $Call.ByID(1452496417, workspaceSlug, status);
}

/**
 * ListChannelAliasProposals returns the workspace's channel-slug equivalence
 * proposals — the pairs two of its projects spell differently that look like
 * one channel. An empty status returns every one.
 * @param {string} workspaceSlug
 * @param {string} status
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListChannelAliasProposals(workspaceSlug, status) {
    return $Call.ByID(2483893220, workspaceSlug, status);
}

/**
 * ListConceptComments returns the discussion thread on a concept.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListConceptComments(workspaceSlug, conceptID) {
    return $Call.ByID(122407102, workspaceSlug, conceptID);
}

/**
 * ListConceptRelations returns the typed edges of a concept. asOf (RFC3339) and
 * market scope the read; empty values omit the corresponding query param.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @param {string} asOf
 * @param {string} market
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListConceptRelations(workspaceSlug, conceptID, asOf, market) {
    return $Call.ByID(1508991505, workspaceSlug, conceptID, asOf, market);
}

/**
 * ListConcepts searches the workspace concept/terminology graph. The shape is
 * opaque to the proxy; the frontend has the TermSearchResult type.
 * @param {string} workspaceSlug
 * @param {$models.ListConceptsArgs} params
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListConcepts(workspaceSlug, params) {
    return $Call.ByID(1388878909, workspaceSlug, params);
}

/**
 * ListConnectorTypes returns all available connector type names.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListConnectorTypes() {
    return $Call.ByID(1554488048).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * ListConnectors returns all active connector instances.
 * @returns {$CancellablePromise<$models.ConnectorInfo[]>}
 */
export function ListConnectors() {
    return $Call.ByID(3954342840).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * ListContentItems lists content available from a connector.
 * @param {string} connectorID
 * @returns {$CancellablePromise<$models.ContentItemInfo[]>}
 */
export function ListContentItems(connectorID) {
    return $Call.ByID(1917252895, connectorID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * ListContextProfiles returns the workspace's governance profiles — the points
 * its content occupies and what governs each.
 * @param {string} workspaceSlug
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListContextProfiles(workspaceSlug) {
    return $Call.ByID(375557869, workspaceSlug);
}

/**
 * ListFlowDefinitions returns the project's flows (built-in + project-stored)
 * from the server. When offline, only the built-in flows are returned.
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.FlowDefinitionInfo[]>}
 */
export function ListFlowDefinitions(projectID) {
    return $Call.ByID(92689182, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType47($result);
    }));
}

/**
 * ListFormats returns all registered formats with metadata.
 * @returns {$CancellablePromise<$models.FormatInfo[]>}
 */
export function ListFormats() {
    return $Call.ByID(2901617344).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * ListInvites returns pending invitations for a workspace.
 * @param {string} workspaceSlug
 * @returns {$CancellablePromise<$models.InviteInfo[]>}
 */
export function ListInvites(workspaceSlug) {
    return $Call.ByID(1133678686, workspaceSlug).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType50($result);
    }));
}

/**
 * ListMarkets returns the workspace-defined market scopes.
 * @param {string} workspaceSlug
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListMarkets(workspaceSlug) {
    return $Call.ByID(3635256721, workspaceSlug);
}

/**
 * ListMembers returns the members of a workspace.
 * @param {string} workspaceSlug
 * @returns {$CancellablePromise<$models.MemberInfo[]>}
 */
export function ListMembers(workspaceSlug) {
    return $Call.ByID(557660227, workspaceSlug).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType52($result);
    }));
}

/**
 * ListObservations returns the external evidence attached to a concept.
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListObservations(workspaceSlug, conceptID) {
    return $Call.ByID(3990992331, workspaceSlug, conceptID);
}

/**
 * ListPlugins returns the manifest-driven plugins discovered in the
 * configured plugin directory.
 * @returns {$CancellablePromise<$models.PluginInfo[]>}
 */
export function ListPlugins() {
    return $Call.ByID(776322992).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType54($result);
    }));
}

/**
 * ListProjectFiles returns the items in a project.
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.ProjectItem[]>}
 */
export function ListProjectFiles(projectID) {
    return $Call.ByID(2403520224, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType56($result);
    }));
}

/**
 * ListProjects returns all open projects.
 * @returns {$CancellablePromise<$models.ProjectInfo[]>}
 */
export function ListProjects() {
    return $Call.ByID(371450674).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType57($result);
    }));
}

/**
 * ListProviderConfigs returns all saved AI provider configurations from the server.
 * @returns {$CancellablePromise<$models.ProviderConfigInfo[]>}
 */
export function ListProviderConfigs() {
    return $Call.ByID(3735242532).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType59($result);
    }));
}

/**
 * ListStoreProjects returns all projects in the content store.
 * @returns {$CancellablePromise<(store$0.Project | null)[]>}
 */
export function ListStoreProjects() {
    return $Call.ByID(4233071499).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType62($result);
    }));
}

/**
 * ListStoreVersions lists versions for a project.
 * @param {string} projectID
 * @returns {$CancellablePromise<(store$0.Version | null)[]>}
 */
export function ListStoreVersions(projectID) {
    return $Call.ByID(1240071736, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType63($result);
    }));
}

/**
 * ListTools returns all available tools.
 * @returns {$CancellablePromise<$models.ToolInfo[]>}
 */
export function ListTools() {
    return $Call.ByID(3952806715).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType65($result);
    }));
}

/**
 * ListVoiceProfiles returns the voice profiles for a workspace.
 * The shape is opaque to the proxy; the frontend has the VoiceProfile type.
 * @param {string} workspaceSlug
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function ListVoiceProfiles(workspaceSlug) {
    return $Call.ByID(1803524732, workspaceSlug);
}

/**
 * ListWorkspaces returns the workspaces available to the current user.
 * When connected to a server, returns server workspaces; otherwise returns
 * a single "Personal" local workspace.
 * @returns {$CancellablePromise<$models.WorkspaceInfo[]>}
 */
export function ListWorkspaces() {
    return $Call.ByID(3303885562).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * LoadPlugins discovers manifest-driven plugins from the configured
 * plugin directory and caches the result. Safe to call from a goroutine.
 * Errors are logged and otherwise ignored — a missing or empty plugin
 * dir is a normal state for a fresh install.
 * @returns {$CancellablePromise<void>}
 */
export function LoadPlugins() {
    return $Call.ByID(686613052);
}

/**
 * Logout removes stored auth and disconnects.
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(329111662);
}

/**
 * LookupMemoryForBlock looks up content-memory matches for a specific block.
 * @param {string} projectID
 * @param {string} itemName
 * @param {string} blockID
 * @param {string} targetLocale
 * @returns {$CancellablePromise<$models.MemoryMatchInfo[]>}
 */
export function LookupMemoryForBlock(projectID, itemName, blockID, targetLocale) {
    return $Call.ByID(892094965, projectID, itemName, blockID, targetLocale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType67($result);
    }));
}

/**
 * LookupTerms looks up terms matching the given text.
 * @param {string} projectID
 * @param {string} text
 * @param {string} sourceLocale
 * @param {string} targetLocale
 * @returns {$CancellablePromise<$models.TermLookupResult | null>}
 */
export function LookupTerms(projectID, text, sourceLocale, targetLocale) {
    return $Call.ByID(223814221, projectID, text, sourceLocale, targetLocale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType69($result);
    }));
}

/**
 * LookupTermsForBlock looks up term matches in a specific block's source text.
 * @param {string} projectID
 * @param {string} itemName
 * @param {string} blockID
 * @param {string} targetLocale
 * @returns {$CancellablePromise<$models.BlockTermMatch[]>}
 */
export function LookupTermsForBlock(projectID, itemName, blockID, targetLocale) {
    return $Call.ByID(1112384681, projectID, itemName, blockID, targetLocale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType71($result);
    }));
}

/**
 * MemoryTranslateItem leverages content memory to translate blocks. Routing
 * mirrors PseudoTranslateItem: server-first when connected, local cache with a
 * queued replay when offline.
 * @param {string} projectID
 * @param {string} itemName
 * @param {string} targetLocale
 * @returns {$CancellablePromise<$models.TranslationStats | null>}
 */
export function MemoryTranslateItem(projectID, itemName, targetLocale) {
    return $Call.ByID(1431073436, projectID, itemName, targetLocale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType73($result);
    }));
}

/**
 * MergeChangeset merges an approved change-set into the live graph.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function MergeChangeset(workspaceSlug, changesetID) {
    return $Call.ByID(3660554460, workspaceSlug, changesetID);
}

/**
 * OpenFileInOS opens a file using the OS default application.
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function OpenFileInOS(filePath) {
    return $Call.ByID(3445961939, filePath);
}

/**
 * PatchChangeset edits a change-set's name/description.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @param {$models.UpdateChangesetArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function PatchChangeset(workspaceSlug, changesetID, req) {
    return $Call.ByID(2394300770, workspaceSlug, changesetID, req);
}

/**
 * PluginDir returns the configured plugin directory path.
 * @returns {$CancellablePromise<string>}
 */
export function PluginDir() {
    return $Call.ByID(426528074);
}

/**
 * PromoteRule hardens a candidate rule into an enforced check on the profile.
 * @param {string} workspaceSlug
 * @param {string} profileID
 * @param {$models.CandidateRuleArgs} rule
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function PromoteRule(workspaceSlug, profileID, rule) {
    return $Call.ByID(2248580658, workspaceSlug, profileID, rule);
}

/**
 * ProxyMultipart is the multipart/form-data companion to ProxyRequest. The
 * string-only ProxyRequest cannot carry file uploads, so surfaces that POST a
 * FormData (brand-scan sources, collection uploads) route here instead: the
 * frontend serializes the form into proxyMultipartPayload (files base64-encoded)
 * and this rebuilds a genuine multipart body, forwarding it to the connected
 * server with the keychain Bearer token. Same connection/auth contract and raw
 * status+body result as ProxyRequest.
 * @param {string} method
 * @param {string} path
 * @param {string} payloadJSON
 * @returns {$CancellablePromise<$models.ProxyResponse>}
 */
export function ProxyMultipart(method, path, payloadJSON) {
    return $Call.ByID(227792476, method, path, payloadJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType74($result);
    }));
}

/**
 * ProxyRequest forwards an arbitrary REST call (method + path, e.g.
 * "/api/v1/acme/projects") to the connected bowrain server with the keychain
 * Bearer token, returning the raw HTTP status and body. body is the request
 * payload (a JSON string, or "" for none). A non-2xx status is returned in
 * ProxyResponse.Status, not as an error; err is non-nil only for a missing
 * connection/token or a transport failure.
 * @param {string} method
 * @param {string} path
 * @param {string} body
 * @returns {$CancellablePromise<$models.ProxyResponse>}
 */
export function ProxyRequest(method, path, body) {
    return $Call.ByID(1673185545, method, path, body).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType74($result);
    }));
}

/**
 * PseudoTranslateItem pseudo-translates all blocks in an item. When connected
 * the action runs on the server (source of truth) and the local cache is
 * refreshed from the result; on failure or offline it runs locally against the
 * cache and queues the action for replay on reconnect.
 * @param {string} projectID
 * @param {string} itemName
 * @param {string} targetLocale
 * @returns {$CancellablePromise<$models.TranslationStats | null>}
 */
export function PseudoTranslateItem(projectID, itemName, targetLocale) {
    return $Call.ByID(274883483, projectID, itemName, targetLocale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType73($result);
    }));
}

/**
 * PublishContent publishes content from the store to a connector.
 * @param {string} connectorID
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function PublishContent(connectorID, projectID) {
    return $Call.ByID(2672799444, connectorID, projectID);
}

/**
 * QueryItemBlocks pages an item's blocks through the same filters the server
 * applies: server-side when connected, from the local store offline.
 * @param {string} projectID
 * @param {string} itemName
 * @param {$models.EditorBlockFilter} filter
 * @returns {$CancellablePromise<$models.BlockInfo[]>}
 */
export function QueryItemBlocks(projectID, itemName, filter) {
    return $Call.ByID(3683844541, projectID, itemName, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * RefreshChangesetBlastRadius walks a change-set's blast radius now, ignoring
 * any stored summary. Nothing is persisted.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function RefreshChangesetBlastRadius(workspaceSlug, changesetID) {
    return $Call.ByID(1025935295, workspaceSlug, changesetID);
}

/**
 * RejectChangeset records a rejecting review verdict.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @param {$models.ReviewArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function RejectChangeset(workspaceSlug, changesetID, req) {
    return $Call.ByID(2686951285, workspaceSlug, changesetID, req);
}

/**
 * RejectRule rejects a candidate rule so it stops re-surfacing.
 * @param {string} workspaceSlug
 * @param {string} profileID
 * @param {$models.CandidateRuleArgs} rule
 * @returns {$CancellablePromise<void>}
 */
export function RejectRule(workspaceSlug, profileID, rule) {
    return $Call.ByID(2322256213, workspaceSlug, profileID, rule);
}

/**
 * RemoveChangesetOp removes the op with the given seq from a draft change-set.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @param {number} seq
 * @returns {$CancellablePromise<void>}
 */
export function RemoveChangesetOp(workspaceSlug, changesetID, seq) {
    return $Call.ByID(1442658831, workspaceSlug, changesetID, seq);
}

/**
 * RemoveConnector removes an active connector.
 * @param {string} connectorID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveConnector(connectorID) {
    return $Call.ByID(616177915, connectorID);
}

/**
 * RemoveItem removes an item from the project. When connected the removal is
 * sent to the server (source of truth) with the local cache updated to match;
 * on failure or offline it updates the cache and queues the removal for replay.
 * @param {string} projectID
 * @param {string} itemName
 * @returns {$CancellablePromise<$models.ProjectInfo | null>}
 */
export function RemoveItem(projectID, itemName) {
    return $Call.ByID(2559376511, projectID, itemName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RemoveMember removes a member from a workspace.
 * @param {string} workspaceSlug
 * @param {string} userID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveMember(workspaceSlug, userID) {
    return $Call.ByID(4174191426, workspaceSlug, userID);
}

/**
 * RemovePilot unbinds a change-set from a project's content stream.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @param {string} projectID
 * @param {string} stream
 * @returns {$CancellablePromise<void>}
 */
export function RemovePilot(workspaceSlug, changesetID, projectID, stream) {
    return $Call.ByID(1881482814, workspaceSlug, changesetID, projectID, stream);
}

/**
 * RenderBlockHTML returns the rendered HTML for a single block.
 * If targetLocale is non-empty and a translation exists, it returns the
 * target text; otherwise it returns the source HTML.
 * @param {string} projectID
 * @param {string} itemName
 * @param {string} blockID
 * @param {string} targetLocale
 * @returns {$CancellablePromise<string>}
 */
export function RenderBlockHTML(projectID, itemName, blockID, targetLocale) {
    return $Call.ByID(3166545228, projectID, itemName, blockID, targetLocale);
}

/**
 * RenderDocumentPreview returns pre-rendered HTML for an item.
 * Uses stored PreviewHTML if available, falling back to generating
 * a preview from the stored BlockIndex.
 * @param {string} projectID
 * @param {string} itemName
 * @param {string} targetLocale
 * @returns {$CancellablePromise<string>}
 */
export function RenderDocumentPreview(projectID, itemName, targetLocale) {
    return $Call.ByID(2234199739, projectID, itemName, targetLocale);
}

/**
 * ResolveConceptComment marks a comment resolved (or re-opens it).
 * @param {string} workspaceSlug
 * @param {string} conceptID
 * @param {string} commentID
 * @param {boolean} resolved
 * @returns {$CancellablePromise<void>}
 */
export function ResolveConceptComment(workspaceSlug, conceptID, commentID, resolved) {
    return $Call.ByID(3898256013, workspaceSlug, conceptID, commentID, resolved);
}

/**
 * ReviewBlock marks a block as reviewed, signed off or un-reviewed for a
 * target locale. status picks the rung: with reviewed=true it is "" for an
 * approval or "signed-off" for a sign-off; with reviewed=false it is "" or
 * "translated" for a plain un-review, "draft" for a reviewer rejection (the
 * unit re-enters the work queue).
 * @param {string} projectID
 * @param {string} itemName
 * @param {string} blockID
 * @param {string} targetLocale
 * @param {boolean} reviewed
 * @param {string} status
 * @returns {$CancellablePromise<void>}
 */
export function ReviewBlock(projectID, itemName, blockID, targetLocale, reviewed, status) {
    return $Call.ByID(1353546789, projectID, itemName, blockID, targetLocale, reviewed, status);
}

/**
 * SaveFlowDefinition creates or updates a project flow definition on the server.
 * Built-in flows are immutable; the server rejects writes to them.
 * @param {string} projectID
 * @param {$models.FlowDefinitionInfo} info
 * @returns {$CancellablePromise<$models.FlowDefinitionInfo | null>}
 */
export function SaveFlowDefinition(projectID, info) {
    return $Call.ByID(1456548112, projectID, info).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * SaveProviderConfig creates or updates a provider configuration on the server.
 * @param {$models.SaveProviderRequest} req
 * @returns {$CancellablePromise<$models.ProviderConfigInfo | null>}
 */
export function SaveProviderConfig(req) {
    return $Call.ByID(832952266, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType75($result);
    }));
}

/**
 * SelectWorkspace sets the active workspace for all subsequent operations.
 * @param {string} slug
 * @returns {$CancellablePromise<void>}
 */
export function SelectWorkspace(slug) {
    return $Call.ByID(2510784253, slug);
}

/**
 * SetApplication stores the Wails v3 application reference for dialog and event access.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(app) {
    return $Call.ByID(1103546806, app);
}

/**
 * StartLogin begins an authorization code + PKCE flow against the server.
 * It starts a local HTTP server to receive the callback, generates PKCE
 * parameters, and opens the system browser to the server's desktop login
 * endpoint. The frontend should call WaitForLogin to block until the
 * callback is received.
 * @param {string} serverURL
 * @returns {$CancellablePromise<void>}
 */
export function StartLogin(serverURL) {
    return $Call.ByID(1565988937, serverURL);
}

/**
 * StartWatching opens a change-event subscription for the given project.
 * Call StopWatching to close the stream when navigating away.
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function StartWatching(projectID) {
    return $Call.ByID(378219921, projectID);
}

/**
 * StopWatching closes the active project watcher.
 * @returns {$CancellablePromise<void>}
 */
export function StopWatching() {
    return $Call.ByID(2958338237);
}

/**
 * StoreProject creates a project in the content store.
 * @param {string} name
 * @param {string} sourceLocale
 * @param {string[]} targetLocales
 * @returns {$CancellablePromise<store$0.Project | null>}
 */
export function StoreProject(name, sourceLocale, targetLocales) {
    return $Call.ByID(1885409090, name, sourceLocale, targetLocales).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType61($result);
    }));
}

/**
 * SubmitChangeset moves a draft change-set into review.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function SubmitChangeset(workspaceSlug, changesetID) {
    return $Call.ByID(378276088, workspaceSlug, changesetID);
}

/**
 * TermEnforceItem runs terminology enforcement on a project item. When
 * connected the check is owned by the server (which runs the framework
 * term-enforce tool over the authoritative content); when offline it runs the
 * same framework tool against the local cache. It is a read-only check, so
 * there is nothing to queue for replay.
 * @param {string} projectID
 * @param {string} itemName
 * @param {string} targetLocale
 * @returns {$CancellablePromise<$models.TermEnforceResult[]>}
 */
export function TermEnforceItem(projectID, itemName, targetLocale) {
    return $Call.ByID(88031319, projectID, itemName, targetLocale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType77($result);
    }));
}

/**
 * TestProviderConfig tests a provider configuration via the server.
 * @param {$models.SaveProviderRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function TestProviderConfig(req) {
    return $Call.ByID(3045289771, req);
}

/**
 * TrialFindings returns the findings diff for one stream: what the check
 * matchers raise under the live graph and under the graph the draft would
 * produce.
 * @param {string} workspaceSlug
 * @param {string} changesetID
 * @param {string} projectID
 * @param {string} stream
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function TrialFindings(workspaceSlug, changesetID, projectID, stream) {
    return $Call.ByID(4053230998, workspaceSlug, changesetID, projectID, stream);
}

/**
 * TryAutoConnect attempts to reconnect using stored auth on startup.
 * @returns {$CancellablePromise<void>}
 */
export function TryAutoConnect() {
    return $Call.ByID(1058981368);
}

/**
 * UpdateBlockTarget updates the target text for a specific block. The local
 * cache is authoritative for block edits, so a successful server write is still
 * reconciled into the cache; an offline or failed write queues the op and
 * updates the cache alone.
 * @param {$models.UpdateBlockRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function UpdateBlockTarget(req) {
    return $Call.ByID(3768121167, req);
}

/**
 * UpdateBlockTargetRuns updates the target for a block using a
 * structured Run sequence.
 * @param {$models.UpdateBlockTargetRunsRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function UpdateBlockTargetRuns(req) {
    return $Call.ByID(3903261825, req);
}

/**
 * UpdateConcept updates an existing concept in the terms store. The server is
 * authoritative for the terms store, so a successful online update skips the local
 * mirror; the local write runs only offline (queued for replay) or in pure
 * local mode.
 * @param {$models.UpdateConceptRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConcept(req) {
    return $Call.ByID(3374190367, req);
}

/**
 * UpdateMarket updates an existing market scope.
 * @param {string} workspaceSlug
 * @param {string} marketID
 * @param {$models.MarketArgs} req
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function UpdateMarket(workspaceSlug, marketID, req) {
    return $Call.ByID(2036367517, workspaceSlug, marketID, req);
}

/**
 * UpdateMemberRole changes a member's role.
 * @param {string} workspaceSlug
 * @param {string} userID
 * @param {string} role
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMemberRole(workspaceSlug, userID, role) {
    return $Call.ByID(3262478483, workspaceSlug, userID, role);
}

/**
 * UpdateMemoryEntry updates an existing content-memory entry. The server is authoritative for
 * the content memory, so a successful online update skips the local mirror; the local write
 * runs only offline (queued for replay) or in pure local mode.
 * @param {$models.MemoryUpdateRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMemoryEntry(req) {
    return $Call.ByID(2763311530, req);
}

/**
 * UpdatePresence reports the user's current editing focus to the server, which
 * fans it out to other watchers over the SSE relay. Best-effort — a failure is
 * logged and swallowed (per-cursor presence is carried over Yjs awareness).
 * @param {string} projectID
 * @param {string} itemName
 * @param {string} blockID
 * @returns {$CancellablePromise<void>}
 */
export function UpdatePresence(projectID, itemName, blockID) {
    return $Call.ByID(3401740472, projectID, itemName, blockID);
}

/**
 * WaitForLogin blocks until the PKCE callback is received or a timeout occurs.
 * Returns true when authentication succeeds.
 * @returns {$CancellablePromise<boolean>}
 */
export function WaitForLogin() {
    return $Call.ByID(3244055841);
}

// Private type creation functions
const $$createType0 = $models.ConceptInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ProjectInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.MemoryEntryInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.BulkApplyMemoryView.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.BulkReviewView.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.ConnectorInfo.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.InviteInfo.createFrom;
const $$createType13 = store$0.Version.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $models.ContentItemInfo.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.BlockInfo.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $models.BlockCountsView.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $models.CollabSession.createFrom;
const $$createType22 = $models.ConnectionInfo.createFrom;
const $$createType23 = $models.SyncStatusInfo.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $models.WorkspaceInfo.createFrom;
const $$createType26 = $models.FlowDefinitionInfo.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = $models.ItemView.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = $Create.Array($$createType17);
const $$createType31 = locale$0.LocaleInfo.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $models.MemorySearchResult.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = $models.PendingReviewPageView.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = $Create.Array($$createType25);
const $$createType38 = $models.TermSearchResult.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = $Create.Map($Create.Any, $Create.Any);
const $$createType41 = $models.VersionInfo.createFrom;
const $$createType42 = $models.VoiceRollupResult.createFrom;
const $$createType43 = $models.WordCountResult.createFrom;
const $$createType44 = $Create.Nullable($$createType43);
const $$createType45 = $Create.Array($Create.Any);
const $$createType46 = $Create.Array($$createType10);
const $$createType47 = $Create.Array($$createType26);
const $$createType48 = $models.FormatInfo.createFrom;
const $$createType49 = $Create.Array($$createType48);
const $$createType50 = $Create.Array($$createType12);
const $$createType51 = $models.MemberInfo.createFrom;
const $$createType52 = $Create.Array($$createType51);
const $$createType53 = $models.PluginInfo.createFrom;
const $$createType54 = $Create.Array($$createType53);
const $$createType55 = $models.ProjectItem.createFrom;
const $$createType56 = $Create.Array($$createType55);
const $$createType57 = $Create.Array($$createType2);
const $$createType58 = $models.ProviderConfigInfo.createFrom;
const $$createType59 = $Create.Array($$createType58);
const $$createType60 = store$0.Project.createFrom;
const $$createType61 = $Create.Nullable($$createType60);
const $$createType62 = $Create.Array($$createType61);
const $$createType63 = $Create.Array($$createType14);
const $$createType64 = $models.ToolInfo.createFrom;
const $$createType65 = $Create.Array($$createType64);
const $$createType66 = $models.MemoryMatchInfo.createFrom;
const $$createType67 = $Create.Array($$createType66);
const $$createType68 = $models.TermLookupResult.createFrom;
const $$createType69 = $Create.Nullable($$createType68);
const $$createType70 = $models.BlockTermMatch.createFrom;
const $$createType71 = $Create.Array($$createType70);
const $$createType72 = $models.TranslationStats.createFrom;
const $$createType73 = $Create.Nullable($$createType72);
const $$createType74 = $models.ProxyResponse.createFrom;
const $$createType75 = $Create.Nullable($$createType58);
const $$createType76 = $models.TermEnforceResult.createFrom;
const $$createType77 = $Create.Array($$createType76);
