import { useState, useEffect, useCallback, useMemo } from "react";
import type {
  FormatInfo,
  ToolInfo,
  ToolSchema,
  FlowInfo,
  FlowDefinitionInfo,
  PluginInfo,
  VersionInfo,
  ProjectInfo,
  BlockInfo,
  UpdateBlockRequest,
  UpdateBlockTargetRunsRequest,
  TranslationStats,
  WordCountResult,
  ProviderConfig,
  ProviderConfigWithKey,
  TMSearchResult,
  TMUpdateRequest,
  TMEntryInfo,
  TMMatchInfo,
  BlockTermMatch,
  TermSearchResult,
  ConceptInfo,
  AddConceptRequest,
  UpdateConceptRequest,
  TermLookupResult,
  TermEnforceResult,
} from "../types/api";

// Wails v3 bindings – ES module imports generated by `wails3 generate bindings`.
import { Backend } from "../api/backend";
import { optionalBinding } from "../api/optionalBinding";

export function useFormats() {
  const [formats, setFormats] = useState<FormatInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Backend.ListFormats()
      .then((r: FormatInfo[]) => setFormats(r))
      .catch((e: Error) => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  return { formats, loading, error };
}

export function useTools() {
  const [tools, setTools] = useState<ToolInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Backend.ListTools()
      .then((r: ToolInfo[]) => setTools(r))
      .catch((e: Error) => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  return { tools, loading, error };
}

export function useFlows(projectId = "") {
  const [flows, setFlows] = useState<FlowInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Backend.ListFlowDefinitions(projectId)
      .then((r: FlowDefinitionInfo[]) =>
        setFlows((r || []).map((d) => ({ name: d.name, description: d.description || "" }))),
      )
      .catch((e: Error) => setError(e.message))
      .finally(() => setLoading(false));
  }, [projectId]);

  return { flows, loading, error };
}

export function usePlugins() {
  const [plugins, setPlugins] = useState<PluginInfo[]>([]);
  const [pluginDir, setPluginDir] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([Backend.ListPlugins(), Backend.PluginDir()])
      .then(([pl, dir]: [PluginInfo[], string]) => {
        setPlugins(pl);
        setPluginDir(dir);
      })
      .catch((e: Error) => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  return { plugins, pluginDir, loading, error };
}

export function useVersion() {
  const [version, setVersion] = useState<VersionInfo | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Backend.GetVersion()
      .then((r: VersionInfo) => setVersion(r))
      .catch((e: Error) => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  return { version, loading, error };
}

export function useHealth() {
  // Wails v3 bindings are always available as ES module imports.
  const connected = true;
  const refresh = useCallback(() => {}, []);
  return { connected, refresh };
}

// Connection state types
export interface ConnectionInfo {
  state: "disconnected" | "connecting" | "connected" | "offline";
  server_url?: string;
  user_name?: string;
  user_email?: string;
  workspace?: string;
}

export function useConnection() {
  const [info, setInfo] = useState<ConnectionInfo>({ state: "disconnected" });

  const refresh = useCallback(async () => {
    const ci = (await Backend.GetConnectionState()) as ConnectionInfo;
    setInfo(ci);
    return ci;
  }, []);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  const connect = useCallback(
    async (serverURL: string) => {
      await Backend.ConnectToServer(serverURL);
      return refresh();
    },
    [refresh],
  );

  const startLogin = useCallback(async (serverURL: string): Promise<void> => {
    await Backend.StartLogin(serverURL);
  }, []);

  const waitForLogin = useCallback(async (): Promise<boolean> => {
    return Backend.WaitForLogin() as Promise<boolean>;
  }, []);

  const cancelLogin = useCallback(async () => {
    await Backend.CancelLogin();
  }, []);

  const logout = useCallback(async () => {
    await Backend.Logout();
    setInfo({ state: "disconnected" });
  }, []);

  const disconnect = useCallback(async () => {
    await Backend.Disconnect();
    setInfo({ state: "disconnected" });
  }, []);

  const selectWorkspace = useCallback(
    async (slug: string) => {
      await Backend.SelectWorkspace(slug);
      return refresh();
    },
    [refresh],
  );

  const getServerWorkspaces = useCallback(async () => {
    return Backend.GetServerWorkspaces() as Promise<
      Array<{
        id: string;
        slug: string;
        name: string;
        description: string;
        role: string;
      }>
    >;
  }, []);

  const startWatching = useCallback(async (projectID: string) => {
    await Backend.StartWatching(projectID);
  }, []);

  const stopWatching = useCallback(async () => {
    await Backend.StopWatching();
  }, []);

  const updatePresence = useCallback(
    async (projectID: string, itemName: string, blockID: string) => {
      await Backend.UpdatePresence(projectID, itemName, blockID);
    },
    [],
  );

  const reviewBlock = useCallback(
    async (
      projectID: string,
      itemName: string,
      blockID: string,
      targetLocale: string,
      reviewed: boolean,
    ): Promise<void> => {
      return Backend.ReviewBlock(projectID, itemName, blockID, targetLocale, reviewed);
    },
    [],
  );

  const getPendingChangesCount = useCallback(async (): Promise<number> => {
    return Backend.GetPendingChangesCount() as Promise<number>;
  }, []);

  return {
    info,
    refresh,
    connect,
    startLogin,
    waitForLogin,
    cancelLogin,
    logout,
    disconnect,
    selectWorkspace,
    getServerWorkspaces,
    startWatching,
    stopWatching,
    updatePresence,
    reviewBlock,
    getPendingChangesCount,
  };
}

// Project API hooks

export function useProjectApi() {
  const createProject = useCallback(
    async (name: string, sourceLang: string, targetLangs: string[]): Promise<ProjectInfo> => {
      return Backend.CreateProject(name, sourceLang, targetLangs) as Promise<ProjectInfo>;
    },
    [],
  );

  const listProjects = useCallback(async (): Promise<ProjectInfo[]> => {
    return Backend.ListProjects() as Promise<ProjectInfo[]>;
  }, []);

  const closeProject = useCallback(async (projectID: string): Promise<void> => {
    return Backend.CloseProject(projectID);
  }, []);

  const addFiles = useCallback(
    async (projectID: string, filePaths: string[]): Promise<ProjectInfo> => {
      return Backend.AddItems(projectID, filePaths) as Promise<ProjectInfo>;
    },
    [],
  );

  const removeFile = useCallback(
    async (projectID: string, fileName: string): Promise<ProjectInfo> => {
      return Backend.RemoveItem(projectID, fileName) as Promise<ProjectInfo>;
    },
    [],
  );

  return {
    createProject,
    listProjects,
    closeProject,
    addFiles,
    removeFile,
  };
}

export function useEditorApi() {
  const getFileBlocks = useCallback(
    async (projectID: string, fileName: string): Promise<BlockInfo[]> => {
      return Backend.GetItemBlocks(projectID, fileName) as Promise<BlockInfo[]>;
    },
    [],
  );

  const updateBlockTarget = useCallback(async (req: UpdateBlockRequest): Promise<void> => {
    return Backend.UpdateBlockTarget(req);
  }, []);

  const updateBlockTargetRuns = useCallback(
    async (req: UpdateBlockTargetRunsRequest): Promise<void> => {
      return Backend.UpdateBlockTargetRuns(req);
    },
    [],
  );

  const pseudoTranslateFile = useCallback(
    async (
      projectID: string,
      fileName: string,
      targetLocale: string,
    ): Promise<TranslationStats> => {
      return Backend.PseudoTranslateItem(
        projectID,
        fileName,
        targetLocale,
      ) as Promise<TranslationStats>;
    },
    [],
  );

  const tmTranslateFile = useCallback(
    async (
      projectID: string,
      fileName: string,
      targetLocale: string,
    ): Promise<TranslationStats> => {
      return Backend.TMTranslateItem(
        projectID,
        fileName,
        targetLocale,
      ) as Promise<TranslationStats>;
    },
    [],
  );

  const getWordCount = useCallback(
    async (projectID: string, fileName: string): Promise<WordCountResult> => {
      return Backend.GetWordCount(projectID, fileName) as Promise<WordCountResult>;
    },
    [],
  );

  const exportTranslatedFile = useCallback(
    async (projectID: string, fileName: string, targetLocale: string): Promise<string> => {
      return Backend.ExportTranslatedItem(projectID, fileName, targetLocale);
    },
    [],
  );

  const openFileInOS = useCallback(async (filePath: string): Promise<void> => {
    return Backend.OpenFileInOS(filePath);
  }, []);

  const renderDocumentPreview = useCallback(
    async (projectID: string, itemName: string, targetLocale: string): Promise<string> => {
      return Backend.RenderDocumentPreview(projectID, itemName, targetLocale);
    },
    [],
  );

  const renderBlockHTML = useCallback(
    async (
      projectID: string,
      itemName: string,
      blockID: string,
      targetLocale: string,
    ): Promise<string> => {
      return Backend.RenderBlockHTML(projectID, itemName, blockID, targetLocale);
    },
    [],
  );

  const lookupTMForBlock = useCallback(
    async (
      projectID: string,
      itemName: string,
      blockID: string,
      targetLocale: string,
    ): Promise<TMMatchInfo[]> => {
      return Backend.LookupTMForBlock(projectID, itemName, blockID, targetLocale) as Promise<
        TMMatchInfo[]
      >;
    },
    [],
  );

  const lookupTermsForBlock = useCallback(
    async (
      projectID: string,
      itemName: string,
      blockID: string,
      targetLocale: string,
    ): Promise<BlockTermMatch[]> => {
      return Backend.LookupTermsForBlock(projectID, itemName, blockID, targetLocale) as Promise<
        BlockTermMatch[]
      >;
    },
    [],
  );

  return useMemo(
    () => ({
      getFileBlocks,
      updateBlockTarget,
      updateBlockTargetRuns,
      pseudoTranslateFile,
      tmTranslateFile,
      getWordCount,
      exportTranslatedFile,
      openFileInOS,
      renderDocumentPreview,
      renderBlockHTML,
      lookupTMForBlock,
      lookupTermsForBlock,
    }),
    [
      getFileBlocks,
      updateBlockTarget,
      updateBlockTargetRuns,
      pseudoTranslateFile,
      tmTranslateFile,
      getWordCount,
      exportTranslatedFile,
      openFileInOS,
      renderDocumentPreview,
      renderBlockHTML,
      lookupTMForBlock,
      lookupTermsForBlock,
    ],
  );
}

// Provider config hooks

export function useProviderConfigs() {
  const [configs, setConfigs] = useState<ProviderConfig[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const refresh = useCallback(() => {
    setLoading(true);
    Backend.ListProviderConfigs()
      .then((c: ProviderConfig[]) => setConfigs(c || []))
      .catch((e: Error) => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  return { configs, loading, error, refresh };
}

// TM API hooks

export function useTMApi() {
  const getTMEntries = useCallback(
    async (
      projectID: string,
      query: string,
      sourceLocale: string,
      targetLocale: string,
      offset: number,
      limit: number,
    ): Promise<TMSearchResult> => {
      return Backend.GetTMEntries(
        projectID,
        query,
        sourceLocale,
        targetLocale,
        offset,
        limit,
      ) as Promise<TMSearchResult>;
    },
    [],
  );

  const getTMCount = useCallback(async (projectID: string): Promise<number> => {
    return Backend.GetTMCount(projectID) as Promise<number>;
  }, []);

  const updateTMEntry = useCallback(async (req: TMUpdateRequest): Promise<void> => {
    return Backend.UpdateTMEntry(req);
  }, []);

  const deleteTMEntry = useCallback(async (projectID: string, entryID: string): Promise<void> => {
    return Backend.DeleteTMEntry(projectID, entryID);
  }, []);

  const addTMEntry = useCallback(
    async (
      projectID: string,
      source: string,
      target: string,
      sourceLocale: string,
      targetLocale: string,
    ): Promise<TMEntryInfo> => {
      return Backend.AddTMEntry(
        projectID,
        source,
        target,
        sourceLocale,
        targetLocale,
      ) as Promise<TMEntryInfo>;
    },
    [],
  );

  return { getTMEntries, getTMCount, updateTMEntry, deleteTMEntry, addTMEntry };
}

// Provider config hooks

export function useProviderApi() {
  const saveProviderConfig = useCallback(
    async (cfg: ProviderConfigWithKey): Promise<ProviderConfig> => {
      return Backend.SaveProviderConfig(cfg) as Promise<ProviderConfig>;
    },
    [],
  );

  const deleteProviderConfig = useCallback(async (id: string): Promise<void> => {
    return Backend.DeleteProviderConfig(id);
  }, []);

  const testProviderConfig = useCallback(async (cfg: ProviderConfigWithKey): Promise<void> => {
    return Backend.TestProviderConfig(cfg);
  }, []);

  return { saveProviderConfig, deleteProviderConfig, testProviderConfig };
}

// Terms API hooks

export function useTermsApi() {
  const getTerms = useCallback(
    async (
      projectID: string,
      query: string,
      sourceLocale: string,
      targetLocale: string,
      offset: number,
      limit: number,
    ): Promise<TermSearchResult> => {
      return Backend.GetTerms(
        projectID,
        query,
        sourceLocale,
        targetLocale,
        offset,
        limit,
      ) as Promise<TermSearchResult>;
    },
    [],
  );

  const getTermCount = useCallback(async (projectID: string): Promise<number> => {
    return Backend.GetTermCount(projectID) as Promise<number>;
  }, []);

  const addConcept = useCallback(async (req: AddConceptRequest): Promise<ConceptInfo> => {
    return Backend.AddConcept(req) as Promise<ConceptInfo>;
  }, []);

  const updateConcept = useCallback(async (req: UpdateConceptRequest): Promise<void> => {
    return Backend.UpdateConcept(req);
  }, []);

  const deleteConcept = useCallback(async (projectID: string, conceptID: string): Promise<void> => {
    return Backend.DeleteConcept(projectID, conceptID);
  }, []);

  const lookupTerms = useCallback(
    async (
      projectID: string,
      text: string,
      sourceLocale: string,
      targetLocale: string,
    ): Promise<TermLookupResult> => {
      return Backend.LookupTerms(
        projectID,
        text,
        sourceLocale,
        targetLocale,
      ) as Promise<TermLookupResult>;
    },
    [],
  );

  const importTermsCSV = useCallback(
    async (
      projectID: string,
      csvContent: string,
      sourceLocale: string,
      targetLocale: string,
      domain: string,
      hasHeader: boolean,
    ): Promise<number> => {
      return Backend.ImportTermsCSV(
        projectID,
        csvContent,
        sourceLocale,
        targetLocale,
        domain,
        hasHeader,
      ) as Promise<number>;
    },
    [],
  );

  const importTermsJSON = useCallback(
    async (projectID: string, jsonContent: string): Promise<number> => {
      return Backend.ImportTermsJSON(projectID, jsonContent) as Promise<number>;
    },
    [],
  );

  const exportTermsJSON = useCallback(async (projectID: string, name: string): Promise<string> => {
    return Backend.ExportTermsJSON(projectID, name) as Promise<string>;
  }, []);

  const termEnforceItem = useCallback(
    async (
      projectID: string,
      itemName: string,
      targetLocale: string,
    ): Promise<TermEnforceResult[]> => {
      return Backend.TermEnforceItem(projectID, itemName, targetLocale) as Promise<
        TermEnforceResult[]
      >;
    },
    [],
  );

  return {
    getTerms,
    getTermCount,
    addConcept,
    updateConcept,
    deleteConcept,
    lookupTerms,
    importTermsCSV,
    importTermsJSON,
    exportTermsJSON,
    termEnforceItem,
  };
}

// Tool schema hook

export function useToolSchema(toolName: string | null) {
  const [schema, setSchema] = useState<ToolSchema | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!toolName) {
      setSchema(null);
      return;
    }
    setLoading(true);
    setError(null);

    // Try to call the backend method; gracefully handle if not available
    const fn = optionalBinding<(name: string) => Promise<ToolSchema | null>>(
      Backend,
      "GetToolSchema",
    );
    if (fn) {
      fn(toolName)
        .then((s) => setSchema(s))
        .catch((e: Error) => setError(e.message))
        .finally(() => setLoading(false));
    } else {
      // Backend doesn't have GetToolSchema yet
      setSchema(null);
      setLoading(false);
    }
  }, [toolName]);

  return { schema, loading, error };
}

// Flow definition hooks

export function useFlowDefinitions(projectId: string) {
  const [definitions, setDefinitions] = useState<FlowDefinitionInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const refresh = useCallback(() => {
    setLoading(true);
    Backend.ListFlowDefinitions(projectId)
      .then((r: FlowDefinitionInfo[]) => setDefinitions(r || []))
      .catch((e: Error) => setError(e.message))
      .finally(() => setLoading(false));
  }, [projectId]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  return { definitions, loading, error, refresh };
}

export function useFlowDefinitionApi(projectId: string) {
  const getFlowDefinition = useCallback(
    async (id: string): Promise<FlowDefinitionInfo> => {
      return Backend.GetFlowDefinition(projectId, id) as Promise<FlowDefinitionInfo>;
    },
    [projectId],
  );

  const saveFlowDefinition = useCallback(
    async (def: FlowDefinitionInfo): Promise<FlowDefinitionInfo> => {
      return Backend.SaveFlowDefinition(projectId, def) as Promise<FlowDefinitionInfo>;
    },
    [projectId],
  );

  const deleteFlowDefinition = useCallback(
    async (id: string): Promise<void> => {
      return Backend.DeleteFlowDefinition(projectId, id);
    },
    [projectId],
  );

  return { getFlowDefinition, saveFlowDefinition, deleteFlowDefinition };
}
