//go:build integration

package po_test

// Code generated by gen-test-stubs from Surefire XML. DO NOT EDIT.
// To implement a test, move it to the appropriate test file and
// replace t.Skip("pending") with test logic.

import "testing"

// ---- POFilterTest (32 tests) ----

// okapi: POFilterTest#testDefaultInfo
func TestRead_DefaultInfo(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testDoubleExtraction
func TestRoundTrip_DoubleExtraction(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testHeaderNoNPlurals
func TestRead_HeaderNoNPlurals(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testHeaderWithEmptyEntryAfter
func TestRead_HeaderWithEmptyEntryAfter(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testHtmlSubfilterBilingualMode
func TestRead_HtmlSubfilterBilingualMode(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testInlines
func TestRead_Inlines(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testMarkdownSubfilter
func TestRead_MarkdownSubfilter(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testMsgCtxtAsNotes
func TestRead_MsgCtxtAsNotes(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testOnePlural
func TestRead_OnePlural(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testOuputAddTranslation
func TestRead_OuputAddTranslation(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testOuputNoQuoteOnSameLine
func TestRead_OuputNoQuoteOnSameLine(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testOuputOptionLine_FuzyFormat
func TestRead_OuputOptionLineFuzyFormat(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testOuputOptionLine_JustFormatWithMacLB
func TestRead_OuputOptionLineJustFormatWithMacLB(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testOuputOptionLine_StuffFuzyFormat
func TestRead_OuputOptionLineStuffFuzyFormat(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testOuputPluralEntryFuzzy
func TestRead_OuputPluralEntryFuzzy(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testOuputWithAllowedEmpty
func TestRead_OuputWithAllowedEmpty(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testOutputProtectApproved
func TestRead_OutputProtectApproved(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testPOTHeader
func TestRead_POTHeader(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testPluralEntryFuzzy
func TestRead_PluralEntryFuzzy(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testPluralFormAccess
func TestRead_PluralFormAccess(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testPluralFormDefaults
func TestRead_PluralFormDefaults(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testProtectApproved
func TestRead_ProtectApproved(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testStartDocument
func TestRead_StartDocument(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testTUCompleteEntry
func TestRead_TUCompleteEntry(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testTUContextParsing
func TestRead_TUContextParsing(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testTUEmptyIDEntry
func TestRead_TUEmptyIDEntry(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testTUPluralEntry_DefaultPlural
func TestRead_TUPluralEntryDefaultPlural(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testTUPluralEntry_DefaultSingular
func TestRead_TUPluralEntryDefaultSingular(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testThreePlurals
func TestRead_ThreePlurals(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testTrailingSkeleton
func TestRead_TrailingSkeleton(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testWithLetterCodes
func TestRead_WithLetterCodes(t *testing.T) {
	t.Skip("pending")
}

// okapi: POFilterTest#testWithNoCodesLookingLikeCodes
func TestRead_WithNoCodesLookingLikeCodes(t *testing.T) {
	t.Skip("pending")
}

// ---- POWriterTest (8 tests) ----

// okapi: POWriterTest#testEscapes
func TestWrite_Escapes(t *testing.T) {
	t.Skip("pending")
}

// okapi: POWriterTest#testEscapesAmongAlreadyEscaped
func TestWrite_EscapesAmongAlreadyEscaped(t *testing.T) {
	t.Skip("pending")
}

// okapi: POWriterTest#testOutputWithFuzzy
func TestWrite_OutputWithFuzzy(t *testing.T) {
	t.Skip("pending")
}

// okapi: POWriterTest#testOutputWithFuzzyPlural
func TestWrite_OutputWithFuzzyPlural(t *testing.T) {
	t.Skip("pending")
}

// okapi: POWriterTest#testOutputWithLinesWithWrap
func TestWrite_OutputWithLinesWithWrap(t *testing.T) {
	t.Skip("pending")
}

// okapi: POWriterTest#testOutputWithPlural
func TestWrite_OutputWithPlural(t *testing.T) {
	t.Skip("pending")
}

// okapi: POWriterTest#testSrcSimpleOutput
func TestWrite_SrcSimpleOutput(t *testing.T) {
	t.Skip("pending")
}

// okapi: POWriterTest#testSrcTrgSimpleOutput
func TestWrite_SrcTrgSimpleOutput(t *testing.T) {
	t.Skip("pending")
}
