package main

import (
	"fmt"
	"reflect"
	"strings"

	formatschema "github.com/neokapi/neokapi/core/format/schema"
	"github.com/neokapi/neokapi/core/model"
	"github.com/neokapi/neokapi/core/redaction"
	"github.com/neokapi/neokapi/core/schema"
)

// sideType is the reflect.Type of model.Side, special-cased so its fields emit
// the TS string-literal union `Side` rather than `number` (Side is an int enum
// with text marshaling).
var sideType = reflect.TypeOf(model.Side(0))

// emitType describes one Go struct to render as a TS interface, with an optional
// doc comment.
type emitType struct {
	name string
	typ  reflect.Type
	doc  string
}

// atoms is the ordered set of IO-contract atom types rendered from Go. These map
// 1:1 onto their Go structs; reflecting them keeps the committed TS honest. The
// superset envelopes (ComponentSchema, PropertySchema, ConditionExpr) live in
// manual.ts because the UI extends them beyond what Go models.
var atoms = []emitType{
	{"IOPort", reflect.TypeOf(schema.IOPort{}),
		"One entry of a tool's IO contract: a typed stand-off output the tool\nconsumes (reads upstream) or produces (writes). `type` names an overlay\ntype, a block-annotation key, or a pseudo-port (`target`/`source`)."},
	{"ToolMeta", reflect.TypeOf(schema.ToolMeta{}),
		"Tool identification, classification, and IO contract (consumes/produces)."},
	// ParameterGroup is hand-authored in manual.ts: its ui:visible field is a
	// ConditionExpr (a hand-authored union with no 1:1 Go type), like
	// PropertySchema/ComponentSchema.
	{"LayoutHints", reflect.TypeOf(schema.LayoutHints{}),
		"Field-level layout hints."},
	{"OptionItem", reflect.TypeOf(schema.OptionItem{}),
		"A labeled enum value for select/radio properties."},
	{"FileFilter", reflect.TypeOf(schema.FileFilter{}),
		"A file-type filter for file picker dialogs."},
	{"PathAnnotation", reflect.TypeOf(schema.PathAnnotation{}),
		"Describes a property that references a file path or named resource."},
	{"FormatMeta", reflect.TypeOf(formatschema.FormatMeta{}),
		"Format identification metadata."},
}

// emit renders the full generated TS file as a string.
func emit() (string, error) {
	var b strings.Builder
	b.WriteString("// GENERATED by scripts/gen-contract-types — DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `make generate-contract-types`; the drift gate is\n")
	b.WriteString("// `make check-contract-types` (mirrors check-reference-docs).\n")
	b.WriteString("//\n")
	b.WriteString("// Source of truth: core/schema, core/format/schema, core/model (Go).\n")
	b.WriteString("// These are the IO-contract atoms that map 1:1 onto Go. The superset\n")
	b.WriteString("// envelope types (ComponentSchema, PropertySchema, ConditionExpr) that the\n")
	b.WriteString("// UI extends beyond Go are hand-authored in ./manual.ts.\n\n")

	b.WriteString("/** Which run sequence a stand-off interpretation pertains to. */\n")
	b.WriteString("export type Side = \"source\" | \"target\";\n")

	b.WriteString(emitVocabularies())

	for _, a := range atoms {
		iface, err := renderInterface(a)
		if err != nil {
			return "", fmt.Errorf("render %s: %w", a.name, err)
		}
		b.WriteString("\n")
		b.WriteString(iface)
	}
	return b.String(), nil
}

// emitVocabularies renders the canonical string vocabularies the flow editor
// attaches presentation (colors/icons/labels) to: tool categories and IO port
// types (overlay types, block-annotation keys, pseudo-ports, the redaction
// secret). Each is sourced from the Go constants, so the committed unions track
// the source of truth and the editor's styling maps (keyed `Record<Union, …>`)
// fail to compile when a member lacks styling.
func emitVocabularies() string {
	overlays := []string{
		string(model.OverlaySegmentation), string(model.OverlayTerm),
		string(model.OverlayEntity), string(model.OverlayQA),
		string(model.OverlayAlignment), string(model.OverlayTermCandidate),
	}
	annotations := []string{
		model.AnnoNote, model.AnnoAltTranslation, model.AnnoTMMatch,
		model.AnnoWordCount, model.AnnoCharCount, model.AnnoSegCount,
		model.AnnoComparison, model.AnnoScopingReport, model.AnnoRepetition,
		model.AnnoBrandVoice, model.AnnoEntityMapping, model.AnnoTermEnforce,
	}
	pseudoAndSecurity := []string{schema.PortSource, schema.PortTarget, redaction.SecretAnnotationKey}

	var b strings.Builder
	b.WriteString(emitStringUnion("ToolCategory",
		"The canonical tool category vocabulary (CLI command groups + flow-editor\ngrouping). Source: core/schema Category* constants.",
		[]string{
			schema.CategoryTranslation, schema.CategoryQuality, schema.CategoryAnalysis,
			schema.CategoryTextProcessing, schema.CategoryConvert, schema.CategoryPipeline,
		}, "TOOL_CATEGORIES"))
	b.WriteString(emitStringUnion("OverlayType",
		"Run-anchored stand-off overlay kinds. Source: core/model Overlay* constants.",
		overlays, "OVERLAY_TYPES"))
	b.WriteString(emitStringUnion("AnnotationType",
		"Block-scoped annotation keys. Source: core/model Anno* constants.",
		annotations, "ANNOTATION_TYPES"))
	b.WriteString(emitStringUnion("PortType",
		"Every IO-contract port-type string a tool may consume or produce: an\noverlay type, an annotation key, a pseudo-port (source/target), or the\nredaction secret. The flow editor keys per-type presentation off this.",
		concat(overlays, annotations, pseudoAndSecurity), "PORT_TYPES"))
	return b.String()
}

// emitStringUnion renders `export type Name = "a" | "b";` plus a frozen
// `export const CONST: readonly Name[] = [...]` enumerating the members in order.
func emitStringUnion(name, doc string, values []string, constName string) string {
	var b strings.Builder
	b.WriteString("\n")
	if doc != "" {
		b.WriteString(blockComment(doc))
	}
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = `"` + v + `"`
	}
	fmt.Fprintf(&b, "export type %s = %s;\n", name, strings.Join(quoted, " | "))
	fmt.Fprintf(&b, "export const %s: readonly %s[] = [%s];\n", constName, name, strings.Join(quoted, ", "))
	return b.String()
}

// concat flattens several string slices in order.
func concat(slices ...[]string) []string {
	var out []string
	for _, s := range slices {
		out = append(out, s...)
	}
	return out
}

// renderInterface renders one Go struct as a TS interface.
func renderInterface(e emitType) (string, error) {
	if e.typ.Kind() != reflect.Struct {
		return "", fmt.Errorf("%s is not a struct", e.name)
	}
	var b strings.Builder
	if e.doc != "" {
		b.WriteString(blockComment(e.doc))
	}
	fmt.Fprintf(&b, "export interface %s {\n", e.name)
	for i := 0; i < e.typ.NumField(); i++ {
		f := e.typ.Field(i)
		if !f.IsExported() {
			continue
		}
		name, opts := parseJSONTag(f)
		if name == "-" {
			continue
		}
		if name == "" {
			name = f.Name
		}
		optional := f.Type.Kind() == reflect.Ptr || hasOption(opts, "omitempty")
		ts, err := tsType(f.Type)
		if err != nil {
			return "", fmt.Errorf("field %s: %w", f.Name, err)
		}
		q := ""
		if optional {
			q = "?"
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", tsKey(name), q, ts)
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// tsType maps a Go type to its TS rendering.
func tsType(t reflect.Type) (string, error) {
	if t == sideType {
		return "Side", nil
	}
	switch t.Kind() {
	case reflect.Ptr:
		return tsType(t.Elem())
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.String:
		return "string", nil
	case reflect.Interface:
		return "unknown", nil
	case reflect.Slice, reflect.Array:
		elem, err := tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return elem + "[]", nil
	case reflect.Map:
		val, err := tsType(t.Elem())
		if err != nil {
			return "", err
		}
		return "Record<string, " + val + ">", nil
	case reflect.Struct:
		// Named struct → reference by its (capitalized) Go name, which matches
		// the emitted TS interface name for the atoms.
		if t.Name() == "" {
			return "", fmt.Errorf("anonymous struct fields are unsupported")
		}
		return t.Name(), nil
	default:
		return "", fmt.Errorf("unsupported kind %s", t.Kind())
	}
}

// parseJSONTag returns the JSON field name and the trailing options.
func parseJSONTag(f reflect.StructField) (name string, opts []string) {
	tag := f.Tag.Get("json")
	if tag == "" {
		return f.Name, nil
	}
	parts := strings.Split(tag, ",")
	return parts[0], parts[1:]
}

func hasOption(opts []string, want string) bool {
	for _, o := range opts {
		if o == want {
			return true
		}
	}
	return false
}

// tsKey quotes a property key when it is not a bare identifier (e.g. "$id",
// "ui:groups", "x-path").
func tsKey(name string) string {
	bare := name != "" && !(name[0] >= '0' && name[0] <= '9')
	for _, r := range name {
		if !(r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')) {
			bare = false
			break
		}
	}
	if bare {
		return name
	}
	return `"` + name + `"`
}

// blockComment renders a multi-line JSDoc block.
func blockComment(doc string) string {
	lines := strings.Split(doc, "\n")
	var b strings.Builder
	b.WriteString("/**\n")
	for _, l := range lines {
		if l == "" {
			b.WriteString(" *\n")
		} else {
			fmt.Fprintf(&b, " * %s\n", l)
		}
	}
	b.WriteString(" */\n")
	return b.String()
}
