package main

// schema.go emits core/proto/content/v1/content.schema.json — a JSON Schema
// (draft 2020-12) for the canonical content-model JSON, generated from the
// neokapi.content.v1 proto descriptors for non-proto consumers.
//
// The schema is a documented convenience, not the binding contract: the
// protojson golden files under core/proto/content/v1/testdata (locked by
// json_test.go) are the hard contract. The schema mirrors the canonical
// encoding rules (contentv1.MarshalJSON): lowerCamelCase property names,
// every property optional (unpopulated fields are omitted), bytes as base64
// strings, 64-bit integers as strings, and oneof groups constrained to a
// single member. Unknown properties are allowed — the canonical decoder
// ignores them for forward compatibility — so `additionalProperties` is left
// open.

import (
	"encoding/json"
	"errors"
	"fmt"

	contentv1 "github.com/neokapi/neokapi/core/proto/content/v1"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// emitSchema renders content.schema.json as a string. Output is
// deterministic: encoding/json sorts object keys.
func emitSchema() (string, error) {
	defs := map[string]any{}
	msgs := contentv1.File_core_proto_content_v1_content_proto.Messages()
	for i := range msgs.Len() {
		md := msgs.Get(i)
		s, err := messageSchema(md)
		if err != nil {
			return "", fmt.Errorf("schema for %s: %w", md.Name(), err)
		}
		defs[string(md.Name())] = s
	}

	root := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$id":     "https://neokapi.org/schemas/content/v1/content.schema.json",
		"title":   "neokapi.content.v1 canonical JSON",
		"description": "GENERATED by scripts/gen-contract-types. DO NOT EDIT. " +
			"JSON Schema for the canonical content-model JSON (AD-034): protojson of " +
			"core/proto/content/v1/content.proto with the fixed options in json.go. " +
			"The protojson golden files under core/proto/content/v1/testdata are the " +
			"binding contract; this schema is a generated convenience for non-proto " +
			"consumers. Unknown properties are permitted (the canonical decoder " +
			"ignores them for forward compatibility).",
		"$defs": defs,
	}
	out, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return "", err
	}
	return string(out) + "\n", nil
}

// messageSchema renders one message as an object schema. Every property is
// optional (canonical protojson omits unpopulated fields); each oneof group
// contributes a `oneOf` constraint requiring exactly one of its members.
func messageSchema(md protoreflect.MessageDescriptor) (map[string]any, error) {
	props := map[string]any{}
	fields := md.Fields()
	for i := range fields.Len() {
		f := fields.Get(i)
		fs, err := fieldSchema(f)
		if err != nil {
			return nil, fmt.Errorf("field %s: %w", f.Name(), err)
		}
		props[f.JSONName()] = fs
	}
	schema := map[string]any{
		"type":       "object",
		"properties": props,
	}
	if md.Oneofs().Len() == 1 {
		oo := md.Oneofs().Get(0)
		var alts []any
		for i := range oo.Fields().Len() {
			alts = append(alts, map[string]any{
				"required": []any{oo.Fields().Get(i).JSONName()},
			})
		}
		schema["oneOf"] = alts
	} else if md.Oneofs().Len() > 1 {
		return nil, errors.New("multiple oneofs are not supported by this generator")
	}
	return schema, nil
}

// fieldSchema renders one field's value schema under canonical protojson.
func fieldSchema(f protoreflect.FieldDescriptor) (map[string]any, error) {
	if f.IsMap() {
		val, err := scalarSchema(f.MapValue())
		if err != nil {
			return nil, err
		}
		return map[string]any{"type": "object", "additionalProperties": val}, nil
	}
	elem, err := scalarSchema(f)
	if err != nil {
		return nil, err
	}
	if f.IsList() {
		return map[string]any{"type": "array", "items": elem}, nil
	}
	return elem, nil
}

func scalarSchema(f protoreflect.FieldDescriptor) (map[string]any, error) {
	switch f.Kind() {
	case protoreflect.BoolKind:
		return map[string]any{"type": "boolean"}, nil
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return map[string]any{"type": "integer"}, nil
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return map[string]any{"type": "number"}, nil
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		// protojson encodes 64-bit integers as strings.
		return map[string]any{"type": "string", "pattern": "^-?[0-9]+$"}, nil
	case protoreflect.StringKind:
		return map[string]any{"type": "string"}, nil
	case protoreflect.BytesKind:
		return map[string]any{"type": "string", "contentEncoding": "base64"}, nil
	case protoreflect.MessageKind:
		return map[string]any{"$ref": "#/$defs/" + string(f.Message().Name())}, nil
	default:
		return nil, fmt.Errorf("unsupported proto kind %s", f.Kind())
	}
}
