import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// One sidebar per top-level navbar section. Each section is surfaced directly
// in the navbar (see docusaurus.config.ts) so readers reach a context without
// first opening a generic "Documentation" menu.
const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [
    "getting-started/introduction",
    "getting-started/installation",
    "getting-started/quickstart",
    "getting-started/try-it",
  ],

  cliSidebar: [
    "kapi-cli/overview",
    "kapi-cli/using-with-claude",
    "kapi-cli/bilingual-workflow",
    // The hand-written per-command pages were retired in favor of the generated,
    // runnable /commands reference (issue #660). The navbar Reference dropdown
    // links there; old /kapi-cli/commands/* URLs redirect via
    // docusaurus.config.ts.
    {
      type: "category",
      label: "Use Cases",
      items: ["kapi-cli/use-cases/terminology-qa", "kapi-cli/use-cases/terminology-pretranslation"],
    },
    "kapi-cli/mcp",
  ],

  walkthroughsSidebar: [
    "walkthroughs/index",
    "walkthroughs/kapi-overview",
    "walkthroughs/kapi-word-count",
    "walkthroughs/kapi-pseudo-translate",
    "walkthroughs/kapi-bilingual-workflow",
    "walkthroughs/kapi-terminology-qa",
    "walkthroughs/kapi-terminology-pretranslation",
  ],

  reactSidebar: [
    "kapi-react/introduction",
    "kapi-react/quickstart",
    "kapi-react/writing-components",
    "kapi-react/t-escape-hatch",
    "kapi-react/plurals-and-select",
    "kapi-react/formatting",
    "kapi-react/pipeline",
    "kapi-react/modes",
    "kapi-react/translating-with-kapi",
    "kapi-react/linting",
    "kapi-react/configuration",
    "kapi-react/alternatives",
  ],

  desktopSidebar: [
    "kapi-desktop/overview",
    "kapi-desktop/getting-started",
    "kapi-desktop/project-file",
  ],

  frameworkSidebar: [
    "developer/architecture",
    "developer/interfaces",
    {
      type: "category",
      label: "Concepts",
      items: [
        "features/formats",
        "features/inline-formatting",
        "features/translation-memory",
        "features/terminology",
        "developer/vocabularies",
        "features/ai-translation",
        "features/mt-services",
        "features/qa-checks",
        "features/brand-voice",
        "features/redaction",
      ],
    },
    {
      type: "category",
      label: "Extending the Framework",
      items: [
        "guides/tool-authoring",
        "guides/flow-authoring",
        "guides/script-step",
        "developer/formats",
        "developer/tools",
        "developer/plugins",
        "developer/java-bridge",
        "developer/testing",
        "developer/graph",
      ],
    },
    {
      type: "category",
      label: "Architecture Decisions",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "architecture" }],
    },
    {
      type: "category",
      label: "Implementation Notes",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "notes-internal" }],
    },
  ],
};

export default sidebars;
