import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// One sidebar per top-level navbar section.
//
//   Kapi        — the product: getting started (install, quickstart,
//                 Claude), CLI usage, recipes, the desktop app, the project model.
//   Framework   — the engine: an Overview, the concepts, then the deep-dive
//                 material (extending the framework, architecture decisions,
//                 implementation notes) formerly under a separate "Contribute".
//   Reference   — generated per-entry pages, the interactive grids, and MCP.
//   Toolbox     — the CLI text utilities and the Kapi React library.
//
// Section headings use `collapsible: false` so they render as static labels
// (not collapsible menus). The two long reference lists — Architecture Decisions
// and Implementation Notes — stay collapsible because always-expanding them
// would dominate the sidebar.
//
// Concept/AD/note lists stay autogenerated so pages can be added/reordered via
// `sidebar_position` frontmatter without editing this file.
const sidebars: SidebarsConfig = {
  kapiSidebar: [
    {
      type: "category",
      label: "Get Started",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        { type: "doc", id: "kapi/overview", label: "Overview" },
        "kapi/get-started/installation",
        "kapi/get-started/quickstart",
        "kapi/get-started/use-with-claude",
      ],
    },
    {
      type: "category",
      label: "Kapi CLI",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        { type: "doc", id: "kapi/recipes/index", label: "Overview" },
        "kapi/recipes/overview",
        "kapi/recipes/estimate-cost",
        "kapi/recipes/pseudo-translate",
        "kapi/recipes/terminology-qa",
        "kapi/recipes/pre-translate-with-tm",
        "kapi/bilingual-workflow",
      ],
    },
    {
      type: "category",
      label: "Kapi Desktop",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [{ type: "doc", id: "kapi/desktop/overview", label: "Overview" }],
    },
  ],

  // Framework spine + the (formerly separate) Contribute material, merged so the
  // whole engine lives in one section, shallow-to-deep.
  frameworkSidebar: [
    {
      type: "category",
      label: "Concepts",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [{ type: "autogenerated", dirName: "framework" }],
    },
    {
      type: "category",
      label: "Extending the Framework",
      collapsible: false,
      className: "sidebar-section-heading",
      items: [
        "contribute/tool-authoring",
        "contribute/flow-authoring",
        "contribute/script-step",
        "contribute/formats",
        "contribute/tools",
        "contribute/plugins",
        "contribute/java-bridge",
        "contribute/testing",
        "contribute/graph",
        "contribute/vocabularies",
        "contribute/interfaces",
      ],
    },
    {
      type: "category",
      label: "Architecture Decisions",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "contribute/architecture" }],
    },
    {
      type: "category",
      label: "Implementation Notes",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "contribute/notes-internal" }],
    },
  ],

  referenceSidebar: ["reference/index", "reference/project-file", "reference/klf-format", "reference/mcp"],

  toolboxSidebar: [
    "toolbox/overview",
    "toolbox/kgrep",
    "toolbox/ksed",
    "toolbox/kcat",
  ],

  reactSidebar: [
    "react/introduction",
    "react/quickstart",
    "react/writing-components",
    "react/t-escape-hatch",
    "react/plurals-and-select",
    "react/formatting",
    "react/pipeline",
    "react/modes",
    "react/translating-with-kapi",
    "react/linting",
    "react/configuration",
    "react/alternatives",
  ],
};

export default sidebars;
