#!/usr/bin/env node
// scripts/learn-gen/gen.ts
//
// The learning labs run in the sample projects under samples/ (Northsea,
// Compass, Mart): the sample is the fixture, as it is for the harness
// recordings, so a lab and the tree a reader clones cannot drift apart. The
// browser has no file system to clone into, so this generator writes the
// samples' text files into one TypeScript module the player seeds the engine
// from.
//
// Reads:  samples/<id>/** (text files; README.md and node_modules left out)
// Emits:  packages/kapi-learn/src/samples.gen.ts
//
// Reproducible: same tree → byte-identical output. No timestamps, no paths
// outside the sample.
//
// Usage:
//   node --experimental-strip-types scripts/learn-gen/gen.ts
//   node --experimental-strip-types scripts/learn-gen/gen.ts --check   # CI: fail if stale

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, dirname, resolve as pathResolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = pathResolve(__dirname, "../..");
const SAMPLES_DIR = join(REPO_ROOT, "samples");
const OUT = join(REPO_ROOT, "packages/kapi-learn/src/samples.gen.ts");

/** The samples the labs run in, in the order the index presents them. */
const SAMPLE_IDS = ["northsea", "compass", "mart"] as const;

/** Left out of every sample: prose about the sample, and dependency trees. */
const SKIP_NAMES = new Set(["README.md", "node_modules", "package-lock.json"]);

interface SampleFile {
  path: string;
  content: string;
}

function isText(bytes: Buffer): boolean {
  // A NUL byte in the first 8 KiB marks a binary file; the samples carry none.
  const head = bytes.subarray(0, 8192);
  return !head.includes(0);
}

function collect(dir: string, root: string, out: SampleFile[]): void {
  for (const name of readdirSync(dir).sort()) {
    if (SKIP_NAMES.has(name)) continue;
    const abs = join(dir, name);
    if (statSync(abs).isDirectory()) {
      collect(abs, root, out);
      continue;
    }
    const bytes = readFileSync(abs);
    const rel = relative(root, abs).split("\\").join("/");
    if (!isText(bytes)) {
      throw new Error(`learn-gen: ${rel} is binary; the labs seed text files only`);
    }
    out.push({ path: rel, content: bytes.toString("utf8") });
  }
}

function render(): string {
  const lines: string[] = [];
  lines.push("// GENERATED by scripts/learn-gen/gen.ts from samples/. Do not edit by hand.");
  lines.push("//");
  lines.push("// The sample projects the learning labs run in, file by file. Regenerate");
  lines.push("// after changing a sample:");
  lines.push("//   node --experimental-strip-types scripts/learn-gen/gen.ts");
  lines.push("");
  lines.push("export interface SampleFile {");
  lines.push("  /** Path relative to the sample's root. */");
  lines.push("  path: string;");
  lines.push("  content: string;");
  lines.push("}");
  lines.push("");
  lines.push("export const SAMPLE_TREES = {");
  for (const id of SAMPLE_IDS) {
    const root = join(SAMPLES_DIR, id);
    if (!existsSync(root)) throw new Error(`learn-gen: samples/${id} is missing`);
    const files: SampleFile[] = [];
    collect(root, root, files);
    lines.push(`  ${id}: [`);
    for (const f of files) {
      lines.push(`    { path: ${JSON.stringify(f.path)}, content: ${JSON.stringify(f.content)} },`);
    }
    lines.push("  ],");
  }
  lines.push("} as const satisfies Record<string, readonly SampleFile[]>;");
  lines.push("");
  lines.push("export type SampleTreeId = keyof typeof SAMPLE_TREES;");
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const check = process.argv.includes("--check");
  const next = render();
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : null;
  if (check) {
    if (current !== next) {
      console.error(
        `learn-gen: ${relative(REPO_ROOT, OUT)} is stale; run \`node --experimental-strip-types scripts/learn-gen/gen.ts\``,
      );
      process.exit(1);
    }
    console.log(`learn-gen: ${relative(REPO_ROOT, OUT)} is up to date`);
    return;
  }
  if (current === next) {
    console.log(`learn-gen: ${relative(REPO_ROOT, OUT)} unchanged`);
    return;
  }
  writeFileSync(OUT, next);
  console.log(`learn-gen: wrote ${relative(REPO_ROOT, OUT)}`);
}

main();
