//go:build integration

package okf_json

// Code generated by gen-test-stubs from Surefire XML. DO NOT EDIT.
// To implement a test, move it to the appropriate test file and
// replace t.Skip("pending") with test logic.

import "testing"

// ---- JSONFilterTest (43 tests) ----

// okapi: JSONFilterTest#metaDataAndExtractionRulesNestedNotes
func TestExtract_MetaDataAndExtractionRulesNestedNotes(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#metaDataAndExtractionRulesWithSubfilter
func TestExtract_MetaDataAndExtractionRulesWithSubfilter(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testAllWithKeyWithException
func TestExtract_AllWithKeyWithException(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testArrayWithObject
func TestExtract_ArrayWithObject(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testArrayWithinArray
func TestExtract_ArrayWithinArray(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testArrayWithinArrayWithinArray
func TestExtract_ArrayWithinArrayWithinArray(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testDefaultInfo
func TestExtract_DefaultInfo(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testDoubleExtraction
func TestRoundTrip_DoubleExtraction(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testDoubleExtractionOnInvalid
func TestRoundTrip_DoubleExtractionOnInvalid(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testDoubleExtractionOnPreviousFailure
func TestRoundTrip_DoubleExtractionOnPreviousFailure(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testEscape
func TestExtract_Escape(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testEscapeForwardSlashes
func TestExtract_EscapeForwardSlashes(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testEscapeForwardSlashesSubfilter
func TestExtract_EscapeForwardSlashesSubfilter(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testEscapedForwardSlashDecoding
func TestExtract_EscapedForwardSlashDecoding(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testExtractionRules
func TestExtract_ExtractionRules(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testGenericMetaRules
func TestExtract_GenericMetaRules(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testGenericMetaRulesWithId
func TestExtract_GenericMetaRulesWithId(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testIdRules
func TestExtract_IdRules(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testInlineCodeFinderEscaping
func TestExtract_InlineCodeFinderEscaping(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testInlineCodeFinderNewLineCharacter
func TestExtract_InlineCodeFinderNewLineCharacter(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testLeadingSlash
func TestExtract_LeadingSlash(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testLineBreaks
func TestExtract_LineBreaks(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testList
func TestExtract_List(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testMaxwidthRules
func TestExtract_MaxwidthRules(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testMaxwidthRulesWithSizeChar
func TestExtract_MaxwidthRulesWithSizeChar(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testMultilineComment
func TestExtract_MultilineComment(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testNamedArray
func TestExtract_NamedArray(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testNestedComments
func TestExtract_NestedComments(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testNestedIdRules
func TestExtract_NestedIdRules(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testNoEscapeForwardSlashes
func TestExtract_NoEscapeForwardSlashes(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testNoneWithKeywithException
func TestExtract_NoneWithKeywithException(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testNoteRules
func TestExtract_NoteRules(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testPath
func TestExtract_Path(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testSimpleEntrySkeleton
func TestExtract_SimpleEntrySkeleton(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testSmartQuotes
func TestExtract_SmartQuotes(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testStandaloneYes
func TestExtract_StandaloneYes(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testSubFilterDoubleExtraction
func TestRoundTrip_SubFilterDoubleExtraction(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testSubfilter
func TestExtract_Subfilter(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testSubfilterEasyToDebug
func TestExtract_SubfilterEasyToDebug(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testSubfilterRules
func TestExtract_SubfilterRules(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testSubfiltersProduceDistinctTextUnitIds
func TestExtract_SubfiltersProduceDistinctTextUnitIds(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testVariableMaxWidthInNestedObjects
func TestExtract_VariableMaxWidthInNestedObjects(t *testing.T) {
	t.Skip("pending")
}

// okapi: JSONFilterTest#testWhiteSpaceAndComments
func TestExtract_WhiteSpaceAndComments(t *testing.T) {
	t.Skip("pending")
}

// ---- JsonSnippetParserTest (1 tests) ----

// okapi: JsonSnippetParserTest#testSingleObject
func TestParse_SingleObject(t *testing.T) {
	t.Skip("pending")
}
