// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as convergence$0 from "../core/convergence/models.js";

/**
 * AIModelOrigin says which layer supplied the effective value.
 * @readonly
 * @enum {string}
 */
export const AIModelOrigin = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * AIModelFromLocalePreset — `defaults.locales.<lang>.tools.<tool>` in the recipe.
     */
    AIModelFromLocalePreset: "locale-preset",

    /**
     * AIModelFromProjectPreset — `defaults.tools.<tool>` in the recipe.
     */
    AIModelFromProjectPreset: "project-preset",

    /**
     * AIModelFromAppConfig — the stored `ai.provider` / `ai.model` (the file at
     * config.GlobalConfigFilePath, or the KAPI_AI_* environment overrides), which
     * is what `kapi models setup` and `kapi models default` write.
     */
    AIModelFromAppConfig: "app-config",

    /**
     * AIModelFromBuiltIn — nothing configured; the tool's own default applies.
     */
    AIModelFromBuiltIn: "built-in",
};

/**
 * AIModelResolution is the provider/model an AI tool will run with, plus where
 * each half came from.
 */
export class AIModelResolution {
    /**
     * Creates a new AIModelResolution instance.
     * @param {Partial<AIModelResolution>} [$$source = {}] - The source object to create the AIModelResolution.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * Provider is the effective provider id ("anthropic", "ollama", …).
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * Model is the effective model name. Empty means "the provider's own
             * default", which is the honest answer when nothing pins a model.
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("provider_origin" in $$source)) {
            /**
             * ProviderOrigin / ModelOrigin name the layer each value came from, so a UI
             * can explain *why* this is active ("from your recipe", "from kapi models
             * default").
             * @member
             * @type {AIModelOrigin}
             */
            this["provider_origin"] = AIModelOrigin.$zero;
        }
        if (!("model_origin" in $$source)) {
            /**
             * @member
             * @type {AIModelOrigin}
             */
            this["model_origin"] = AIModelOrigin.$zero;
        }
        if (!("configured" in $$source)) {
            /**
             * Configured is false when neither half is configured anywhere — the
             * built-in fallback is carrying the run, which is worth surfacing rather
             * than presenting as a deliberate choice.
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIModelResolution instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIModelResolution}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIModelResolution(/** @type {Partial<AIModelResolution>} */($$parsedSource));
    }
}

/**
 * ConvergeLocaleResult is the per-locale outcome of a convergence run.
 */
export class ConvergeLocaleResult {
    /**
     * Creates a new ConvergeLocaleResult instance.
     * @param {Partial<ConvergeLocaleResult>} [$$source = {}] - The source object to create the ConvergeLocaleResult.
     */
    constructor($$source = {}) {
        if (!("locale" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["locale"] = "";
        }
        if (!("shippable" in $$source)) {
            /**
             * every gated scope for this locale clears its gate
             * @member
             * @type {boolean}
             */
            this["shippable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * still short of its gate after the loop (needs human)
             * @member
             * @type {boolean | undefined}
             */
            this["parked"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ladder state → "at least" percent
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["pct"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * FailingChecks counts units that are produced but fail the project's
             * bound checks (#1078 G4) — they read at `draft`, not `translated`, for
             * gating, so they hold the locale below its gate until fixed.
             * @member
             * @type {number | undefined}
             */
            this["failingChecks"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Materialized counts the target files written for this locale by the
             * post-loop materialize step (defaults.materialize: on-converge, or
             * --materialize). Only shippable locales materialize; a parked locale
             * stays at 0.
             * @member
             * @type {number | undefined}
             */
            this["materialized"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConvergeLocaleResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConvergeLocaleResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pct" in $$parsedSource) {
            $$parsedSource["pct"] = $$createField3_0($$parsedSource["pct"]);
        }
        return new ConvergeLocaleResult(/** @type {Partial<ConvergeLocaleResult>} */($$parsedSource));
    }
}

/**
 * ConvergeOutput is the structured result of `kapi run` driving the default
 * flow over a project's content. One pass by default; looped to the ship gate
 * under --until-gate.
 */
export class ConvergeOutput {
    /**
     * Creates a new ConvergeOutput instance.
     * @param {Partial<ConvergeOutput>} [$$source = {}] - The source object to create the ConvergeOutput.
     */
    constructor($$source = {}) {
        if (!("flow" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["flow"] = "";
        }
        if (!("passes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["passes"] = 0;
        }
        if (!("converged" in $$source)) {
            /**
             * every gated scope is shippable
             * @member
             * @type {boolean}
             */
            this["converged"] = false;
        }
        if (!("locales" in $$source)) {
            /**
             * @member
             * @type {ConvergeLocaleResult[]}
             */
            this["locales"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * ParkedScopes lists the gated (collection, locale) scopes that remain
             * short of their gate — per-scope detail under the per-locale rollup, so
             * a UI can link each parked scope to its review queue.
             * @member
             * @type {ParkedScope[] | undefined}
             */
            this["parkedScopes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * MaterializedFiles is the total count of target files written by the
             * post-loop materialize step across every shippable locale (0 when the
             * policy is manual and --materialize was not passed).
             * @member
             * @type {number | undefined}
             */
            this["materializedFiles"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * BlockedOnSource is how many translatable source blocks were held below the
             * active source gate this run (epic 019): their translations were NOT
             * produced because the source is un-settled. 0 when the gate is `none` or the
             * source is fully settled. It is source-scoped (deduped across locales — a
             * source block is shared by every target), mirroring the server's run row.
             * @member
             * @type {number | undefined}
             */
            this["blockedOnSource"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SourceGate is the resolved source-first gate level applied
             * (none|authored|checked|approved), for observability. Empty when no gate
             * was evaluated (no content).
             * @member
             * @type {string | undefined}
             */
            this["sourceGate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * StallReason is the machine-readable cause a run did not converge — set to
             * source_not_ready when every pending locale had nothing producible because
             * its source is held below the gate. Empty on a clean/parked-on-target run.
             * @member
             * @type {string | undefined}
             */
            this["stallReason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConvergeOutput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConvergeOutput}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("locales" in $$parsedSource) {
            $$parsedSource["locales"] = $$createField3_0($$parsedSource["locales"]);
        }
        if ("parkedScopes" in $$parsedSource) {
            $$parsedSource["parkedScopes"] = $$createField4_0($$parsedSource["parkedScopes"]);
        }
        return new ConvergeOutput(/** @type {Partial<ConvergeOutput>} */($$parsedSource));
    }
}

/**
 * The convergence report MODEL and the per-block ladder helpers live in the
 * framework (core/convergence) so any surface derives the same shape from the
 * same rules. The CLI owns the file-IO orchestration that feeds them
 * (UnitsFromProject, readBlocks, bilingualBlocks, the state-store review index)
 * and re-exports the types via aliases so existing CLI + desktop callers — and
 * the generated Wails bindings — are unchanged.
 *
 * ConvergenceReport is the full derived convergence picture (alias of
 * convergence.Report). Returned by ProjectConvergence and consumed by the
 * Kapi Desktop.
 */
export const ConvergenceReport = convergence$0.Report;

/**
 * The convergence report MODEL and the per-block ladder helpers live in the
 * framework (core/convergence) so any surface derives the same shape from the
 * same rules. The CLI owns the file-IO orchestration that feeds them
 * (UnitsFromProject, readBlocks, bilingualBlocks, the state-store review index)
 * and re-exports the types via aliases so existing CLI + desktop callers — and
 * the generated Wails bindings — are unchanged.
 *
 * ConvergenceReport is the full derived convergence picture (alias of
 * convergence.Report). Returned by ProjectConvergence and consumed by the
 * Kapi Desktop.
 * @typedef {convergence$0.Report} ConvergenceReport
 */

/**
 * ParkedScope identifies one gated (collection, locale) scope still short of
 * its gate after the run — the address a review surface can deep-link to.
 */
export class ParkedScope {
    /**
     * Creates a new ParkedScope instance.
     * @param {Partial<ParkedScope>} [$$source = {}] - The source object to create the ParkedScope.
     */
    constructor($$source = {}) {
        if (!("locale" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["locale"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["collection"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParkedScope instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ParkedScope}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParkedScope(/** @type {Partial<ParkedScope>} */($$parsedSource));
    }
}

/**
 * The convergence report MODEL and the per-block ladder helpers live in the
 * framework (core/convergence) so any surface derives the same shape from the
 * same rules. The CLI owns the file-IO orchestration that feeds them
 * (UnitsFromProject, readBlocks, bilingualBlocks, the state-store review index)
 * and re-exports the types via aliases so existing CLI + desktop callers — and
 * the generated Wails bindings — are unchanged.
 */
export const ReviewItem = convergence$0.ReviewItem;

/**
 * The convergence report MODEL and the per-block ladder helpers live in the
 * framework (core/convergence) so any surface derives the same shape from the
 * same rules. The CLI owns the file-IO orchestration that feeds them
 * (UnitsFromProject, readBlocks, bilingualBlocks, the state-store review index)
 * and re-exports the types via aliases so existing CLI + desktop callers — and
 * the generated Wails bindings — are unchanged.
 * @typedef {convergence$0.ReviewItem} ReviewItem
 */

/**
 * UpPlanOutput is the structured result of `kapi up --plan`: the dry-run work
 * plan per (collection, locale), with totals. No provider calls are made and
 * nothing is written.
 */
export class UpPlanOutput {
    /**
     * Creates a new UpPlanOutput instance.
     * @param {Partial<UpPlanOutput>} [$$source = {}] - The source object to create the UpPlanOutput.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["flow"] = undefined;
        }
        if (!("scopes" in $$source)) {
            /**
             * @member
             * @type {UpPlanScope[]}
             */
            this["scopes"] = [];
        }
        if (!("totals" in $$source)) {
            /**
             * @member
             * @type {UpPlanScope}
             */
            this["totals"] = (new UpPlanScope());
        }
        if (/** @type {any} */(false)) {
            /**
             * Provider is the AI provider a converge run would use (the shared
             * ai.provider default), when one is configured.
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Subscription is true when that provider bills a personal subscription
             * (claude-code): the token estimate is scale, not a metered API cost.
             * @member
             * @type {boolean | undefined}
             */
            this["subscription"] = undefined;
        }
        if (!("note" in $$source)) {
            /**
             * Note documents the estimation method for agents reading the JSON.
             * @member
             * @type {string}
             */
            this["note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpPlanOutput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpPlanOutput}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scopes" in $$parsedSource) {
            $$parsedSource["scopes"] = $$createField1_0($$parsedSource["scopes"]);
        }
        if ("totals" in $$parsedSource) {
            $$parsedSource["totals"] = $$createField2_0($$parsedSource["totals"]);
        }
        return new UpPlanOutput(/** @type {Partial<UpPlanOutput>} */($$parsedSource));
    }
}

/**
 * UpPlanScope is the planned work for one (collection, locale) scope: how many
 * units have no target yet, how many of those an exact content-memory hit would cover, and
 * what remains for AI translation with a rough token estimate.
 */
export class UpPlanScope {
    /**
     * Creates a new UpPlanScope instance.
     * @param {Partial<UpPlanScope>} [$$source = {}] - The source object to create the UpPlanScope.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["locale"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["collection"] = undefined;
        }
        if (!("missingTarget" in $$source)) {
            /**
             * MissingTarget is the count of translatable units with no committed
             * target for the locale.
             * @member
             * @type {number}
             */
            this["missingTarget"] = 0;
        }
        if (!("tmExact" in $$source)) {
            /**
             * MemoryExact is the count of missing units covered by an exact-hash content-memory hit
             * (the cheap leverage estimate — fuzzy leverage is not counted).
             * @member
             * @type {number}
             */
            this["tmExact"] = 0;
        }
        if (!("aiRemaining" in $$source)) {
            /**
             * AIRemaining is the count of missing units left for AI translation
             * after content-memory leverage.
             * @member
             * @type {number}
             */
            this["aiRemaining"] = 0;
        }
        if (!("tokenEstimate" in $$source)) {
            /**
             * TokenEstimate approximates the input tokens for the remaining AI work:
             * source characters / 4 (a common chars-per-token heuristic — the
             * providers expose no tokenizer here, so this is an estimate, not a
             * quote).
             * @member
             * @type {number}
             */
            this["tokenEstimate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpPlanScope instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpPlanScope}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpPlanScope(/** @type {Partial<UpPlanScope>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ConvergeLocaleResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ParkedScope.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = UpPlanScope.createFrom;
const $$createType6 = $Create.Array($$createType5);
