/**
 * Component Parameter Schema Types
 *
 * These types match the JSON Schema format generated by the okapi-bridge
 * schema generator and the Go schema.FromStruct() reflection helper,
 * with x-* extensions for UI rendering.
 *
 * Both filters and tools use the same schema format. FilterSchema is a
 * specialization of ComponentSchema with filter-specific metadata.
 */

/** Generalized component schema — works for both filters and tools. */
export interface ComponentSchema {
  $id: string;
  $version?: string;
  title: string;
  description?: string;
  type: string;
  "x-component"?: ComponentMeta;
  "x-filter"?: FilterMeta;
  "x-groups"?: ParameterGroup[];
  properties: Record<string, PropertySchema>;
}

/** Component metadata (for tools, steps, etc.) */
export interface ComponentMeta {
  id: string;
  type: string; // "format" | "tool" | "step"
  category?: string; // "transform" | "validate" | "enrich" | "convert" | "pipeline"
  displayName?: string;
  description?: string;
}

/** Filter-specific schema (backward compatible specialization). */
export interface FilterSchema extends ComponentSchema {
  "x-filter": FilterMeta;
}

export interface FilterMeta {
  id: string;
  class: string;
  extensions: string[];
  mimeTypes: string[];
}

export interface ParameterGroup {
  id: string;
  label: string;
  description?: string;
  collapsed?: boolean;
  fields: string[];
}

export interface PropertySchema {
  type: string;
  description?: string;
  default?: unknown;
  deprecated?: boolean;
  enum?: string[];

  // Nested object properties
  properties?: Record<string, PropertySchema>;
  additionalProperties?: PropertySchema | boolean;
  items?: PropertySchema;
  required?: string[];

  // UI hints (x-* extensions)
  "x-widget"?: WidgetType;
  "x-placeholder"?: string;
  "x-presets"?: Record<string, unknown>;
  "x-okapiFormat"?: string;
  "x-order"?: number;
  "x-showIf"?: ShowIfCondition;
}

export type WidgetType =
  | "regexBuilder"
  | "codeFinderRules"
  | "tagList"
  | "numberList"
  | "simplifierRulesEditor"
  | "filterSelector";

export interface ShowIfCondition {
  field: string;
  value: unknown;
}

/**
 * CodeFinderRules value structure (clean JSON format).
 */
export interface CodeFinderRulesValue {
  rules: Array<{ pattern: string }>;
  sample?: string;
  useAllRulesWhenTesting?: boolean;
}

/**
 * Filter parameters value type.
 */
export type FilterParamsValue = Record<string, unknown>;
