// sync.proto — Sync protocol messages.
// Defines the content layer for chunked, diff-based content sync between a
// project and a venue.
//
// These messages live in their own proto + Go package (syncv1), beside the
// canonical content schema, so any client can speak the sync wire without
// pulling in a venue's service surface. The proto package name carries no
// venue noun and the encoding depends only on field numbers, so the schema is
// independent of where either side of the exchange lives.
//
// Run/segment content embeds the canonical content-model schema
// (core/proto/content/v1, see AD-034) instead of redefining it. The former
// SyncSegment/SyncRun/SyncTextRun/… messages were field-for-field identical
// to SegmentMessage/RunMessage/TextRunMessage/…, so this substitution is
// wire-identical: same field numbers, same field types, byte-identical
// encoding. Only the sync-specific envelope (hashes, expected_hash, the
// *_json escapes) is defined here.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: core/proto/sync/v1/sync.proto

package syncv1

import (
	v1 "github.com/neokapi/neokapi/core/proto/content/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncRef is a stream's freshness ref: one composite value answering how far
// what a client holds sits from what the server holds, on every axis at once
// (core/ref.Ref).
//
// The four components are not the same kind of value. `content` is a monotonic
// position in the stream's change feed — ahead and behind are meaningful and a
// transfer resumes from it. The other three are identity hashes, compared for
// equality and for nothing else: two unequal hashes carry no ordering, so the
// ref reports that governance moved and leaves the resolution to a caller who
// can ask a human.
//
// A writer asserts only the component it owns (SyncManifest.expected_ref), so
// ordinary content traffic — which moves nothing but the position — can never
// manufacture a governance conflict for a writer nowhere near it. An empty
// component asserts nothing, which is what keeps the compare-and-swap additive:
// a client that predates the ref sends none and writes exactly as before.
type SyncRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content is the position in the stream's change feed (change_log.seq).
	Content int64 `protobuf:"varint,1,opt,name=content,proto3" json:"content,omitempty"`
	// Context identifies the governing context: which collections exist, the
	// point each occupies, and the voice profile governing it. It is the same
	// fold SyncPushInit.context_hash negotiates on.
	Context string `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	// Terms identifies the governed terminology in force for the workspace.
	Terms string `protobuf:"bytes,3,opt,name=terms,proto3" json:"terms,omitempty"`
	// Decisions identifies the committed decision record for this stream.
	Decisions     string `protobuf:"bytes,4,opt,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRef) Reset() {
	*x = SyncRef{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRef) ProtoMessage() {}

func (x *SyncRef) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRef.ProtoReflect.Descriptor instead.
func (*SyncRef) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRef) GetContent() int64 {
	if x != nil {
		return x.Content
	}
	return 0
}

func (x *SyncRef) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *SyncRef) GetTerms() string {
	if x != nil {
		return x.Terms
	}
	return ""
}

func (x *SyncRef) GetDecisions() string {
	if x != nil {
		return x.Decisions
	}
	return ""
}

// SyncPushInit is the first step in a push. The client sends item-level
// hashes so the server can compute the diff.
type SyncPushInit struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ProjectId    string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Stream       string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	ContentTypes []string               `protobuf:"bytes,3,rep,name=content_types,json=contentTypes,proto3" json:"content_types,omitempty"` // "blocks", "context", "terms", "memory", "media"
	// Merkle tree: item-level hashes (item_name → hash of block hashes).
	ItemHashes map[string]string `protobuf:"bytes,4,rep,name=item_hashes,json=itemHashes,proto3" json:"item_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Fast path: root hash of all item hashes. If server matches, nothing changed.
	RootHash string `protobuf:"bytes,5,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// Collection-level hashes for non-block content.
	TermsHash  string `protobuf:"bytes,6,opt,name=terms_hash,json=termsHash,proto3" json:"terms_hash,omitempty"`
	MemoryHash string `protobuf:"bytes,7,opt,name=memory_hash,json=memoryHash,proto3" json:"memory_hash,omitempty"`
	// Fast path for the context content type: a hash over every declared
	// collection's context entry (see SyncContextEntry.content_hash). When it
	// matches the server's, the recipe's declared structure and governance are
	// already in force and the whole context reconcile is skipped.
	ContextHash string `protobuf:"bytes,8,opt,name=context_hash,json=contextHash,proto3" json:"context_hash,omitempty"`
	// The names of the content collections the recipe declares. Sent beside
	// context_hash so the server can answer which collections it holds that the
	// recipe no longer declares — the context content type's counterpart to
	// deleted_items, and reported for exactly the same reason: the server says
	// what diverged, it does not act on it.
	Collections   []string `protobuf:"bytes,9,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPushInit) Reset() {
	*x = SyncPushInit{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPushInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPushInit) ProtoMessage() {}

func (x *SyncPushInit) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPushInit.ProtoReflect.Descriptor instead.
func (*SyncPushInit) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncPushInit) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SyncPushInit) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *SyncPushInit) GetContentTypes() []string {
	if x != nil {
		return x.ContentTypes
	}
	return nil
}

func (x *SyncPushInit) GetItemHashes() map[string]string {
	if x != nil {
		return x.ItemHashes
	}
	return nil
}

func (x *SyncPushInit) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *SyncPushInit) GetTermsHash() string {
	if x != nil {
		return x.TermsHash
	}
	return ""
}

func (x *SyncPushInit) GetMemoryHash() string {
	if x != nil {
		return x.MemoryHash
	}
	return ""
}

func (x *SyncPushInit) GetContextHash() string {
	if x != nil {
		return x.ContextHash
	}
	return ""
}

func (x *SyncPushInit) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

type SyncPushInitResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UploadId string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Status   string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "unchanged", "diff_required", "full_upload"
	// Items that need block-level diff.
	ChangedItems []string `protobuf:"bytes,3,rep,name=changed_items,json=changedItems,proto3" json:"changed_items,omitempty"`
	// Items on server that client didn't include (upstream deletions).
	DeletedItems []string `protobuf:"bytes,4,rep,name=deleted_items,json=deletedItems,proto3" json:"deleted_items,omitempty"`
	// New items the client has that server doesn't.
	NewItems []string `protobuf:"bytes,5,rep,name=new_items,json=newItems,proto3" json:"new_items,omitempty"`
	// Whether terms/content memory need re-syncing.
	TermsChanged       bool  `protobuf:"varint,6,opt,name=terms_changed,json=termsChanged,proto3" json:"terms_changed,omitempty"`
	MemoryChanged      bool  `protobuf:"varint,7,opt,name=memory_changed,json=memoryChanged,proto3" json:"memory_changed,omitempty"`
	UnchangedItemCount int32 `protobuf:"varint,8,opt,name=unchanged_item_count,json=unchangedItemCount,proto3" json:"unchanged_item_count,omitempty"`
	// Whether the declared context — collections, their coordinates, their
	// governance — differs from what the server holds. False means the recipe's
	// structure is already in force and the manifest need not carry it.
	ContextChanged bool `protobuf:"varint,9,opt,name=context_changed,json=contextChanged,proto3" json:"context_changed,omitempty"`
	// Collections the server holds under recipe ownership that this push no
	// longer declares. REPORTED, NEVER ACTED ON: a collection is where content
	// lives, and a recipe edit is not consent to drop the server-side content
	// grouped under it. The symmetry with deleted_items is deliberate.
	UndeclaredCollections []string `protobuf:"bytes,10,rep,name=undeclared_collections,json=undeclaredCollections,proto3" json:"undeclared_collections,omitempty"`
	// The server's current freshness ref for this stream, so a push that has
	// already paid for a round trip does not pay for a second one to learn what
	// it must assert in the commit that follows.
	Ref           *SyncRef `protobuf:"bytes,11,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPushInitResponse) Reset() {
	*x = SyncPushInitResponse{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPushInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPushInitResponse) ProtoMessage() {}

func (x *SyncPushInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPushInitResponse.ProtoReflect.Descriptor instead.
func (*SyncPushInitResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncPushInitResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *SyncPushInitResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SyncPushInitResponse) GetChangedItems() []string {
	if x != nil {
		return x.ChangedItems
	}
	return nil
}

func (x *SyncPushInitResponse) GetDeletedItems() []string {
	if x != nil {
		return x.DeletedItems
	}
	return nil
}

func (x *SyncPushInitResponse) GetNewItems() []string {
	if x != nil {
		return x.NewItems
	}
	return nil
}

func (x *SyncPushInitResponse) GetTermsChanged() bool {
	if x != nil {
		return x.TermsChanged
	}
	return false
}

func (x *SyncPushInitResponse) GetMemoryChanged() bool {
	if x != nil {
		return x.MemoryChanged
	}
	return false
}

func (x *SyncPushInitResponse) GetUnchangedItemCount() int32 {
	if x != nil {
		return x.UnchangedItemCount
	}
	return 0
}

func (x *SyncPushInitResponse) GetContextChanged() bool {
	if x != nil {
		return x.ContextChanged
	}
	return false
}

func (x *SyncPushInitResponse) GetUndeclaredCollections() []string {
	if x != nil {
		return x.UndeclaredCollections
	}
	return nil
}

func (x *SyncPushInitResponse) GetRef() *SyncRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type SyncItemDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	BlockHashes   map[string]string      `protobuf:"bytes,3,rep,name=block_hashes,json=blockHashes,proto3" json:"block_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // block_id → content_hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncItemDiff) Reset() {
	*x = SyncItemDiff{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncItemDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncItemDiff) ProtoMessage() {}

func (x *SyncItemDiff) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncItemDiff.ProtoReflect.Descriptor instead.
func (*SyncItemDiff) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncItemDiff) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *SyncItemDiff) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *SyncItemDiff) GetBlockHashes() map[string]string {
	if x != nil {
		return x.BlockHashes
	}
	return nil
}

type SyncItemDiffResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Blocks to upload (new or changed on client).
	Needed []string `protobuf:"bytes,1,rep,name=needed,proto3" json:"needed,omitempty"`
	// Blocks the server has that client doesn't (upstream deletions within item).
	Deleted []string `protobuf:"bytes,2,rep,name=deleted,proto3" json:"deleted,omitempty"`
	// Blocks changed by another client since the requesting client last synced.
	Conflicts []string `protobuf:"bytes,3,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	// Pre-signed URLs for uploading needed blocks as chunks.
	ChunkUrls []string `protobuf:"bytes,4,rep,name=chunk_urls,json=chunkUrls,proto3" json:"chunk_urls,omitempty"`
	// Transport mode: "direct" (SAS URLs) or "proxy" (upload through API).
	Transport     string `protobuf:"bytes,5,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncItemDiffResponse) Reset() {
	*x = SyncItemDiffResponse{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncItemDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncItemDiffResponse) ProtoMessage() {}

func (x *SyncItemDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncItemDiffResponse.ProtoReflect.Descriptor instead.
func (*SyncItemDiffResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *SyncItemDiffResponse) GetNeeded() []string {
	if x != nil {
		return x.Needed
	}
	return nil
}

func (x *SyncItemDiffResponse) GetDeleted() []string {
	if x != nil {
		return x.Deleted
	}
	return nil
}

func (x *SyncItemDiffResponse) GetConflicts() []string {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *SyncItemDiffResponse) GetChunkUrls() []string {
	if x != nil {
		return x.ChunkUrls
	}
	return nil
}

func (x *SyncItemDiffResponse) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

type SyncManifest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UploadId  string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ProjectId string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Stream    string                 `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	// Chunks uploaded to blob storage.
	Chunks []*ChunkRef `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// Item metadata.
	Items []*SyncItemMeta `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	// Who and what pushed.
	ActorId       string            `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	WorkspaceSlug string            `protobuf:"bytes,7,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	ConnectorId   string            `protobuf:"bytes,8,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	Context       map[string]string `protobuf:"bytes,9,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The context content type: the collections the recipe declares, the point
	// each occupies in the project's context space, and the governance resolved
	// for that point. It rides in the manifest rather than in a chunk because it
	// is the shape the uploaded items are stored INTO — one push is one
	// consistent state, so the collections must land in the same transaction as
	// the blocks that reference them.
	Contexts []*SyncContextEntry `protobuf:"bytes,10,rep,name=contexts,proto3" json:"contexts,omitempty"`
	// ExpectedRef is the compare-and-swap assertion: the governance components
	// this push last observed on the server. The server rejects the commit when a
	// component it asserts has moved since, and the client renders that as
	// "governance moved — pull first".
	//
	// Only the components a push actually writes are asserted, and only the ones
	// it carries a value for. The position is never asserted: block traffic moves
	// it constantly and by design, and letting it fail a governance write is the
	// conflation the composite ref exists to end.
	ExpectedRef   *SyncRef `protobuf:"bytes,11,opt,name=expected_ref,json=expectedRef,proto3" json:"expected_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncManifest) Reset() {
	*x = SyncManifest{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncManifest) ProtoMessage() {}

func (x *SyncManifest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncManifest.ProtoReflect.Descriptor instead.
func (*SyncManifest) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *SyncManifest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *SyncManifest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SyncManifest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *SyncManifest) GetChunks() []*ChunkRef {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *SyncManifest) GetItems() []*SyncItemMeta {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SyncManifest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *SyncManifest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *SyncManifest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *SyncManifest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SyncManifest) GetContexts() []*SyncContextEntry {
	if x != nil {
		return x.Contexts
	}
	return nil
}

func (x *SyncManifest) GetExpectedRef() *SyncRef {
	if x != nil {
		return x.ExpectedRef
	}
	return nil
}

type ChunkRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "blocks", "terms", "memory", "media"
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`                                  // SHA-256 of compressed bytes
	RecordCount   int32                  `protobuf:"varint,4,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	ByteSize      int64                  `protobuf:"varint,5,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRef) Reset() {
	*x = ChunkRef{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRef) ProtoMessage() {}

func (x *ChunkRef) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRef.ProtoReflect.Descriptor instead.
func (*ChunkRef) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkRef) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkRef) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ChunkRef) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ChunkRef) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *ChunkRef) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

// SyncChunk is the unit of transfer. Each chunk contains a batch of
// typed records. A single push can mix content types across chunks.
type SyncChunk struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContentType string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	RecordCount int32                  `protobuf:"varint,2,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	// Exactly one of these is populated (determined by content_type).
	Blocks        []*SyncBlock       `protobuf:"bytes,10,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Terms         []*SyncTerm        `protobuf:"bytes,11,rep,name=terms,proto3" json:"terms,omitempty"`
	MemoryEntries []*SyncMemoryEntry `protobuf:"bytes,12,rep,name=memory_entries,json=memoryEntries,proto3" json:"memory_entries,omitempty"`
	Media         []*SyncMedia       `protobuf:"bytes,13,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChunk) Reset() {
	*x = SyncChunk{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChunk) ProtoMessage() {}

func (x *SyncChunk) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChunk.ProtoReflect.Descriptor instead.
func (*SyncChunk) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{7}
}

func (x *SyncChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SyncChunk) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *SyncChunk) GetBlocks() []*SyncBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *SyncChunk) GetTerms() []*SyncTerm {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *SyncChunk) GetMemoryEntries() []*SyncMemoryEntry {
	if x != nil {
		return x.MemoryEntries
	}
	return nil
}

func (x *SyncChunk) GetMedia() []*SyncMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

// SyncBlock is the sync-protocol envelope around the canonical Block content:
// canonical SegmentMessage/RunMessage payloads (core/proto/content/v1) plus
// the sync-specific fields — item scoping, hashes, and the *_json escapes.
// EXPLICITLY-LABELED ENVELOPE: the run/segment content is the canonical
// schema; only the envelope is defined here.
type SyncBlock struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemName     string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Name         string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type         string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	MimeType     string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Translatable bool                   `protobuf:"varint,6,opt,name=translatable,proto3" json:"translatable,omitempty"`
	// Source content (canonical schema; formerly the wire-identical SyncSegment).
	Source     []*v1.SegmentMessage `protobuf:"bytes,7,rep,name=source,proto3" json:"source,omitempty"`
	SourceText string               `protobuf:"bytes,8,opt,name=source_text,json=sourceText,proto3" json:"source_text,omitempty"` // plain text convenience
	// Translations per locale.
	Targets map[string]*SyncSegmentList `protobuf:"bytes,9,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Metadata.
	Properties      map[string]string `protobuf:"bytes,10,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AnnotationsJson []byte            `protobuf:"bytes,11,opt,name=annotations_json,json=annotationsJson,proto3" json:"annotations_json,omitempty"`
	// Structure.
	SkeletonJson       []byte `protobuf:"bytes,12,opt,name=skeleton_json,json=skeletonJson,proto3" json:"skeleton_json,omitempty"`
	PreserveWhitespace bool   `protobuf:"varint,13,opt,name=preserve_whitespace,json=preserveWhitespace,proto3" json:"preserve_whitespace,omitempty"`
	DisplayHintJson    []byte `protobuf:"bytes,14,opt,name=display_hint_json,json=displayHintJson,proto3" json:"display_hint_json,omitempty"`
	ContentRefJson     []byte `protobuf:"bytes,15,opt,name=content_ref_json,json=contentRefJson,proto3" json:"content_ref_json,omitempty"`
	// Extensible connector data.
	ConnectorData map[string]string `protobuf:"bytes,16,rep,name=connector_data,json=connectorData,proto3" json:"connector_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Conflict detection: hash the client last saw. Server rejects if
	// current hash differs (another client changed it).
	ExpectedHash string `protobuf:"bytes,17,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"`
	// Content hash for diff computation.
	ContentHash string `protobuf:"bytes,18,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// Positional, run-anchored stand-off overlays: segmentation, term, entity,
	// qa, alignment, term-candidate, and any plugin-defined type. Carried as the
	// canonical OverlayMessage (core/proto/content/v1) — typed, not an opaque
	// JSON blob — so every overlay kind, its run-index anchors, props, variant,
	// and typed span value survive push→store→pull losslessly; an unknown/future
	// overlay kind round-trips by type name + JSON (its value degrades to a
	// GenericAnnotation) rather than being dropped. Unlike the content-model
	// BlockMessage — which reconstructs segmentation from its multi-segment
	// source/target boundaries and so EXCLUDES it from its overlays field — a
	// SyncBlock carries source/target as a single wire segment, so segmentation
	// rides in this list explicitly too.
	Overlays []*v1.OverlayMessage `protobuf:"bytes,19,rep,name=overlays,proto3" json:"overlays,omitempty"`
	// Source authoring locale — the locale of the source runs (Block.SourceLocale).
	SourceLocale string `protobuf:"bytes,20,opt,name=source_locale,json=sourceLocale,proto3" json:"source_locale,omitempty"`
	// Whether this block is referenced by a skeleton (Block.IsReferent).
	IsReferent    bool `protobuf:"varint,21,opt,name=is_referent,json=isReferent,proto3" json:"is_referent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncBlock) Reset() {
	*x = SyncBlock{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBlock) ProtoMessage() {}

func (x *SyncBlock) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBlock.ProtoReflect.Descriptor instead.
func (*SyncBlock) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{8}
}

func (x *SyncBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncBlock) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *SyncBlock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyncBlock) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SyncBlock) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *SyncBlock) GetTranslatable() bool {
	if x != nil {
		return x.Translatable
	}
	return false
}

func (x *SyncBlock) GetSource() []*v1.SegmentMessage {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SyncBlock) GetSourceText() string {
	if x != nil {
		return x.SourceText
	}
	return ""
}

func (x *SyncBlock) GetTargets() map[string]*SyncSegmentList {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *SyncBlock) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *SyncBlock) GetAnnotationsJson() []byte {
	if x != nil {
		return x.AnnotationsJson
	}
	return nil
}

func (x *SyncBlock) GetSkeletonJson() []byte {
	if x != nil {
		return x.SkeletonJson
	}
	return nil
}

func (x *SyncBlock) GetPreserveWhitespace() bool {
	if x != nil {
		return x.PreserveWhitespace
	}
	return false
}

func (x *SyncBlock) GetDisplayHintJson() []byte {
	if x != nil {
		return x.DisplayHintJson
	}
	return nil
}

func (x *SyncBlock) GetContentRefJson() []byte {
	if x != nil {
		return x.ContentRefJson
	}
	return nil
}

func (x *SyncBlock) GetConnectorData() map[string]string {
	if x != nil {
		return x.ConnectorData
	}
	return nil
}

func (x *SyncBlock) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

func (x *SyncBlock) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *SyncBlock) GetOverlays() []*v1.OverlayMessage {
	if x != nil {
		return x.Overlays
	}
	return nil
}

func (x *SyncBlock) GetSourceLocale() string {
	if x != nil {
		return x.SourceLocale
	}
	return ""
}

func (x *SyncBlock) GetIsReferent() bool {
	if x != nil {
		return x.IsReferent
	}
	return false
}

// SyncSegmentList wraps a locale's segments so SyncBlock.targets can map
// locale → segments (proto3 maps cannot have repeated-message values).
// The segments themselves are the canonical schema; this wrapper is
// wire-identical to the former SyncSegmentList-of-SyncSegment.
type SyncSegmentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*v1.SegmentMessage   `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSegmentList) Reset() {
	*x = SyncSegmentList{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSegmentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSegmentList) ProtoMessage() {}

func (x *SyncSegmentList) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSegmentList.ProtoReflect.Descriptor instead.
func (*SyncSegmentList) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{9}
}

func (x *SyncSegmentList) GetSegments() []*v1.SegmentMessage {
	if x != nil {
		return x.Segments
	}
	return nil
}

// SyncTerm carries a terminology concept with translations.
type SyncTerm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConceptId     string                 `protobuf:"bytes,1,opt,name=concept_id,json=conceptId,proto3" json:"concept_id,omitempty"`
	SourceTerm    string                 `protobuf:"bytes,2,opt,name=source_term,json=sourceTerm,proto3" json:"source_term,omitempty"`
	SourceLocale  string                 `protobuf:"bytes,3,opt,name=source_locale,json=sourceLocale,proto3" json:"source_locale,omitempty"`
	Translations  []*SyncTermTranslation `protobuf:"bytes,4,rep,name=translations,proto3" json:"translations,omitempty"`
	Definition    string                 `protobuf:"bytes,5,opt,name=definition,proto3" json:"definition,omitempty"`
	Domain        string                 `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // "approved", "pending", "deprecated"
	ContentHash   string                 `protobuf:"bytes,9,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncTerm) Reset() {
	*x = SyncTerm{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTerm) ProtoMessage() {}

func (x *SyncTerm) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTerm.ProtoReflect.Descriptor instead.
func (*SyncTerm) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{10}
}

func (x *SyncTerm) GetConceptId() string {
	if x != nil {
		return x.ConceptId
	}
	return ""
}

func (x *SyncTerm) GetSourceTerm() string {
	if x != nil {
		return x.SourceTerm
	}
	return ""
}

func (x *SyncTerm) GetSourceLocale() string {
	if x != nil {
		return x.SourceLocale
	}
	return ""
}

func (x *SyncTerm) GetTranslations() []*SyncTermTranslation {
	if x != nil {
		return x.Translations
	}
	return nil
}

func (x *SyncTerm) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *SyncTerm) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SyncTerm) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *SyncTerm) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SyncTerm) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

type SyncTermTranslation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	Term          string                 `protobuf:"bytes,2,opt,name=term,proto3" json:"term,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncTermTranslation) Reset() {
	*x = SyncTermTranslation{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTermTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTermTranslation) ProtoMessage() {}

func (x *SyncTermTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTermTranslation.ProtoReflect.Descriptor instead.
func (*SyncTermTranslation) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{11}
}

func (x *SyncTermTranslation) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SyncTermTranslation) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *SyncTermTranslation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// SyncMemoryEntry carries a content memory entry.
//
// This message and the `memory_entries` / `memory_hash` / `memory_changed`
// fields were renamed from their historical `TM` spelling. Message and field
// names are wire schema — serialized into the descriptor and into every
// protojson payload — so this was a breaking protocol change, taken
// deliberately while the sync protocol is pre-production. It was safe to take
// because the content-memory sync path is declared but not yet implemented:
// no producer populates these fields, and the server rejects the "memory"
// content type as unsupported (see jobs/worker_sync.go). Renaming now, before
// anything serializes them, avoids carrying the old vocabulary forever.
type SyncMemoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceLocale  string                 `protobuf:"bytes,2,opt,name=source_locale,json=sourceLocale,proto3" json:"source_locale,omitempty"`
	TargetLocale  string                 `protobuf:"bytes,3,opt,name=target_locale,json=targetLocale,proto3" json:"target_locale,omitempty"`
	SourceText    string                 `protobuf:"bytes,4,opt,name=source_text,json=sourceText,proto3" json:"source_text,omitempty"`
	TargetText    string                 `protobuf:"bytes,5,opt,name=target_text,json=targetText,proto3" json:"target_text,omitempty"`
	Origin        string                 `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"` // "human", "mt", "ai"
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,8,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentHash   string                 `protobuf:"bytes,9,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMemoryEntry) Reset() {
	*x = SyncMemoryEntry{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMemoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMemoryEntry) ProtoMessage() {}

func (x *SyncMemoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMemoryEntry.ProtoReflect.Descriptor instead.
func (*SyncMemoryEntry) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{12}
}

func (x *SyncMemoryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncMemoryEntry) GetSourceLocale() string {
	if x != nil {
		return x.SourceLocale
	}
	return ""
}

func (x *SyncMemoryEntry) GetTargetLocale() string {
	if x != nil {
		return x.TargetLocale
	}
	return ""
}

func (x *SyncMemoryEntry) GetSourceText() string {
	if x != nil {
		return x.SourceText
	}
	return ""
}

func (x *SyncMemoryEntry) GetTargetText() string {
	if x != nil {
		return x.TargetText
	}
	return ""
}

func (x *SyncMemoryEntry) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SyncMemoryEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SyncMemoryEntry) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *SyncMemoryEntry) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// SyncMedia carries a binary asset reference or inline data.
type SyncMedia struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemName string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	MimeType string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Filename string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	AltText  string                 `protobuf:"bytes,5,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	Size     int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	// Exactly one of these:
	InlineData []byte `protobuf:"bytes,10,opt,name=inline_data,json=inlineData,proto3" json:"inline_data,omitempty"` // small assets (< 256KB)
	BlobKey    string `protobuf:"bytes,11,opt,name=blob_key,json=blobKey,proto3" json:"blob_key,omitempty"`          // large assets: separately uploaded blob
	// Locale variants.
	Locale        string            `protobuf:"bytes,12,opt,name=locale,proto3" json:"locale,omitempty"`
	SourceMediaId string            `protobuf:"bytes,13,opt,name=source_media_id,json=sourceMediaId,proto3" json:"source_media_id,omitempty"`
	Properties    map[string]string `protobuf:"bytes,14,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentHash   string            `protobuf:"bytes,15,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // SHA-256 of binary content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMedia) Reset() {
	*x = SyncMedia{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMedia) ProtoMessage() {}

func (x *SyncMedia) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMedia.ProtoReflect.Descriptor instead.
func (*SyncMedia) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{13}
}

func (x *SyncMedia) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncMedia) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *SyncMedia) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *SyncMedia) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SyncMedia) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *SyncMedia) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SyncMedia) GetInlineData() []byte {
	if x != nil {
		return x.InlineData
	}
	return nil
}

func (x *SyncMedia) GetBlobKey() string {
	if x != nil {
		return x.BlobKey
	}
	return ""
}

func (x *SyncMedia) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SyncMedia) GetSourceMediaId() string {
	if x != nil {
		return x.SourceMediaId
	}
	return ""
}

func (x *SyncMedia) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *SyncMedia) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// SyncContextEntry is one content collection as the recipe declares it: the
// name its items are grouped under, the point it occupies in the project's
// context space, the governance resolved for that point, and which side owns
// it. Together the entries are the "context" content type — the project's
// declared structure and governance, carried in the push transaction rather
// than uploaded beside it.
//
// PERSISTED IDENTIFIERS. `name` and every value in `coordinates` become
// identifiers on the server: items are linked to a collection by name, and the
// coordinates are stored as the point the governance was resolved at. Renaming
// a collection in the recipe therefore does not rename it on the server — it
// declares a new one and leaves the old reported-but-undeclared.
type SyncContextEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the collection name from `collections[].name`. Non-empty: an
	// unnamed bare entry declares no collection and is not carried here.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Coordinates is the point the collection's `channel:` resolves to — the
	// profile on the product axis and the channel it names. Slugs, never concept
	// references.
	Coordinates map[string]string `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Channel is the collection's value on the one axis the framework reads for
	// itself (core/project.ChannelAxis), resolved by the client. It selects the
	// matching override inside the voice profile.
	Channel string `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	// VoiceProfile is the NAME of the voice profile governing this collection —
	// the linkage key the workspace brand hub upserts by. Empty when the
	// collection's point binds no voice.
	VoiceProfile string `protobuf:"bytes,4,opt,name=voice_profile,json=voiceProfile,proto3" json:"voice_profile,omitempty"`
	// VoiceProfileJson is the authored content of that profile, so the push
	// carries the governance itself and not merely a reference to one the server
	// may not hold. Sent once per distinct profile name in a push; later entries
	// naming the same profile carry only the name. Empty on a --no-brand push,
	// which reduces the entry to structure without governance.
	VoiceProfileJson []byte `protobuf:"bytes,5,opt,name=voice_profile_json,json=voiceProfileJson,proto3" json:"voice_profile_json,omitempty"`
	// Owner is "recipe" or "workspace" (see above).
	Owner string `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	// ContentHash is the entry's own hash, over the fields above. The server
	// stores it and compares it: an entry whose hash is unchanged is not
	// rewritten, so a re-push of an unedited recipe does not churn the row.
	ContentHash string `protobuf:"bytes,7,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// Preview is where this collection's strings can be read in place — the
	// component explorer or running site that shows them as a reader sees them.
	// A repository fact the server cannot derive, so it travels with the
	// collection's other declared facts. Absent when the collection declares
	// none, which is how a reviewer decides to offer document reading only.
	Preview       *SyncPreviewSource `protobuf:"bytes,8,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncContextEntry) Reset() {
	*x = SyncContextEntry{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncContextEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncContextEntry) ProtoMessage() {}

func (x *SyncContextEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncContextEntry.ProtoReflect.Descriptor instead.
func (*SyncContextEntry) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{14}
}

func (x *SyncContextEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyncContextEntry) GetCoordinates() map[string]string {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *SyncContextEntry) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SyncContextEntry) GetVoiceProfile() string {
	if x != nil {
		return x.VoiceProfile
	}
	return ""
}

func (x *SyncContextEntry) GetVoiceProfileJson() []byte {
	if x != nil {
		return x.VoiceProfileJson
	}
	return nil
}

func (x *SyncContextEntry) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SyncContextEntry) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *SyncContextEntry) GetPreview() *SyncPreviewSource {
	if x != nil {
		return x.Preview
	}
	return nil
}

// SyncPreviewSource is a place a collection's strings can be seen in situ.
//
// The kinds differ in how a view is FOUND, not in how it renders: a Storybook
// publishes an index that maps components to stories, while a running site is
// addressed by route. What they share is the runtime bridge that pushes the
// reviewer's translations into the page, which belongs to the i18n runtime and
// not to any one host — so the kind is carried, and a host a client does not
// recognise offers no in-context reading rather than a guess.
type SyncPreviewSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind names how to resolve a view. "storybook" is the one implemented.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// URL is the root of the preview host — the published Storybook, the running
	// site — without a trailing view path.
	Url           string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPreviewSource) Reset() {
	*x = SyncPreviewSource{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPreviewSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPreviewSource) ProtoMessage() {}

func (x *SyncPreviewSource) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPreviewSource.ProtoReflect.Descriptor instead.
func (*SyncPreviewSource) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{15}
}

func (x *SyncPreviewSource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SyncPreviewSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SyncItemMeta struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Format   string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`     // "json", "xliff2", "markdown" — declared, not guessed
	Encoding string                 `protobuf:"bytes,3,opt,name=encoding,proto3" json:"encoding,omitempty"` // "utf-8"
	// Collection names the SyncContextEntry this item belongs to — the recipe
	// collection whose glob claims the item's path. Empty when no collection
	// claims it, which is not an error: an ad-hoc file syncs ungrouped and the
	// project's default point governs it.
	Collection     string            `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	BlockIndexJson string            `protobuf:"bytes,5,opt,name=block_index_json,json=blockIndexJson,proto3" json:"block_index_json,omitempty"`
	PreviewHtml    string            `protobuf:"bytes,6,opt,name=preview_html,json=previewHtml,proto3" json:"preview_html,omitempty"`
	SourceLanguage string            `protobuf:"bytes,7,opt,name=source_language,json=sourceLanguage,proto3" json:"source_language,omitempty"`
	ConnectorData  map[string]string `protobuf:"bytes,8,rep,name=connector_data,json=connectorData,proto3" json:"connector_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncItemMeta) Reset() {
	*x = SyncItemMeta{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncItemMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncItemMeta) ProtoMessage() {}

func (x *SyncItemMeta) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncItemMeta.ProtoReflect.Descriptor instead.
func (*SyncItemMeta) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{16}
}

func (x *SyncItemMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyncItemMeta) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SyncItemMeta) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *SyncItemMeta) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SyncItemMeta) GetBlockIndexJson() string {
	if x != nil {
		return x.BlockIndexJson
	}
	return ""
}

func (x *SyncItemMeta) GetPreviewHtml() string {
	if x != nil {
		return x.PreviewHtml
	}
	return ""
}

func (x *SyncItemMeta) GetSourceLanguage() string {
	if x != nil {
		return x.SourceLanguage
	}
	return ""
}

func (x *SyncItemMeta) GetConnectorData() map[string]string {
	if x != nil {
		return x.ConnectorData
	}
	return nil
}

type SyncPullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	ContentTypes  []string               `protobuf:"bytes,5,rep,name=content_types,json=contentTypes,proto3" json:"content_types,omitempty"` // filter by type (empty = all)
	Locales       []string               `protobuf:"bytes,6,rep,name=locales,proto3" json:"locales,omitempty"`                               // filter by locale (empty = all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPullRequest) Reset() {
	*x = SyncPullRequest{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPullRequest) ProtoMessage() {}

func (x *SyncPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPullRequest.ProtoReflect.Descriptor instead.
func (*SyncPullRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{17}
}

func (x *SyncPullRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SyncPullRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *SyncPullRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *SyncPullRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SyncPullRequest) GetContentTypes() []string {
	if x != nil {
		return x.ContentTypes
	}
	return nil
}

func (x *SyncPullRequest) GetLocales() []string {
	if x != nil {
		return x.Locales
	}
	return nil
}

type SyncPullResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Cursor  int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasMore bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// Mixed content types in a single response.
	Blocks        []*SyncBlock       `protobuf:"bytes,10,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Terms         []*SyncTerm        `protobuf:"bytes,11,rep,name=terms,proto3" json:"terms,omitempty"`
	MemoryEntries []*SyncMemoryEntry `protobuf:"bytes,12,rep,name=memory_entries,json=memoryEntries,proto3" json:"memory_entries,omitempty"`
	Media         []*SyncMedia       `protobuf:"bytes,13,rep,name=media,proto3" json:"media,omitempty"`
	// The project's collections, each carrying its owner. A recipe-owned entry
	// is descriptive on this path — the client reads it and leaves the local
	// governance alone, because kapi.yaml is the authority for it. A
	// workspace-owned entry is the one a pull may act on.
	Contexts []*SyncContextEntry `protobuf:"bytes,14,rep,name=contexts,proto3" json:"contexts,omitempty"`
	// The server's freshness ref for this stream as of this page, so a pull
	// refreshes what the next write must assert without a second round trip.
	Ref           *SyncRef `protobuf:"bytes,15,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPullResponse) Reset() {
	*x = SyncPullResponse{}
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPullResponse) ProtoMessage() {}

func (x *SyncPullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_sync_v1_sync_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPullResponse.ProtoReflect.Descriptor instead.
func (*SyncPullResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_sync_v1_sync_proto_rawDescGZIP(), []int{18}
}

func (x *SyncPullResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *SyncPullResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SyncPullResponse) GetBlocks() []*SyncBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *SyncPullResponse) GetTerms() []*SyncTerm {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *SyncPullResponse) GetMemoryEntries() []*SyncMemoryEntry {
	if x != nil {
		return x.MemoryEntries
	}
	return nil
}

func (x *SyncPullResponse) GetMedia() []*SyncMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *SyncPullResponse) GetContexts() []*SyncContextEntry {
	if x != nil {
		return x.Contexts
	}
	return nil
}

func (x *SyncPullResponse) GetRef() *SyncRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

var File_core_proto_sync_v1_sync_proto protoreflect.FileDescriptor

const file_core_proto_sync_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x1dcore/proto/sync/v1/sync.proto\x12\x0fneokapi.sync.v1\x1a#core/proto/content/v1/content.proto\"q\n" +
	"\aSyncRef\x12\x18\n" +
	"\acontent\x18\x01 \x01(\x03R\acontent\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x14\n" +
	"\x05terms\x18\x03 \x01(\tR\x05terms\x12\x1c\n" +
	"\tdecisions\x18\x04 \x01(\tR\tdecisions\"\x9b\x03\n" +
	"\fSyncPushInit\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12#\n" +
	"\rcontent_types\x18\x03 \x03(\tR\fcontentTypes\x12N\n" +
	"\vitem_hashes\x18\x04 \x03(\v2-.neokapi.sync.v1.SyncPushInit.ItemHashesEntryR\n" +
	"itemHashes\x12\x1b\n" +
	"\troot_hash\x18\x05 \x01(\tR\brootHash\x12\x1d\n" +
	"\n" +
	"terms_hash\x18\x06 \x01(\tR\ttermsHash\x12\x1f\n" +
	"\vmemory_hash\x18\a \x01(\tR\n" +
	"memoryHash\x12!\n" +
	"\fcontext_hash\x18\b \x01(\tR\vcontextHash\x12 \n" +
	"\vcollections\x18\t \x03(\tR\vcollections\x1a=\n" +
	"\x0fItemHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x03\n" +
	"\x14SyncPushInitResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rchanged_items\x18\x03 \x03(\tR\fchangedItems\x12#\n" +
	"\rdeleted_items\x18\x04 \x03(\tR\fdeletedItems\x12\x1b\n" +
	"\tnew_items\x18\x05 \x03(\tR\bnewItems\x12#\n" +
	"\rterms_changed\x18\x06 \x01(\bR\ftermsChanged\x12%\n" +
	"\x0ememory_changed\x18\a \x01(\bR\rmemoryChanged\x120\n" +
	"\x14unchanged_item_count\x18\b \x01(\x05R\x12unchangedItemCount\x12'\n" +
	"\x0fcontext_changed\x18\t \x01(\bR\x0econtextChanged\x125\n" +
	"\x16undeclared_collections\x18\n" +
	" \x03(\tR\x15undeclaredCollections\x12*\n" +
	"\x03ref\x18\v \x01(\v2\x18.neokapi.sync.v1.SyncRefR\x03ref\"\xdb\x01\n" +
	"\fSyncItemDiff\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12Q\n" +
	"\fblock_hashes\x18\x03 \x03(\v2..neokapi.sync.v1.SyncItemDiff.BlockHashesEntryR\vblockHashes\x1a>\n" +
	"\x10BlockHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x01\n" +
	"\x14SyncItemDiffResponse\x12\x16\n" +
	"\x06needed\x18\x01 \x03(\tR\x06needed\x12\x18\n" +
	"\adeleted\x18\x02 \x03(\tR\adeleted\x12\x1c\n" +
	"\tconflicts\x18\x03 \x03(\tR\tconflicts\x12\x1d\n" +
	"\n" +
	"chunk_urls\x18\x04 \x03(\tR\tchunkUrls\x12\x1c\n" +
	"\ttransport\x18\x05 \x01(\tR\ttransport\"\xad\x04\n" +
	"\fSyncManifest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x121\n" +
	"\x06chunks\x18\x04 \x03(\v2\x19.neokapi.sync.v1.ChunkRefR\x06chunks\x123\n" +
	"\x05items\x18\x05 \x03(\v2\x1d.neokapi.sync.v1.SyncItemMetaR\x05items\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12%\n" +
	"\x0eworkspace_slug\x18\a \x01(\tR\rworkspaceSlug\x12!\n" +
	"\fconnector_id\x18\b \x01(\tR\vconnectorId\x12D\n" +
	"\acontext\x18\t \x03(\v2*.neokapi.sync.v1.SyncManifest.ContextEntryR\acontext\x12=\n" +
	"\bcontexts\x18\n" +
	" \x03(\v2!.neokapi.sync.v1.SyncContextEntryR\bcontexts\x12;\n" +
	"\fexpected_ref\x18\v \x01(\v2\x18.neokapi.sync.v1.SyncRefR\vexpectedRef\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\bChunkRef\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12!\n" +
	"\frecord_count\x18\x04 \x01(\x05R\vrecordCount\x12\x1b\n" +
	"\tbyte_size\x18\x05 \x01(\x03R\bbyteSize\"\xb1\x02\n" +
	"\tSyncChunk\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12!\n" +
	"\frecord_count\x18\x02 \x01(\x05R\vrecordCount\x122\n" +
	"\x06blocks\x18\n" +
	" \x03(\v2\x1a.neokapi.sync.v1.SyncBlockR\x06blocks\x12/\n" +
	"\x05terms\x18\v \x03(\v2\x19.neokapi.sync.v1.SyncTermR\x05terms\x12G\n" +
	"\x0ememory_entries\x18\f \x03(\v2 .neokapi.sync.v1.SyncMemoryEntryR\rmemoryEntries\x120\n" +
	"\x05media\x18\r \x03(\v2\x1a.neokapi.sync.v1.SyncMediaR\x05media\"\xe7\b\n" +
	"\tSyncBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\"\n" +
	"\ftranslatable\x18\x06 \x01(\bR\ftranslatable\x12:\n" +
	"\x06source\x18\a \x03(\v2\".neokapi.content.v1.SegmentMessageR\x06source\x12\x1f\n" +
	"\vsource_text\x18\b \x01(\tR\n" +
	"sourceText\x12A\n" +
	"\atargets\x18\t \x03(\v2'.neokapi.sync.v1.SyncBlock.TargetsEntryR\atargets\x12J\n" +
	"\n" +
	"properties\x18\n" +
	" \x03(\v2*.neokapi.sync.v1.SyncBlock.PropertiesEntryR\n" +
	"properties\x12)\n" +
	"\x10annotations_json\x18\v \x01(\fR\x0fannotationsJson\x12#\n" +
	"\rskeleton_json\x18\f \x01(\fR\fskeletonJson\x12/\n" +
	"\x13preserve_whitespace\x18\r \x01(\bR\x12preserveWhitespace\x12*\n" +
	"\x11display_hint_json\x18\x0e \x01(\fR\x0fdisplayHintJson\x12(\n" +
	"\x10content_ref_json\x18\x0f \x01(\fR\x0econtentRefJson\x12T\n" +
	"\x0econnector_data\x18\x10 \x03(\v2-.neokapi.sync.v1.SyncBlock.ConnectorDataEntryR\rconnectorData\x12#\n" +
	"\rexpected_hash\x18\x11 \x01(\tR\fexpectedHash\x12!\n" +
	"\fcontent_hash\x18\x12 \x01(\tR\vcontentHash\x12>\n" +
	"\boverlays\x18\x13 \x03(\v2\".neokapi.content.v1.OverlayMessageR\boverlays\x12#\n" +
	"\rsource_locale\x18\x14 \x01(\tR\fsourceLocale\x12\x1f\n" +
	"\vis_referent\x18\x15 \x01(\bR\n" +
	"isReferent\x1a\\\n" +
	"\fTargetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .neokapi.sync.v1.SyncSegmentListR\x05value:\x028\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12ConnectorDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x0fSyncSegmentList\x12>\n" +
	"\bsegments\x18\x01 \x03(\v2\".neokapi.content.v1.SegmentMessageR\bsegments\"\xb6\x03\n" +
	"\bSyncTerm\x12\x1d\n" +
	"\n" +
	"concept_id\x18\x01 \x01(\tR\tconceptId\x12\x1f\n" +
	"\vsource_term\x18\x02 \x01(\tR\n" +
	"sourceTerm\x12#\n" +
	"\rsource_locale\x18\x03 \x01(\tR\fsourceLocale\x12H\n" +
	"\ftranslations\x18\x04 \x03(\v2$.neokapi.sync.v1.SyncTermTranslationR\ftranslations\x12\x1e\n" +
	"\n" +
	"definition\x18\x05 \x01(\tR\n" +
	"definition\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\x12I\n" +
	"\n" +
	"properties\x18\a \x03(\v2).neokapi.sync.v1.SyncTerm.PropertiesEntryR\n" +
	"properties\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12!\n" +
	"\fcontent_hash\x18\t \x01(\tR\vcontentHash\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x13SyncTermTranslation\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x12\x12\n" +
	"\x04term\x18\x02 \x01(\tR\x04term\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x8f\x03\n" +
	"\x0fSyncMemoryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rsource_locale\x18\x02 \x01(\tR\fsourceLocale\x12#\n" +
	"\rtarget_locale\x18\x03 \x01(\tR\ftargetLocale\x12\x1f\n" +
	"\vsource_text\x18\x04 \x01(\tR\n" +
	"sourceText\x12\x1f\n" +
	"\vtarget_text\x18\x05 \x01(\tR\n" +
	"targetText\x12\x16\n" +
	"\x06origin\x18\x06 \x01(\tR\x06origin\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\x12P\n" +
	"\n" +
	"properties\x18\b \x03(\v20.neokapi.sync.v1.SyncMemoryEntry.PropertiesEntryR\n" +
	"properties\x12!\n" +
	"\fcontent_hash\x18\t \x01(\tR\vcontentHash\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x03\n" +
	"\tSyncMedia\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x19\n" +
	"\balt_text\x18\x05 \x01(\tR\aaltText\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x1f\n" +
	"\vinline_data\x18\n" +
	" \x01(\fR\n" +
	"inlineData\x12\x19\n" +
	"\bblob_key\x18\v \x01(\tR\ablobKey\x12\x16\n" +
	"\x06locale\x18\f \x01(\tR\x06locale\x12&\n" +
	"\x0fsource_media_id\x18\r \x01(\tR\rsourceMediaId\x12J\n" +
	"\n" +
	"properties\x18\x0e \x03(\v2*.neokapi.sync.v1.SyncMedia.PropertiesEntryR\n" +
	"properties\x12!\n" +
	"\fcontent_hash\x18\x0f \x01(\tR\vcontentHash\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x03\n" +
	"\x10SyncContextEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12T\n" +
	"\vcoordinates\x18\x02 \x03(\v22.neokapi.sync.v1.SyncContextEntry.CoordinatesEntryR\vcoordinates\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12#\n" +
	"\rvoice_profile\x18\x04 \x01(\tR\fvoiceProfile\x12,\n" +
	"\x12voice_profile_json\x18\x05 \x01(\fR\x10voiceProfileJson\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12!\n" +
	"\fcontent_hash\x18\a \x01(\tR\vcontentHash\x12<\n" +
	"\apreview\x18\b \x01(\v2\".neokapi.sync.v1.SyncPreviewSourceR\apreview\x1a>\n" +
	"\x10CoordinatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x11SyncPreviewSource\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x87\x03\n" +
	"\fSyncItemMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1a\n" +
	"\bencoding\x18\x03 \x01(\tR\bencoding\x12\x1e\n" +
	"\n" +
	"collection\x18\x04 \x01(\tR\n" +
	"collection\x12(\n" +
	"\x10block_index_json\x18\x05 \x01(\tR\x0eblockIndexJson\x12!\n" +
	"\fpreview_html\x18\x06 \x01(\tR\vpreviewHtml\x12'\n" +
	"\x0fsource_language\x18\a \x01(\tR\x0esourceLanguage\x12W\n" +
	"\x0econnector_data\x18\b \x03(\v20.neokapi.sync.v1.SyncItemMeta.ConnectorDataEntryR\rconnectorData\x1a@\n" +
	"\x12ConnectorDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\x0fSyncPullRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12#\n" +
	"\rcontent_types\x18\x05 \x03(\tR\fcontentTypes\x12\x18\n" +
	"\alocales\x18\x06 \x03(\tR\alocales\"\x90\x03\n" +
	"\x10SyncPullResponse\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x122\n" +
	"\x06blocks\x18\n" +
	" \x03(\v2\x1a.neokapi.sync.v1.SyncBlockR\x06blocks\x12/\n" +
	"\x05terms\x18\v \x03(\v2\x19.neokapi.sync.v1.SyncTermR\x05terms\x12G\n" +
	"\x0ememory_entries\x18\f \x03(\v2 .neokapi.sync.v1.SyncMemoryEntryR\rmemoryEntries\x120\n" +
	"\x05media\x18\r \x03(\v2\x1a.neokapi.sync.v1.SyncMediaR\x05media\x12=\n" +
	"\bcontexts\x18\x0e \x03(\v2!.neokapi.sync.v1.SyncContextEntryR\bcontexts\x12*\n" +
	"\x03ref\x18\x0f \x01(\v2\x18.neokapi.sync.v1.SyncRefR\x03refB6Z4github.com/neokapi/neokapi/core/proto/sync/v1;syncv1b\x06proto3"

var (
	file_core_proto_sync_v1_sync_proto_rawDescOnce sync.Once
	file_core_proto_sync_v1_sync_proto_rawDescData []byte
)

func file_core_proto_sync_v1_sync_proto_rawDescGZIP() []byte {
	file_core_proto_sync_v1_sync_proto_rawDescOnce.Do(func() {
		file_core_proto_sync_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_sync_v1_sync_proto_rawDesc), len(file_core_proto_sync_v1_sync_proto_rawDesc)))
	})
	return file_core_proto_sync_v1_sync_proto_rawDescData
}

var file_core_proto_sync_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_core_proto_sync_v1_sync_proto_goTypes = []any{
	(*SyncRef)(nil),              // 0: neokapi.sync.v1.SyncRef
	(*SyncPushInit)(nil),         // 1: neokapi.sync.v1.SyncPushInit
	(*SyncPushInitResponse)(nil), // 2: neokapi.sync.v1.SyncPushInitResponse
	(*SyncItemDiff)(nil),         // 3: neokapi.sync.v1.SyncItemDiff
	(*SyncItemDiffResponse)(nil), // 4: neokapi.sync.v1.SyncItemDiffResponse
	(*SyncManifest)(nil),         // 5: neokapi.sync.v1.SyncManifest
	(*ChunkRef)(nil),             // 6: neokapi.sync.v1.ChunkRef
	(*SyncChunk)(nil),            // 7: neokapi.sync.v1.SyncChunk
	(*SyncBlock)(nil),            // 8: neokapi.sync.v1.SyncBlock
	(*SyncSegmentList)(nil),      // 9: neokapi.sync.v1.SyncSegmentList
	(*SyncTerm)(nil),             // 10: neokapi.sync.v1.SyncTerm
	(*SyncTermTranslation)(nil),  // 11: neokapi.sync.v1.SyncTermTranslation
	(*SyncMemoryEntry)(nil),      // 12: neokapi.sync.v1.SyncMemoryEntry
	(*SyncMedia)(nil),            // 13: neokapi.sync.v1.SyncMedia
	(*SyncContextEntry)(nil),     // 14: neokapi.sync.v1.SyncContextEntry
	(*SyncPreviewSource)(nil),    // 15: neokapi.sync.v1.SyncPreviewSource
	(*SyncItemMeta)(nil),         // 16: neokapi.sync.v1.SyncItemMeta
	(*SyncPullRequest)(nil),      // 17: neokapi.sync.v1.SyncPullRequest
	(*SyncPullResponse)(nil),     // 18: neokapi.sync.v1.SyncPullResponse
	nil,                          // 19: neokapi.sync.v1.SyncPushInit.ItemHashesEntry
	nil,                          // 20: neokapi.sync.v1.SyncItemDiff.BlockHashesEntry
	nil,                          // 21: neokapi.sync.v1.SyncManifest.ContextEntry
	nil,                          // 22: neokapi.sync.v1.SyncBlock.TargetsEntry
	nil,                          // 23: neokapi.sync.v1.SyncBlock.PropertiesEntry
	nil,                          // 24: neokapi.sync.v1.SyncBlock.ConnectorDataEntry
	nil,                          // 25: neokapi.sync.v1.SyncTerm.PropertiesEntry
	nil,                          // 26: neokapi.sync.v1.SyncMemoryEntry.PropertiesEntry
	nil,                          // 27: neokapi.sync.v1.SyncMedia.PropertiesEntry
	nil,                          // 28: neokapi.sync.v1.SyncContextEntry.CoordinatesEntry
	nil,                          // 29: neokapi.sync.v1.SyncItemMeta.ConnectorDataEntry
	(*v1.SegmentMessage)(nil),    // 30: neokapi.content.v1.SegmentMessage
	(*v1.OverlayMessage)(nil),    // 31: neokapi.content.v1.OverlayMessage
}
var file_core_proto_sync_v1_sync_proto_depIdxs = []int32{
	19, // 0: neokapi.sync.v1.SyncPushInit.item_hashes:type_name -> neokapi.sync.v1.SyncPushInit.ItemHashesEntry
	0,  // 1: neokapi.sync.v1.SyncPushInitResponse.ref:type_name -> neokapi.sync.v1.SyncRef
	20, // 2: neokapi.sync.v1.SyncItemDiff.block_hashes:type_name -> neokapi.sync.v1.SyncItemDiff.BlockHashesEntry
	6,  // 3: neokapi.sync.v1.SyncManifest.chunks:type_name -> neokapi.sync.v1.ChunkRef
	16, // 4: neokapi.sync.v1.SyncManifest.items:type_name -> neokapi.sync.v1.SyncItemMeta
	21, // 5: neokapi.sync.v1.SyncManifest.context:type_name -> neokapi.sync.v1.SyncManifest.ContextEntry
	14, // 6: neokapi.sync.v1.SyncManifest.contexts:type_name -> neokapi.sync.v1.SyncContextEntry
	0,  // 7: neokapi.sync.v1.SyncManifest.expected_ref:type_name -> neokapi.sync.v1.SyncRef
	8,  // 8: neokapi.sync.v1.SyncChunk.blocks:type_name -> neokapi.sync.v1.SyncBlock
	10, // 9: neokapi.sync.v1.SyncChunk.terms:type_name -> neokapi.sync.v1.SyncTerm
	12, // 10: neokapi.sync.v1.SyncChunk.memory_entries:type_name -> neokapi.sync.v1.SyncMemoryEntry
	13, // 11: neokapi.sync.v1.SyncChunk.media:type_name -> neokapi.sync.v1.SyncMedia
	30, // 12: neokapi.sync.v1.SyncBlock.source:type_name -> neokapi.content.v1.SegmentMessage
	22, // 13: neokapi.sync.v1.SyncBlock.targets:type_name -> neokapi.sync.v1.SyncBlock.TargetsEntry
	23, // 14: neokapi.sync.v1.SyncBlock.properties:type_name -> neokapi.sync.v1.SyncBlock.PropertiesEntry
	24, // 15: neokapi.sync.v1.SyncBlock.connector_data:type_name -> neokapi.sync.v1.SyncBlock.ConnectorDataEntry
	31, // 16: neokapi.sync.v1.SyncBlock.overlays:type_name -> neokapi.content.v1.OverlayMessage
	30, // 17: neokapi.sync.v1.SyncSegmentList.segments:type_name -> neokapi.content.v1.SegmentMessage
	11, // 18: neokapi.sync.v1.SyncTerm.translations:type_name -> neokapi.sync.v1.SyncTermTranslation
	25, // 19: neokapi.sync.v1.SyncTerm.properties:type_name -> neokapi.sync.v1.SyncTerm.PropertiesEntry
	26, // 20: neokapi.sync.v1.SyncMemoryEntry.properties:type_name -> neokapi.sync.v1.SyncMemoryEntry.PropertiesEntry
	27, // 21: neokapi.sync.v1.SyncMedia.properties:type_name -> neokapi.sync.v1.SyncMedia.PropertiesEntry
	28, // 22: neokapi.sync.v1.SyncContextEntry.coordinates:type_name -> neokapi.sync.v1.SyncContextEntry.CoordinatesEntry
	15, // 23: neokapi.sync.v1.SyncContextEntry.preview:type_name -> neokapi.sync.v1.SyncPreviewSource
	29, // 24: neokapi.sync.v1.SyncItemMeta.connector_data:type_name -> neokapi.sync.v1.SyncItemMeta.ConnectorDataEntry
	8,  // 25: neokapi.sync.v1.SyncPullResponse.blocks:type_name -> neokapi.sync.v1.SyncBlock
	10, // 26: neokapi.sync.v1.SyncPullResponse.terms:type_name -> neokapi.sync.v1.SyncTerm
	12, // 27: neokapi.sync.v1.SyncPullResponse.memory_entries:type_name -> neokapi.sync.v1.SyncMemoryEntry
	13, // 28: neokapi.sync.v1.SyncPullResponse.media:type_name -> neokapi.sync.v1.SyncMedia
	14, // 29: neokapi.sync.v1.SyncPullResponse.contexts:type_name -> neokapi.sync.v1.SyncContextEntry
	0,  // 30: neokapi.sync.v1.SyncPullResponse.ref:type_name -> neokapi.sync.v1.SyncRef
	9,  // 31: neokapi.sync.v1.SyncBlock.TargetsEntry.value:type_name -> neokapi.sync.v1.SyncSegmentList
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_core_proto_sync_v1_sync_proto_init() }
func file_core_proto_sync_v1_sync_proto_init() {
	if File_core_proto_sync_v1_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_sync_v1_sync_proto_rawDesc), len(file_core_proto_sync_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_sync_v1_sync_proto_goTypes,
		DependencyIndexes: file_core_proto_sync_v1_sync_proto_depIdxs,
		MessageInfos:      file_core_proto_sync_v1_sync_proto_msgTypes,
	}.Build()
	File_core_proto_sync_v1_sync_proto = out.File
	file_core_proto_sync_v1_sync_proto_goTypes = nil
	file_core_proto_sync_v1_sync_proto_depIdxs = nil
}
