/**
 * Emit the W3C HTML5 translatability tables as committed JSON for the Go readers.
 *
 * `packages/i18n-react/src/plugin/defaults.ts` is the single definition. It is
 * TypeScript because the JSX transform that first needed it is; the markdown and
 * mdx readers need the same answers about the same elements, and two hand-kept
 * copies of a spec table drift the moment one side adds an element.
 *
 * Run `make generate-translatability` to refresh, `-check` to gate on drift.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  componentTranslatableAttributes,
  containerElements,
  htmlTranslatableAttributes,
  inlineElements,
  nonTranslatableElements,
  translatableElements,
} from "../packages/i18n-react/src/plugin/defaults.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "core", "translatability", "data", "w3c.json");

const sorted = (s: Set<string>) => [...s].sort();

const table = {
  // Regenerated by scripts/gen-translatability.ts — see the header there.
  _generated: "scripts/gen-translatability.ts from packages/i18n-react/src/plugin/defaults.ts",
  nonTranslatableElements: sorted(nonTranslatableElements),
  translatableElements: sorted(translatableElements),
  inlineElements: sorted(inlineElements),
  containerElements: sorted(containerElements),
  htmlTranslatableAttributes: sorted(htmlTranslatableAttributes),
  componentTranslatableAttributes: sorted(componentTranslatableAttributes),
};

const rendered = JSON.stringify(table, null, 2) + "\n";

if (process.argv.includes("-check")) {
  let current: string;
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    console.error(`translatability: ${OUT} is missing — run 'make generate-translatability'`);
    process.exit(1);
  }
  if (current !== rendered) {
    console.error(
      "translatability: the committed W3C table is stale relative to " +
        "packages/i18n-react/src/plugin/defaults.ts.\n" +
        "Run 'make generate-translatability' and commit the result.",
    );
    process.exit(1);
  }
  console.log(`translatability: ${OUT} is current`);
} else {
  writeFileSync(OUT, rendered);
  const counts = Object.entries(table)
    .filter(([, v]) => Array.isArray(v))
    .map(([k, v]) => `${k}=${(v as string[]).length}`)
    .join(" ");
  console.log(`translatability: wrote ${OUT} (${counts})`);
}
