#!/usr/bin/env bash
#
# Regenerate a Docusaurus site's qps (pseudo-locale) translations.
#
# qps is the runtime-correctness probe: every string that goes through the i18n
# machinery renders mangled (▒ Ĥöŵ îţ ŵöŕķš ▒), so one URL shows which text is
# translatable and which is hardcoded. It is not project content and not a
# target language in the recipe — the posture `make l10n-pseudo` already takes
# for the catalog-driven surfaces.
#
# TWO TIERS, and they are separated because only one can run in CI.
#
#   CONTENT (--content-only, the default in `make l10n-pseudo`)
#     The docs pages themselves, pseudo-translated with kapi into
#     i18n/qps/docusaurus-plugin-content-docs/current/. Needs kapi and nothing
#     else, so it rides the l10n pipeline and the autofix bot keeps it current
#     as the docs change. Without that, a page added after the last manual run
#     falls back to English in the pseudo build — which reads as "this string is
#     not translatable" when it only means "not regenerated". A probe that lies
#     is worse than no probe.
#
#   THEME (--with-theme)
#     navbar, footer, code.json, current.json. These come from
#     `docusaurus write-translations`, which needs the site's own node_modules,
#     and bowrain/web/docs is deliberately outside the pnpm workspace, so the
#     l10n CI job cannot install them. The docs workflows run this tier before
#     each site build; run it by hand for a local preview. Everything it writes
#     under the site's i18n/qps/ tree is gitignored and never committed.
#
# The theme tier also needs a fix-up: a Docusaurus translation file is
# {"key": {"message": …, "description": …}} and only `message` is shown to a
# reader. `description` is authoring metadata that write-translations
# regenerates verbatim, so mangling it makes every future diff unreadable.
# pseudo-translate has no key-path flag, so the descriptions are restored after.
#
# Usage:
#     scripts/pseudo-docs-i18n.sh bowrain/web/docs                # content only
#     scripts/pseudo-docs-i18n.sh bowrain/web/docs --with-theme   # + theme JSON
set -euo pipefail

site="${1:?usage: $0 <docusaurus-site-dir> [--with-theme]}"
mode="${2:---content-only}"
repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root/$site"

# Which kapi generates the locale. A local run builds one into bin/; CI installs
# a pinned release with setup-kapi and puts it on PATH, so the published docs are
# generated by a kapi someone released rather than by whatever the working tree
# happens to compile to. That is also what makes the site's trigger paths
# honest: the output is then a function of the docs, the recipe, the terms and a
# version, none of which is "the entire Go module graph".
kapi="${KAPI_BIN:-}"
if [ -z "$kapi" ]; then
  if [ -x "$repo_root/bin/kapi" ]; then
    kapi="$repo_root/bin/kapi"
  else
    kapi=$(command -v kapi || true)
  fi
fi
[ -n "$kapi" ] && [ -x "$kapi" ] || {
  echo "::error::no kapi binary — build one with 'make build' or install one with setup-kapi"
  exit 1
}
echo "==> generating with $("$kapi" version 2>/dev/null | head -1) at $kapi"

export KAPI_NO_PROJECT=1 KAPI_TELEMETRY=0

# ── content ─────────────────────────────────────────────────────────────────
out="i18n/qps/docusaurus-plugin-content-docs/current"
rm -rf "$out"

n=0
while IFS= read -r f; do
  rel="${f#docs/}"
  mkdir -p "$out/$(dirname "$rel")"
  # -p binds the recipe, which is where the reader CONFIGURATION lives:
  #
  #     mdx:
  #       config:
  #         translateFrontMatter: true
  #         frontMatterKeys: [title, description, sidebar_label]
  #
  # Without it the frontmatter passes through verbatim, so every sidebar entry,
  # page title and meta description renders English in the pseudo build and
  # reads as "not translatable" when it means "never offered". KAPI_NO_PROJECT
  # stays set: it turns off the upward-walk DISCOVERY, and an explicit -p still
  # wins, so this binds deliberately rather than by cwd.
  #
  # -f mdx stays too, for BOTH extensions. It names the format, which -p would
  # also supply, but it does so independently of the collection globs: a .md
  # read by the MARKDOWN reader takes a multi-line <Component …/> for a
  # paragraph of prose and translates the tag and attribute names, and 33 pages
  # stopped compiling that way. The recipe's own note says the same thing.
  "$kapi" pseudo-translate "$f" --target-lang qps -p "$repo_root/kapi.yaml" \
    -f mdx -o "$out/$rel" -q >/dev/null
  n=$((n + 1))
done < <(find docs -name "*.md" -o -name "*.mdx" | sort)
echo "==> $site: $n pages pseudo-translated into $out"

# ── react components ────────────────────────────────────────────────────────
# Only for a site wired to the transform: it is named by a webpack loader in
# the site's own plugin, and a site without that plugin would build a
# dictionary nothing reads. bowrain/web/docs does not need one — its handful of
# component strings already use <Translate>, so code.json covers them.
if [ -f plugins/neokapi-i18n.mjs ]; then
  echo "==> $site: extracting React components"
  rm -rf i18n-kbf i18n-runtime
  # --config carries the componentMap the loader also reads. They must agree:
  # a component mapped on one side and not the other yields hashes the
  # transform cannot look up, and every string falls back to source.
  vpx neokapi-i18n extract --config i18n-react.config.json \
    --src "src/**/*.{tsx,jsx,ts}" --out i18n-kbf 2>/dev/null | tail -1

  # Each .kbf.json is content like any other, so the same tool that pseudos the
  # docs pages pseudos these — markers and all coming from the recipe.
  while IFS= read -r f; do
    "$kapi" pseudo-translate "$f" --target-lang qps -p "$repo_root/kapi.yaml" \
      -o "$f" -q >/dev/null
  done < <(find i18n-kbf -name '*.kbf.json')

  # Flatten to the dictionary the loader reads at build time.
  vpx neokapi-i18n compile i18n-kbf --locale qps --out i18n-runtime 2>/dev/null | tail -1
  echo "==> $site: React dictionary at i18n-runtime/qps.json"
fi

[ "$mode" = "--with-theme" ] || exit 0

# ── theme ───────────────────────────────────────────────────────────────────
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

echo "==> write-translations --locale qps"
vpx docusaurus write-translations --locale qps >/dev/null

# Only the files write-translations owns; the content tree above is not its.
find i18n/qps -maxdepth 2 -name "*.json" | sort | while read -r f; do
  cp "$f" "$work/pre.json"
  # -p for the recipe's qps tool config, same as the content tier: without it
  # the theme JSON keeps the ▒ markers the recipe turns off, so a page shows
  # bracketed chrome around unbracketed content.
  $kapi pseudo-translate $f --target-lang qps -f json \
    -p $repo_root/kapi.yaml -o $work/post.json -q

  python3 - "$work/pre.json" "$work/post.json" "$f" <<'PY'
import json, sys

src = json.load(open(sys.argv[1]))
out = json.load(open(sys.argv[2]))

restored = 0
for key, val in out.items():
    if isinstance(val, dict) and isinstance(src.get(key), dict) and "description" in src[key]:
        if val.get("description") != src[key]["description"]:
            val["description"] = src[key]["description"]
            restored += 1

with open(sys.argv[3], "w") as fh:
    json.dump(out, fh, indent=2, ensure_ascii=False)
    fh.write("\n")

msgs = sum(1 for v in out.values() if isinstance(v, dict) and "▒" in str(v.get("message", "")))
print(f"    {sys.argv[3]}: {msgs}/{len(out)} messages pseudo-ized, {restored} descriptions restored")
PY
done
