// Command authoringeval measures kapi's authoring surfaces against a
// synthesized corpus.
//
// Three questions, one corpus:
//
//	authoring-checks     Does a voice check find the violations the profile
//	                     declares, and stay quiet on prose that obeys it?
//	voice-infer-quality  Does an inferred draft profile recover the profile the
//	                     corpus was written from?
//	authoring-effect     Does `kapi voice guide` steer an assistant's writing
//	                     toward the profile, rather than just improving it?
//
// Everything is driven through the real kapi binary. Nothing here reimplements
// a check in order to measure it.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// DefaultOut is the dataset the dashboard reads.
const DefaultOut = "web/src/pages/authoring-eval/_authoringeval.json"

// Report is the whole dataset.
type Report struct {
	Note string `json:"_note"`
	// Date is a date and not a timestamp, so a rerun on the same day produces
	// the same bytes and the drift guard stays quiet. Age is computed in the
	// browser from this, never written here.
	Date string `json:"date"`
	// Corpus is disclosed in the data, not only in the prose around it. A
	// reader who downloads this file still learns the material is synthetic.
	Corpus CorpusInfo `json:"corpus"`
	// Checks is authoring-checks: one entry per check measured.
	Checks []CheckAccuracy `json:"checks"`
	// Infer is voice-infer-quality.
	Infer *InferResult `json:"infer,omitempty"`
	// Steer is authoring-effect.
	Steer *SteerResult `json:"steer,omitempty"`
}

// CorpusInfo describes the material every number came from.
type CorpusInfo struct {
	Synthetic  bool           `json:"synthetic"`
	Disclosure string         `json:"disclosure"`
	Docs       int            `json:"docs"`
	OnProfile  int            `json:"onProfile"`
	OffProfile int            `json:"offProfile"`
	Plants     int            `json:"plants"`
	ByMech     map[string]int `json:"plantsByMechanism"`
	Profile    string         `json:"profile"`
	Contrast   string         `json:"contrast"`
	Documents  []Doc          `json:"documents"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "authoringeval:", err)
		os.Exit(1)
	}
}

func run() error {
	var (
		out      = flag.String("out", "", "dataset path (default: "+DefaultOut+" under the repo root)")
		only     = flag.String("only", "", "run one measurement: checks, infer, steer")
		provider = flag.String("provider", "claude-code", "AI provider for the measurements that need one; `none` runs the offline arm alone")
		model    = flag.String("model", "sonnet", "model for the measurements that need one")
		date     = flag.String("date", "", "date to stamp (default: today)")
		keep     = flag.Bool("keep", false, "keep the workspace and print its path")
	)
	flag.Parse()

	root, err := repoRoot()
	if err != nil {
		return err
	}
	bin := findKapi(root)
	if bin == "" {
		return errors.New("no kapi binary: run `make build` first")
	}
	if *date == "" {
		*date = time.Now().UTC().Format("2006-01-02")
	}
	target := *out
	if target == "" {
		target = filepath.Join(root, DefaultOut)
	}

	dir, err := os.MkdirTemp("", "authoringeval-")
	if err != nil {
		return err
	}
	if *keep {
		fmt.Println("workspace:", dir)
	} else {
		defer func() { _ = os.RemoveAll(dir) }()
	}

	ctx := context.Background()
	if err := setupWorkspace(ctx, bin, dir); err != nil {
		return err
	}

	rep := Report{
		Note: "GENERATED by `go run ./scripts/authoringeval`. Do not edit by hand. " +
			"Every number is produced by running the real kapi binary against the corpus recorded here.",
		Date:   *date,
		Corpus: describeCorpus(),
	}

	// A previous dataset is carried forward for whatever this run does not
	// measure, so `-only` narrows the work without shrinking the published
	// result. contexteval learned this the hard way.
	prev := loadPrevious(target)
	if prev != nil {
		rep.Infer, rep.Steer = prev.Infer, prev.Steer
		rep.Checks = prev.Checks
	}

	wants := func(name string) bool { return *only == "" || *only == name }

	if wants("checks") {
		fmt.Fprintln(os.Stderr, "authoring-checks: scoring", len(corpus), "documents")
		offline, err := runOfflineCheck(ctx, bin, dir)
		if err != nil {
			return err
		}
		rep.Checks = []CheckAccuracy{offline}
		reportChecks(offline)
		if *provider == "none" {
			// The offline arm alone, which needs no model and costs nothing.
			// The published LLM row stays as whichever run produced it, rather
			// than being replaced by an absence.
			if prev != nil && len(prev.Checks) > 1 {
				rep.Checks = append(rep.Checks, prev.Checks[1:]...)
				fmt.Fprintf(os.Stderr, "\n%s: kept from the previous run\n", prev.Checks[1].Check)
			}
		} else {
			llm, err := runLLMCheck(ctx, bin, dir, *provider, *model)
			if err != nil {
				return err
			}
			rep.Checks = append(rep.Checks, llm)
			reportChecks(llm)
		}
	}

	if wants("infer") {
		fmt.Fprintln(os.Stderr, "voice-infer-quality: inferring from", len(docsOfKind(onProfile)), "on-profile documents")
		res, err := runInfer(ctx, bin, dir, *provider, *model)
		if err != nil {
			return err
		}
		rep.Infer = res
		reportInfer(res)
	}

	if wants("steer") {
		fmt.Fprintln(os.Stderr, "authoring-effect: writing", len(steerTasks), "documents twice, scoring against two profiles")
		res, err := runSteer(ctx, bin, dir, *provider, *model)
		if err != nil {
			return err
		}
		rep.Steer = res
		reportSteer(res)
	}

	data, err := Marshal(rep)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(target, data, 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", target)
	return nil
}

// Marshal renders the dataset the one way, so the drift guard compares bytes.
func Marshal(r Report) ([]byte, error) {
	b, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

func loadPrevious(path string) *Report {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var r Report
	if json.Unmarshal(raw, &r) != nil {
		return nil
	}
	return &r
}

func describeCorpus() CorpusInfo {
	on, off := docsOfKind(onProfile), docsOfKind(offProfile)
	by := plantsByMechanism()
	total := 0
	for _, n := range by {
		total += n
	}
	return CorpusInfo{
		Synthetic: true,
		Disclosure: "Written for this eval. Two of the three measurements need ground truth no repository carries: " +
			"a profile a person wrote from a known corpus, and prose whose every violation is marked. So the corpus " +
			"was synthesized and the profile written first. What that costs is external validity: these numbers say " +
			"whether the checks find what the profile declares, not how they behave on prose written by someone who " +
			"has never read it.",
		Docs:       len(corpus),
		OnProfile:  len(on),
		OffProfile: len(off),
		Plants:     total,
		ByMech:     by,
		Profile:    referenceProfile,
		Contrast:   contrastProfile,
		Documents:  corpus,
	}
}

func reportChecks(a CheckAccuracy) {
	fmt.Printf("\n%s\n", a.Check)
	if a.Blocked != "" {
		fmt.Printf("  NOT MEASURED: %s\n", a.Blocked)
		return
	}
	fmt.Printf("  recall %.0f%% (%d/%d planted violations found)\n", 100*a.Recall, a.Covered, a.Plants)
	for _, m := range mechanisms() {
		ms := a.ByMechanism[m]
		fmt.Printf("    %-9s %3.0f%% (%d/%d)\n", m, 100*ms.Recall, ms.Covered, ms.Plants)
	}
	fmt.Printf("  false positives: %d finding(s) across %d of %d on-profile documents, where the right answer is silence\n",
		a.CleanFalsePositives, a.CleanDocsWithFindings, a.CleanDocs)
}

func repoRoot() (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	out, err := exec.CommandContext(ctx, "git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		return "", errors.New("not in a git checkout")
	}
	return strings.TrimSpace(string(out)), nil
}

// findKapi prefers this checkout's build, so a run measures this code rather
// than whatever kapi the developer has installed.
func findKapi(root string) string {
	local := filepath.Join(root, "bin", "kapi")
	if _, err := os.Stat(local); err == nil {
		return local
	}
	if p, err := exec.LookPath("kapi"); err == nil {
		return p
	}
	return ""
}
