// Command evalindex builds the data behind /evals: every eval kapi publishes,
// grouped by the question it answers, with the card needed to judge or repeat it.
//
// It is a registry rather than a runner. Each eval has its own harness and its
// own cadence. Some regenerate on every build, some spend model calls and are
// refreshed on demand, and forcing them into one command would mean either
// running the cheap ones rarely or the expensive ones constantly.
//
// What this adds is the thing no individual harness can: a view of what is
// measured, what is measured partially, and what is not measured at all. A gap a
// reader cannot see is a gap they will assume is covered.
//
//	go run ./scripts/evalindex                     # write the cover-page data
//	go run ./scripts/evalindex -out /dev/stdout    # inspect it
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DefaultOut is the committed data the cover page reads.
const DefaultOut = "web/src/pages/evals/_index.json"

func main() {
	out := flag.String("out", DefaultOut, "where to write the index")
	flag.Parse()

	index, err := Build()
	if err != nil {
		fmt.Fprintln(os.Stderr, "evalindex:", err)
		os.Exit(1)
	}
	data, err := Marshal(index)
	if err != nil {
		fmt.Fprintln(os.Stderr, "evalindex:", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil && *out == DefaultOut {
		fmt.Fprintln(os.Stderr, "evalindex:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "evalindex:", err)
		os.Exit(1)
	}

	c := index.Coverage
	fmt.Printf("evalindex: %d questions, %d evals (%d measured, %d partial, %d unvalidated, %d absent) → %s\n",
		len(index.Questions), len(index.Evals),
		c.Measured, c.Partial, c.Unvalidated, c.Absent, *out)
}

// Index is the whole cover page.
type Index struct {
	Note      string     `json:"_note"`
	Questions []Question `json:"questions"`
	Evals     []Eval     `json:"evals"`
	Coverage  Coverage   `json:"coverage"`
}

// Coverage is the honest summary: how much of what a reader might ask is
// actually answered.
type Coverage struct {
	Measured    int `json:"measured"`
	Partial     int `json:"partial"`
	Unvalidated int `json:"unvalidated"`
	Absent      int `json:"absent"`
	// QuestionsUnanswered counts questions where no eval is measured. It is the
	// number worth putting at the top of the page.
	QuestionsUnanswered int `json:"questionsUnanswered"`
}

const indexNote = "GENERATED by `go run ./scripts/evalindex`. The cards are authored; their claims about " +
	"coverage are checked against the repository by the companion test, because a registry free to say " +
	"whatever it likes about how well kapi is measured would be the opposite of evidence."

// Build assembles the index and refuses to emit one that contradicts itself.
func Build() (*Index, error) {
	byID := make(map[string]Eval, len(evals))
	for _, e := range evals {
		if _, dup := byID[e.ID]; dup {
			return nil, fmt.Errorf("two evals share the id %q", e.ID)
		}
		byID[e.ID] = e
	}

	seen := map[string]bool{}
	for _, q := range questions {
		if len(q.Evals) == 0 {
			return nil, fmt.Errorf("question %q lists no evals; an unanswerable question is a card, not a heading", q.ID)
		}
		for _, id := range q.Evals {
			if _, ok := byID[id]; !ok {
				return nil, fmt.Errorf("question %q names eval %q, which has no card", q.ID, id)
			}
			if seen[id] {
				return nil, fmt.Errorf("eval %q answers two questions; give it a primary home", id)
			}
			seen[id] = true
		}
	}
	for _, e := range evals {
		if !seen[e.ID] {
			return nil, fmt.Errorf("eval %q answers no question, so nothing on the page would explain why it exists", e.ID)
		}
	}

	index := &Index{Note: indexNote, Questions: questions, Evals: evals}
	for _, e := range evals {
		switch e.Status {
		case StatusMeasured:
			index.Coverage.Measured++
		case StatusPartial:
			index.Coverage.Partial++
		case StatusUnvalidated:
			index.Coverage.Unvalidated++
		case StatusAbsent:
			index.Coverage.Absent++
		}
	}
	for _, q := range questions {
		answered := false
		for _, id := range q.Evals {
			if byID[id].Status == StatusMeasured || byID[id].Status == StatusPartial {
				answered = true
			}
		}
		if !answered {
			index.Coverage.QuestionsUnanswered++
		}
	}
	return index, nil
}

// Marshal renders the index as the exact bytes committed.
func Marshal(i *Index) ([]byte, error) {
	var b strings.Builder
	enc := json.NewEncoder(&b)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(i); err != nil {
		return nil, err
	}
	return []byte(b.String()), nil
}
