// neokapi_bridge.proto — the plugin/bridge gRPC service surface.
//
// This file holds only the BridgeService and its request/response envelope
// messages. The content-model messages (PartMessage, BlockMessage, the
// RunMessage discriminated union, overlays, skeleton, …) live in the
// canonical wire schema at core/proto/content/v1/content.proto (imported
// below). They were moved there verbatim — same field names and numbers —
// so the wire encoding is unchanged; see that file for the compatibility
// policy (field numbers frozen, no renames).
//
// The Java okapi-bridge compiles both files; content.proto keeps
// java_package "neokapi.bridge.proto" so the generated Java classes are
// unchanged.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: core/plugin/proto/v2/neokapi_bridge.proto

package bridgev2

import (
	v1 "github.com/neokapi/neokapi/core/proto/content/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OutputRef specifies where to write output directly on disk.
type OutputRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Destination:
	//
	//	*OutputRef_Path
	//	*OutputRef_Uri
	Destination   isOutputRef_Destination `protobuf_oneof:"destination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputRef) Reset() {
	*x = OutputRef{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputRef) ProtoMessage() {}

func (x *OutputRef) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputRef.ProtoReflect.Descriptor instead.
func (*OutputRef) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *OutputRef) GetDestination() isOutputRef_Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *OutputRef) GetPath() string {
	if x != nil {
		if x, ok := x.Destination.(*OutputRef_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *OutputRef) GetUri() string {
	if x != nil {
		if x, ok := x.Destination.(*OutputRef_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

type isOutputRef_Destination interface {
	isOutputRef_Destination()
}

type OutputRef_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"` // Local filesystem path
}

type OutputRef_Uri struct {
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3,oneof"` // Remote/local URI
}

func (*OutputRef_Path) isOutputRef_Destination() {}

func (*OutputRef_Uri) isOutputRef_Destination() {}

// PartBatch holds multiple parts in a single gRPC message to amortize
// per-message overhead (proto marshal, HTTP/2 framing, flush syscalls).
type PartBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*v1.PartMessage      `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartBatch) Reset() {
	*x = PartBatch{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartBatch) ProtoMessage() {}

func (x *PartBatch) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartBatch.ProtoReflect.Descriptor instead.
func (*PartBatch) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *PartBatch) GetParts() []*v1.PartMessage {
	if x != nil {
		return x.Parts
	}
	return nil
}

// ContentBlockBatch holds multiple ContentBlocks for batched gRPC transfer.
type ContentBlockBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*v1.ContentBlock     `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockBatch) Reset() {
	*x = ContentBlockBatch{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockBatch) ProtoMessage() {}

func (x *ContentBlockBatch) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockBatch.ProtoReflect.Descriptor instead.
func (*ContentBlockBatch) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *ContentBlockBatch) GetBlocks() []*v1.ContentBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// ProcessRequest is sent by the client (Go) to the server (Java).
type ProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ProcessRequest_Header
	//	*ProcessRequest_Part
	//	*ProcessRequest_PartBatch
	//	*ProcessRequest_ContentBlock
	//	*ProcessRequest_ContentBatch
	Request       isProcessRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessRequest) GetRequest() isProcessRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ProcessRequest) GetHeader() *ProcessHeader {
	if x != nil {
		if x, ok := x.Request.(*ProcessRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ProcessRequest) GetPart() *v1.PartMessage {
	if x != nil {
		if x, ok := x.Request.(*ProcessRequest_Part); ok {
			return x.Part
		}
	}
	return nil
}

func (x *ProcessRequest) GetPartBatch() *PartBatch {
	if x != nil {
		if x, ok := x.Request.(*ProcessRequest_PartBatch); ok {
			return x.PartBatch
		}
	}
	return nil
}

func (x *ProcessRequest) GetContentBlock() *v1.ContentBlock {
	if x != nil {
		if x, ok := x.Request.(*ProcessRequest_ContentBlock); ok {
			return x.ContentBlock
		}
	}
	return nil
}

func (x *ProcessRequest) GetContentBatch() *ContentBlockBatch {
	if x != nil {
		if x, ok := x.Request.(*ProcessRequest_ContentBatch); ok {
			return x.ContentBatch
		}
	}
	return nil
}

type isProcessRequest_Request interface {
	isProcessRequest_Request()
}

type ProcessRequest_Header struct {
	Header *ProcessHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"` // First message: input/output config
}

type ProcessRequest_Part struct {
	Part *v1.PartMessage `protobuf:"bytes,2,opt,name=part,proto3,oneof"` // Single processed part (legacy)
}

type ProcessRequest_PartBatch struct {
	PartBatch *PartBatch `protobuf:"bytes,3,opt,name=part_batch,json=partBatch,proto3,oneof"` // Batched processed parts
}

type ProcessRequest_ContentBlock struct {
	ContentBlock *v1.ContentBlock `protobuf:"bytes,5,opt,name=content_block,json=contentBlock,proto3,oneof"` // Single processed content block (lightweight)
}

type ProcessRequest_ContentBatch struct {
	ContentBatch *ContentBlockBatch `protobuf:"bytes,6,opt,name=content_batch,json=contentBatch,proto3,oneof"` // Batched processed content blocks (preferred)
}

func (*ProcessRequest_Header) isProcessRequest_Request() {}

func (*ProcessRequest_Part) isProcessRequest_Request() {}

func (*ProcessRequest_PartBatch) isProcessRequest_Request() {}

func (*ProcessRequest_ContentBlock) isProcessRequest_Request() {}

func (*ProcessRequest_ContentBatch) isProcessRequest_Request() {}

// ProcessResponse is sent by the server (Java) to the client (Go).
type ProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ProcessResponse_Part
	//	*ProcessResponse_ReadDone
	//	*ProcessResponse_Complete
	//	*ProcessResponse_PartBatch
	//	*ProcessResponse_ContentBatch
	Response      isProcessResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessResponse) GetResponse() isProcessResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ProcessResponse) GetPart() *v1.PartMessage {
	if x != nil {
		if x, ok := x.Response.(*ProcessResponse_Part); ok {
			return x.Part
		}
	}
	return nil
}

func (x *ProcessResponse) GetReadDone() *ProcessReadDone {
	if x != nil {
		if x, ok := x.Response.(*ProcessResponse_ReadDone); ok {
			return x.ReadDone
		}
	}
	return nil
}

func (x *ProcessResponse) GetComplete() *ProcessComplete {
	if x != nil {
		if x, ok := x.Response.(*ProcessResponse_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *ProcessResponse) GetPartBatch() *PartBatch {
	if x != nil {
		if x, ok := x.Response.(*ProcessResponse_PartBatch); ok {
			return x.PartBatch
		}
	}
	return nil
}

func (x *ProcessResponse) GetContentBatch() *ContentBlockBatch {
	if x != nil {
		if x, ok := x.Response.(*ProcessResponse_ContentBatch); ok {
			return x.ContentBatch
		}
	}
	return nil
}

type isProcessResponse_Response interface {
	isProcessResponse_Response()
}

type ProcessResponse_Part struct {
	Part *v1.PartMessage `protobuf:"bytes,1,opt,name=part,proto3,oneof"` // Single part (legacy)
}

type ProcessResponse_ReadDone struct {
	ReadDone *ProcessReadDone `protobuf:"bytes,2,opt,name=read_done,json=readDone,proto3,oneof"` // All parts have been read
}

type ProcessResponse_Complete struct {
	Complete *ProcessComplete `protobuf:"bytes,3,opt,name=complete,proto3,oneof"` // Output written, cycle complete
}

type ProcessResponse_PartBatch struct {
	PartBatch *PartBatch `protobuf:"bytes,4,opt,name=part_batch,json=partBatch,proto3,oneof"` // Batched parts
}

type ProcessResponse_ContentBatch struct {
	ContentBatch *ContentBlockBatch `protobuf:"bytes,5,opt,name=content_batch,json=contentBatch,proto3,oneof"` // Batched content blocks (lightweight, preferred)
}

func (*ProcessResponse_Part) isProcessResponse_Response() {}

func (*ProcessResponse_ReadDone) isProcessResponse_Response() {}

func (*ProcessResponse_Complete) isProcessResponse_Response() {}

func (*ProcessResponse_PartBatch) isProcessResponse_Response() {}

func (*ProcessResponse_ContentBatch) isProcessResponse_Response() {}

// InlineStep configures a pipeline step to run inside the Process RPC.
// When ProcessHeader.inline_steps is non-empty, the Java side pipes each
// filter event through the step chain before streaming results to Go.
// This eliminates Go↔Java round-trips for Okapi-native step processing.
type InlineStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepClass     string                 `protobuf:"bytes,1,opt,name=step_class,json=stepClass,proto3" json:"step_class,omitempty"`                                                                              // Fully-qualified Java class name
	StepParams    map[string]string      `protobuf:"bytes,2,rep,name=step_params,json=stepParams,proto3" json:"step_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Step parameters (key-value)
	ParamTypes    map[string]string      `protobuf:"bytes,3,rep,name=param_types,json=paramTypes,proto3" json:"param_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Schema-derived types for correct Okapi suffixes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineStep) Reset() {
	*x = InlineStep{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineStep) ProtoMessage() {}

func (x *InlineStep) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineStep.ProtoReflect.Descriptor instead.
func (*InlineStep) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *InlineStep) GetStepClass() string {
	if x != nil {
		return x.StepClass
	}
	return ""
}

func (x *InlineStep) GetStepParams() map[string]string {
	if x != nil {
		return x.StepParams
	}
	return nil
}

func (x *InlineStep) GetParamTypes() map[string]string {
	if x != nil {
		return x.ParamTypes
	}
	return nil
}

// ProcessHeader configures the Process RPC.
type ProcessHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilterClass    string                 `protobuf:"bytes,1,opt,name=filter_class,json=filterClass,proto3" json:"filter_class,omitempty"`
	Input          *v1.ContentRef         `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"` // Input document reference
	SourceLocale   string                 `protobuf:"bytes,3,opt,name=source_locale,json=sourceLocale,proto3" json:"source_locale,omitempty"`
	TargetLocale   string                 `protobuf:"bytes,4,opt,name=target_locale,json=targetLocale,proto3" json:"target_locale,omitempty"`
	Encoding       string                 `protobuf:"bytes,5,opt,name=encoding,proto3" json:"encoding,omitempty"`
	MimeType       string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FilterParams   map[string]string      `protobuf:"bytes,7,rep,name=filter_params,json=filterParams,proto3" json:"filter_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Output         *OutputRef             `protobuf:"bytes,8,opt,name=output,proto3" json:"output,omitempty"`                                                // Where to write output (optional; omit for read-only)
	OutputLocale   string                 `protobuf:"bytes,9,opt,name=output_locale,json=outputLocale,proto3" json:"output_locale,omitempty"`                // Locale for the output document
	SubscribeParts []int32                `protobuf:"varint,10,rep,packed,name=subscribe_parts,json=subscribeParts,proto3" json:"subscribe_parts,omitempty"` // Part types to stream to Go (empty = all).
	// Java only sends parts matching these types;
	// all other events are written directly without
	// crossing the gRPC boundary.
	// Values match PartMessage.part_type (e.g. 5 = Block).
	InlineSteps []*InlineStep `protobuf:"bytes,11,rep,name=inline_steps,json=inlineSteps,proto3" json:"inline_steps,omitempty"` // Optional steps to run between filter and writer.
	// Steps are applied in order to each filter event
	// before it is streamed to Go or written to output.
	ConfigId      string `protobuf:"bytes,12,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"` // Optional named Okapi filter configuration to apply
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessHeader) Reset() {
	*x = ProcessHeader{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessHeader) ProtoMessage() {}

func (x *ProcessHeader) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessHeader.ProtoReflect.Descriptor instead.
func (*ProcessHeader) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessHeader) GetFilterClass() string {
	if x != nil {
		return x.FilterClass
	}
	return ""
}

func (x *ProcessHeader) GetInput() *v1.ContentRef {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ProcessHeader) GetSourceLocale() string {
	if x != nil {
		return x.SourceLocale
	}
	return ""
}

func (x *ProcessHeader) GetTargetLocale() string {
	if x != nil {
		return x.TargetLocale
	}
	return ""
}

func (x *ProcessHeader) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *ProcessHeader) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ProcessHeader) GetFilterParams() map[string]string {
	if x != nil {
		return x.FilterParams
	}
	return nil
}

func (x *ProcessHeader) GetOutput() *OutputRef {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ProcessHeader) GetOutputLocale() string {
	if x != nil {
		return x.OutputLocale
	}
	return ""
}

func (x *ProcessHeader) GetSubscribeParts() []int32 {
	if x != nil {
		return x.SubscribeParts
	}
	return nil
}

func (x *ProcessHeader) GetInlineSteps() []*InlineStep {
	if x != nil {
		return x.InlineSteps
	}
	return nil
}

func (x *ProcessHeader) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

// ProcessReadDone signals that all parts have been read from the document.
type ProcessReadDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessReadDone) Reset() {
	*x = ProcessReadDone{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessReadDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReadDone) ProtoMessage() {}

func (x *ProcessReadDone) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReadDone.ProtoReflect.Descriptor instead.
func (*ProcessReadDone) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{7}
}

// ProcessComplete signals that the output has been written (or read-only is done).
type ProcessComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`                           // Inline output bytes (empty when OutputRef was used)
	OutputPath    string                 `protobuf:"bytes,2,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"` // Path where output was written
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessComplete) Reset() {
	*x = ProcessComplete{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessComplete) ProtoMessage() {}

func (x *ProcessComplete) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessComplete.ProtoReflect.Descriptor instead.
func (*ProcessComplete) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessComplete) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ProcessComplete) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *ProcessComplete) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{9}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{10}
}

// StepRequest is sent by the client (Go) to the server (Java) for step processing.
type StepRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*StepRequest_Header
	//	*StepRequest_Part
	Request       isStepRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *StepRequest) GetRequest() isStepRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StepRequest) GetHeader() *StepHeader {
	if x != nil {
		if x, ok := x.Request.(*StepRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *StepRequest) GetPart() *v1.PartMessage {
	if x != nil {
		if x, ok := x.Request.(*StepRequest_Part); ok {
			return x.Part
		}
	}
	return nil
}

type isStepRequest_Request interface {
	isStepRequest_Request()
}

type StepRequest_Header struct {
	Header *StepHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type StepRequest_Part struct {
	Part *v1.PartMessage `protobuf:"bytes,2,opt,name=part,proto3,oneof"`
}

func (*StepRequest_Header) isStepRequest_Request() {}

func (*StepRequest_Part) isStepRequest_Request() {}

// StepHeader configures the ProcessStep RPC.
type StepHeader struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StepClass          string                 `protobuf:"bytes,1,opt,name=step_class,json=stepClass,proto3" json:"step_class,omitempty"`                                                                              // Fully-qualified Java class name of the step
	StepParams         map[string]string      `protobuf:"bytes,2,rep,name=step_params,json=stepParams,proto3" json:"step_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Step parameters (key-value)
	SourceLocale       string                 `protobuf:"bytes,3,opt,name=source_locale,json=sourceLocale,proto3" json:"source_locale,omitempty"`
	TargetLocale       string                 `protobuf:"bytes,4,opt,name=target_locale,json=targetLocale,proto3" json:"target_locale,omitempty"`
	RootDirectory      string                 `protobuf:"bytes,5,opt,name=root_directory,json=rootDirectory,proto3" json:"root_directory,omitempty"`                                                                  // Project root for ${rootDir} resolution
	InputRootDirectory string                 `protobuf:"bytes,6,opt,name=input_root_directory,json=inputRootDirectory,proto3" json:"input_root_directory,omitempty"`                                                 // Input root for ${inputRootDir} resolution
	ParamTypes         map[string]string      `protobuf:"bytes,7,rep,name=param_types,json=paramTypes,proto3" json:"param_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Schema-derived types: {"regEx":"boolean","count":"integer"}
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StepHeader) Reset() {
	*x = StepHeader{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepHeader) ProtoMessage() {}

func (x *StepHeader) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepHeader.ProtoReflect.Descriptor instead.
func (*StepHeader) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *StepHeader) GetStepClass() string {
	if x != nil {
		return x.StepClass
	}
	return ""
}

func (x *StepHeader) GetStepParams() map[string]string {
	if x != nil {
		return x.StepParams
	}
	return nil
}

func (x *StepHeader) GetSourceLocale() string {
	if x != nil {
		return x.SourceLocale
	}
	return ""
}

func (x *StepHeader) GetTargetLocale() string {
	if x != nil {
		return x.TargetLocale
	}
	return ""
}

func (x *StepHeader) GetRootDirectory() string {
	if x != nil {
		return x.RootDirectory
	}
	return ""
}

func (x *StepHeader) GetInputRootDirectory() string {
	if x != nil {
		return x.InputRootDirectory
	}
	return ""
}

func (x *StepHeader) GetParamTypes() map[string]string {
	if x != nil {
		return x.ParamTypes
	}
	return nil
}

// StepResponse is sent by the server (Java) to the client (Go).
type StepResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*StepResponse_Part
	//	*StepResponse_Complete
	Response      isStepResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *StepResponse) GetResponse() isStepResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *StepResponse) GetPart() *v1.PartMessage {
	if x != nil {
		if x, ok := x.Response.(*StepResponse_Part); ok {
			return x.Part
		}
	}
	return nil
}

func (x *StepResponse) GetComplete() *StepComplete {
	if x != nil {
		if x, ok := x.Response.(*StepResponse_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

type isStepResponse_Response interface {
	isStepResponse_Response()
}

type StepResponse_Part struct {
	Part *v1.PartMessage `protobuf:"bytes,1,opt,name=part,proto3,oneof"`
}

type StepResponse_Complete struct {
	Complete *StepComplete `protobuf:"bytes,2,opt,name=complete,proto3,oneof"`
}

func (*StepResponse_Part) isStepResponse_Response() {}

func (*StepResponse_Complete) isStepResponse_Response() {}

// StepComplete signals that all parts have been processed by the step.
type StepComplete struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartsProcessed int32                  `protobuf:"varint,1,opt,name=parts_processed,json=partsProcessed,proto3" json:"parts_processed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StepComplete) Reset() {
	*x = StepComplete{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepComplete) ProtoMessage() {}

func (x *StepComplete) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepComplete.ProtoReflect.Descriptor instead.
func (*StepComplete) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *StepComplete) GetPartsProcessed() int32 {
	if x != nil {
		return x.PartsProcessed
	}
	return 0
}

// SegmentRequest asks the daemon to segment one run of text.
type SegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`                                                                           // segmenter name (capabilities.segmenters[].name)
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                                                               // flattened, code-masked text to segment
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`                                                                           // BCP-47 locale
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // engine-specific params (e.g. model, threshold)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentRequest) Reset() {
	*x = SegmentRequest{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentRequest) ProtoMessage() {}

func (x *SegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentRequest.ProtoReflect.Descriptor instead.
func (*SegmentRequest) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{15}
}

func (x *SegmentRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *SegmentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SegmentRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SegmentRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// SegmentResponse returns the interior boundaries — ascending rune (code-point)
// offsets into SegmentRequest.text, excluding 0 and len(text).
type SegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundaries    []int32                `protobuf:"varint,1,rep,packed,name=boundaries,proto3" json:"boundaries,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentResponse) Reset() {
	*x = SegmentResponse{}
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentResponse) ProtoMessage() {}

func (x *SegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentResponse.ProtoReflect.Descriptor instead.
func (*SegmentResponse) Descriptor() ([]byte, []int) {
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP(), []int{16}
}

func (x *SegmentResponse) GetBoundaries() []int32 {
	if x != nil {
		return x.Boundaries
	}
	return nil
}

func (x *SegmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_core_plugin_proto_v2_neokapi_bridge_proto protoreflect.FileDescriptor

const file_core_plugin_proto_v2_neokapi_bridge_proto_rawDesc = "" +
	"\n" +
	")core/plugin/proto/v2/neokapi_bridge.proto\x12\x11neokapi.bridge.v2\x1a#core/proto/content/v1/content.proto\"D\n" +
	"\tOutputRef\x12\x14\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x12\x12\n" +
	"\x03uri\x18\x02 \x01(\tH\x00R\x03uriB\r\n" +
	"\vdestination\"B\n" +
	"\tPartBatch\x125\n" +
	"\x05parts\x18\x01 \x03(\v2\x1f.neokapi.content.v1.PartMessageR\x05parts\"M\n" +
	"\x11ContentBlockBatch\x128\n" +
	"\x06blocks\x18\x01 \x03(\v2 .neokapi.content.v1.ContentBlockR\x06blocks\"\xe3\x02\n" +
	"\x0eProcessRequest\x12:\n" +
	"\x06header\x18\x01 \x01(\v2 .neokapi.bridge.v2.ProcessHeaderH\x00R\x06header\x125\n" +
	"\x04part\x18\x02 \x01(\v2\x1f.neokapi.content.v1.PartMessageH\x00R\x04part\x12=\n" +
	"\n" +
	"part_batch\x18\x03 \x01(\v2\x1c.neokapi.bridge.v2.PartBatchH\x00R\tpartBatch\x12G\n" +
	"\rcontent_block\x18\x05 \x01(\v2 .neokapi.content.v1.ContentBlockH\x00R\fcontentBlock\x12K\n" +
	"\rcontent_batch\x18\x06 \x01(\v2$.neokapi.bridge.v2.ContentBlockBatchH\x00R\fcontentBatchB\t\n" +
	"\arequest\"\xe5\x02\n" +
	"\x0fProcessResponse\x125\n" +
	"\x04part\x18\x01 \x01(\v2\x1f.neokapi.content.v1.PartMessageH\x00R\x04part\x12A\n" +
	"\tread_done\x18\x02 \x01(\v2\".neokapi.bridge.v2.ProcessReadDoneH\x00R\breadDone\x12@\n" +
	"\bcomplete\x18\x03 \x01(\v2\".neokapi.bridge.v2.ProcessCompleteH\x00R\bcomplete\x12=\n" +
	"\n" +
	"part_batch\x18\x04 \x01(\v2\x1c.neokapi.bridge.v2.PartBatchH\x00R\tpartBatch\x12K\n" +
	"\rcontent_batch\x18\x05 \x01(\v2$.neokapi.bridge.v2.ContentBlockBatchH\x00R\fcontentBatchB\n" +
	"\n" +
	"\bresponse\"\xc9\x02\n" +
	"\n" +
	"InlineStep\x12\x1d\n" +
	"\n" +
	"step_class\x18\x01 \x01(\tR\tstepClass\x12N\n" +
	"\vstep_params\x18\x02 \x03(\v2-.neokapi.bridge.v2.InlineStep.StepParamsEntryR\n" +
	"stepParams\x12N\n" +
	"\vparam_types\x18\x03 \x03(\v2-.neokapi.bridge.v2.InlineStep.ParamTypesEntryR\n" +
	"paramTypes\x1a=\n" +
	"\x0fStepParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fParamTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x04\n" +
	"\rProcessHeader\x12!\n" +
	"\ffilter_class\x18\x01 \x01(\tR\vfilterClass\x124\n" +
	"\x05input\x18\x02 \x01(\v2\x1e.neokapi.content.v1.ContentRefR\x05input\x12#\n" +
	"\rsource_locale\x18\x03 \x01(\tR\fsourceLocale\x12#\n" +
	"\rtarget_locale\x18\x04 \x01(\tR\ftargetLocale\x12\x1a\n" +
	"\bencoding\x18\x05 \x01(\tR\bencoding\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12W\n" +
	"\rfilter_params\x18\a \x03(\v22.neokapi.bridge.v2.ProcessHeader.FilterParamsEntryR\ffilterParams\x124\n" +
	"\x06output\x18\b \x01(\v2\x1c.neokapi.bridge.v2.OutputRefR\x06output\x12#\n" +
	"\routput_locale\x18\t \x01(\tR\foutputLocale\x12'\n" +
	"\x0fsubscribe_parts\x18\n" +
	" \x03(\x05R\x0esubscribeParts\x12@\n" +
	"\finline_steps\x18\v \x03(\v2\x1d.neokapi.bridge.v2.InlineStepR\vinlineSteps\x12\x1b\n" +
	"\tconfig_id\x18\f \x01(\tR\bconfigId\x1a?\n" +
	"\x11FilterParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fProcessReadDone\"`\n" +
	"\x0fProcessComplete\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x1f\n" +
	"\voutput_path\x18\x02 \x01(\tR\n" +
	"outputPath\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x88\x01\n" +
	"\vStepRequest\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1d.neokapi.bridge.v2.StepHeaderH\x00R\x06header\x125\n" +
	"\x04part\x18\x02 \x01(\v2\x1f.neokapi.content.v1.PartMessageH\x00R\x04partB\t\n" +
	"\arequest\"\xec\x03\n" +
	"\n" +
	"StepHeader\x12\x1d\n" +
	"\n" +
	"step_class\x18\x01 \x01(\tR\tstepClass\x12N\n" +
	"\vstep_params\x18\x02 \x03(\v2-.neokapi.bridge.v2.StepHeader.StepParamsEntryR\n" +
	"stepParams\x12#\n" +
	"\rsource_locale\x18\x03 \x01(\tR\fsourceLocale\x12#\n" +
	"\rtarget_locale\x18\x04 \x01(\tR\ftargetLocale\x12%\n" +
	"\x0eroot_directory\x18\x05 \x01(\tR\rrootDirectory\x120\n" +
	"\x14input_root_directory\x18\x06 \x01(\tR\x12inputRootDirectory\x12N\n" +
	"\vparam_types\x18\a \x03(\v2-.neokapi.bridge.v2.StepHeader.ParamTypesEntryR\n" +
	"paramTypes\x1a=\n" +
	"\x0fStepParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fParamTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\fStepResponse\x125\n" +
	"\x04part\x18\x01 \x01(\v2\x1f.neokapi.content.v1.PartMessageH\x00R\x04part\x12=\n" +
	"\bcomplete\x18\x02 \x01(\v2\x1f.neokapi.bridge.v2.StepCompleteH\x00R\bcompleteB\n" +
	"\n" +
	"\bresponse\"7\n" +
	"\fStepComplete\x12'\n" +
	"\x0fparts_processed\x18\x01 \x01(\x05R\x0epartsProcessed\"\xd6\x01\n" +
	"\x0eSegmentRequest\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\x12E\n" +
	"\x06params\x18\x04 \x03(\v2-.neokapi.bridge.v2.SegmentRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x0fSegmentResponse\x12\x1e\n" +
	"\n" +
	"boundaries\x18\x01 \x03(\x05R\n" +
	"boundaries\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xe0\x02\n" +
	"\rBridgeService\x12T\n" +
	"\aProcess\x12!.neokapi.bridge.v2.ProcessRequest\x1a\".neokapi.bridge.v2.ProcessResponse(\x010\x01\x12R\n" +
	"\vProcessStep\x12\x1e.neokapi.bridge.v2.StepRequest\x1a\x1f.neokapi.bridge.v2.StepResponse(\x010\x01\x12P\n" +
	"\aSegment\x12!.neokapi.bridge.v2.SegmentRequest\x1a\".neokapi.bridge.v2.SegmentResponse\x12S\n" +
	"\bShutdown\x12\".neokapi.bridge.v2.ShutdownRequest\x1a#.neokapi.bridge.v2.ShutdownResponseBR\n" +
	"\x14neokapi.bridge.protoP\x01Z8github.com/neokapi/neokapi/core/plugin/proto/v2;bridgev2b\x06proto3"

var (
	file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescOnce sync.Once
	file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescData []byte
)

func file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescGZIP() []byte {
	file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescOnce.Do(func() {
		file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_plugin_proto_v2_neokapi_bridge_proto_rawDesc), len(file_core_plugin_proto_v2_neokapi_bridge_proto_rawDesc)))
	})
	return file_core_plugin_proto_v2_neokapi_bridge_proto_rawDescData
}

var file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_core_plugin_proto_v2_neokapi_bridge_proto_goTypes = []any{
	(*OutputRef)(nil),         // 0: neokapi.bridge.v2.OutputRef
	(*PartBatch)(nil),         // 1: neokapi.bridge.v2.PartBatch
	(*ContentBlockBatch)(nil), // 2: neokapi.bridge.v2.ContentBlockBatch
	(*ProcessRequest)(nil),    // 3: neokapi.bridge.v2.ProcessRequest
	(*ProcessResponse)(nil),   // 4: neokapi.bridge.v2.ProcessResponse
	(*InlineStep)(nil),        // 5: neokapi.bridge.v2.InlineStep
	(*ProcessHeader)(nil),     // 6: neokapi.bridge.v2.ProcessHeader
	(*ProcessReadDone)(nil),   // 7: neokapi.bridge.v2.ProcessReadDone
	(*ProcessComplete)(nil),   // 8: neokapi.bridge.v2.ProcessComplete
	(*ShutdownRequest)(nil),   // 9: neokapi.bridge.v2.ShutdownRequest
	(*ShutdownResponse)(nil),  // 10: neokapi.bridge.v2.ShutdownResponse
	(*StepRequest)(nil),       // 11: neokapi.bridge.v2.StepRequest
	(*StepHeader)(nil),        // 12: neokapi.bridge.v2.StepHeader
	(*StepResponse)(nil),      // 13: neokapi.bridge.v2.StepResponse
	(*StepComplete)(nil),      // 14: neokapi.bridge.v2.StepComplete
	(*SegmentRequest)(nil),    // 15: neokapi.bridge.v2.SegmentRequest
	(*SegmentResponse)(nil),   // 16: neokapi.bridge.v2.SegmentResponse
	nil,                       // 17: neokapi.bridge.v2.InlineStep.StepParamsEntry
	nil,                       // 18: neokapi.bridge.v2.InlineStep.ParamTypesEntry
	nil,                       // 19: neokapi.bridge.v2.ProcessHeader.FilterParamsEntry
	nil,                       // 20: neokapi.bridge.v2.StepHeader.StepParamsEntry
	nil,                       // 21: neokapi.bridge.v2.StepHeader.ParamTypesEntry
	nil,                       // 22: neokapi.bridge.v2.SegmentRequest.ParamsEntry
	(*v1.PartMessage)(nil),    // 23: neokapi.content.v1.PartMessage
	(*v1.ContentBlock)(nil),   // 24: neokapi.content.v1.ContentBlock
	(*v1.ContentRef)(nil),     // 25: neokapi.content.v1.ContentRef
}
var file_core_plugin_proto_v2_neokapi_bridge_proto_depIdxs = []int32{
	23, // 0: neokapi.bridge.v2.PartBatch.parts:type_name -> neokapi.content.v1.PartMessage
	24, // 1: neokapi.bridge.v2.ContentBlockBatch.blocks:type_name -> neokapi.content.v1.ContentBlock
	6,  // 2: neokapi.bridge.v2.ProcessRequest.header:type_name -> neokapi.bridge.v2.ProcessHeader
	23, // 3: neokapi.bridge.v2.ProcessRequest.part:type_name -> neokapi.content.v1.PartMessage
	1,  // 4: neokapi.bridge.v2.ProcessRequest.part_batch:type_name -> neokapi.bridge.v2.PartBatch
	24, // 5: neokapi.bridge.v2.ProcessRequest.content_block:type_name -> neokapi.content.v1.ContentBlock
	2,  // 6: neokapi.bridge.v2.ProcessRequest.content_batch:type_name -> neokapi.bridge.v2.ContentBlockBatch
	23, // 7: neokapi.bridge.v2.ProcessResponse.part:type_name -> neokapi.content.v1.PartMessage
	7,  // 8: neokapi.bridge.v2.ProcessResponse.read_done:type_name -> neokapi.bridge.v2.ProcessReadDone
	8,  // 9: neokapi.bridge.v2.ProcessResponse.complete:type_name -> neokapi.bridge.v2.ProcessComplete
	1,  // 10: neokapi.bridge.v2.ProcessResponse.part_batch:type_name -> neokapi.bridge.v2.PartBatch
	2,  // 11: neokapi.bridge.v2.ProcessResponse.content_batch:type_name -> neokapi.bridge.v2.ContentBlockBatch
	17, // 12: neokapi.bridge.v2.InlineStep.step_params:type_name -> neokapi.bridge.v2.InlineStep.StepParamsEntry
	18, // 13: neokapi.bridge.v2.InlineStep.param_types:type_name -> neokapi.bridge.v2.InlineStep.ParamTypesEntry
	25, // 14: neokapi.bridge.v2.ProcessHeader.input:type_name -> neokapi.content.v1.ContentRef
	19, // 15: neokapi.bridge.v2.ProcessHeader.filter_params:type_name -> neokapi.bridge.v2.ProcessHeader.FilterParamsEntry
	0,  // 16: neokapi.bridge.v2.ProcessHeader.output:type_name -> neokapi.bridge.v2.OutputRef
	5,  // 17: neokapi.bridge.v2.ProcessHeader.inline_steps:type_name -> neokapi.bridge.v2.InlineStep
	12, // 18: neokapi.bridge.v2.StepRequest.header:type_name -> neokapi.bridge.v2.StepHeader
	23, // 19: neokapi.bridge.v2.StepRequest.part:type_name -> neokapi.content.v1.PartMessage
	20, // 20: neokapi.bridge.v2.StepHeader.step_params:type_name -> neokapi.bridge.v2.StepHeader.StepParamsEntry
	21, // 21: neokapi.bridge.v2.StepHeader.param_types:type_name -> neokapi.bridge.v2.StepHeader.ParamTypesEntry
	23, // 22: neokapi.bridge.v2.StepResponse.part:type_name -> neokapi.content.v1.PartMessage
	14, // 23: neokapi.bridge.v2.StepResponse.complete:type_name -> neokapi.bridge.v2.StepComplete
	22, // 24: neokapi.bridge.v2.SegmentRequest.params:type_name -> neokapi.bridge.v2.SegmentRequest.ParamsEntry
	3,  // 25: neokapi.bridge.v2.BridgeService.Process:input_type -> neokapi.bridge.v2.ProcessRequest
	11, // 26: neokapi.bridge.v2.BridgeService.ProcessStep:input_type -> neokapi.bridge.v2.StepRequest
	15, // 27: neokapi.bridge.v2.BridgeService.Segment:input_type -> neokapi.bridge.v2.SegmentRequest
	9,  // 28: neokapi.bridge.v2.BridgeService.Shutdown:input_type -> neokapi.bridge.v2.ShutdownRequest
	4,  // 29: neokapi.bridge.v2.BridgeService.Process:output_type -> neokapi.bridge.v2.ProcessResponse
	13, // 30: neokapi.bridge.v2.BridgeService.ProcessStep:output_type -> neokapi.bridge.v2.StepResponse
	16, // 31: neokapi.bridge.v2.BridgeService.Segment:output_type -> neokapi.bridge.v2.SegmentResponse
	10, // 32: neokapi.bridge.v2.BridgeService.Shutdown:output_type -> neokapi.bridge.v2.ShutdownResponse
	29, // [29:33] is the sub-list for method output_type
	25, // [25:29] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_core_plugin_proto_v2_neokapi_bridge_proto_init() }
func file_core_plugin_proto_v2_neokapi_bridge_proto_init() {
	if File_core_plugin_proto_v2_neokapi_bridge_proto != nil {
		return
	}
	file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[0].OneofWrappers = []any{
		(*OutputRef_Path)(nil),
		(*OutputRef_Uri)(nil),
	}
	file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[3].OneofWrappers = []any{
		(*ProcessRequest_Header)(nil),
		(*ProcessRequest_Part)(nil),
		(*ProcessRequest_PartBatch)(nil),
		(*ProcessRequest_ContentBlock)(nil),
		(*ProcessRequest_ContentBatch)(nil),
	}
	file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[4].OneofWrappers = []any{
		(*ProcessResponse_Part)(nil),
		(*ProcessResponse_ReadDone)(nil),
		(*ProcessResponse_Complete)(nil),
		(*ProcessResponse_PartBatch)(nil),
		(*ProcessResponse_ContentBatch)(nil),
	}
	file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[11].OneofWrappers = []any{
		(*StepRequest_Header)(nil),
		(*StepRequest_Part)(nil),
	}
	file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes[13].OneofWrappers = []any{
		(*StepResponse_Part)(nil),
		(*StepResponse_Complete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_plugin_proto_v2_neokapi_bridge_proto_rawDesc), len(file_core_plugin_proto_v2_neokapi_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_plugin_proto_v2_neokapi_bridge_proto_goTypes,
		DependencyIndexes: file_core_plugin_proto_v2_neokapi_bridge_proto_depIdxs,
		MessageInfos:      file_core_plugin_proto_v2_neokapi_bridge_proto_msgTypes,
	}.Build()
	File_core_plugin_proto_v2_neokapi_bridge_proto = out.File
	file_core_plugin_proto_v2_neokapi_bridge_proto_goTypes = nil
	file_core_plugin_proto_v2_neokapi_bridge_proto_depIdxs = nil
}
