import posthog from "posthog-js";
import { initPostHogSurface } from "@neokapi/ui";

const POSTHOG_KEY = import.meta.env.VITE_POSTHOG_KEY as string | undefined;
const POSTHOG_HOST = (import.meta.env.VITE_POSTHOG_HOST as string) || "https://eu.i.posthog.com";

let initialized = false;
let identified: string | undefined;

/**
 * Start analytics for an authenticated session. Idempotent; returns whether
 * analytics are running.
 *
 * Authentication is the gate, and `posthog.init` is the whole of what is being
 * gated: it is the call that writes the year-long `ph_*` identifier — on the
 * registrable domain, `.bowrain.cloud`, which the landing and documentation
 * sites share and publish as cookieless — arms autocapture, and starts session
 * replay. So an anonymous visitor reaches PostHog in no way at all: no cookie
 * on any domain, no recording, and not one request, including on the leg where
 * the app bounces a visitor with no session to the identity provider.
 *
 * `identifyUser` is the only caller, because a user id is exactly the evidence
 * that a session exists. Every other entry point below is inert until it has
 * run, so a call fired before the session is known is dropped rather than
 * queued — a dropped event is the price of the guarantee.
 */
function startAuthenticatedSession(): boolean {
  if (initialized) return true;
  // initPostHogSurface registers the mandatory {surface, environment} taxonomy
  // and key-gates init (keyless builds stay silent).
  initialized = initPostHogSurface(posthog, {
    surface: "web-app",
    environment: import.meta.env.MODE,
    key: POSTHOG_KEY,
    host: POSTHOG_HOST,
    init: {
      // SPA route changes never trigger a full document load, so automatic
      // pageviews would only cover the first hit. All $pageview events —
      // including the initial one — are fired from the TanStack Router
      // subscription in BowrainApp (via the platform seam), which also attaches
      // the params-scrubbed route pattern.
      capture_pageview: false,
      capture_pageleave: true,
      autocapture: true,
      // Session replay — the best tool for reproducing a user-reported error:
      // watch exactly what they did. Privacy-first (GDPR / EU PostHog): every
      // text input is masked by default; mark extra-sensitive DOM with
      // [data-sensitive] to blackout, or [data-ph-no-capture] to drop entirely.
      disable_session_recording: false,
      session_recording: {
        maskAllInputs: true,
        maskTextSelector: "[data-sensitive]",
      },
      // Core Web Vitals (LCP / INP / CLS) as $web_vitals events — real-user
      // performance, and the metrics Google ranks on.
      capture_performance: { web_vitals: true },
      // When api_host is our first-party reverse proxy (app.bowrain.cloud/ph, set
      // via VITE_POSTHOG_HOST), ui_host must still point at the real PostHog cloud
      // so links generated by the SDK (toolbar, replay) resolve correctly.
      ui_host: "https://eu.posthog.com",
    },
  });
  return initialized;
}

/**
 * Bind analytics to the signed-in user, starting them on the first call.
 *
 * The shared app calls this from the router's `beforeLoad`, the moment the
 * current-user fetch comes back with a session — ahead of the first `$pageview`
 * that resolution goes on to fire, so the opening event of a session is not the
 * one lost to starting up. Repeat calls for the same id are dropped: route
 * loads re-run, and PostHog only needs telling once.
 */
export function identifyUser(id: string, properties?: Record<string, unknown>) {
  if (!startAuthenticatedSession()) return;
  if (identified === id) return;
  identified = id;
  posthog.identify(id, properties);
}

/**
 * Fire-and-forget product event (platform seam `analytics.capture`).
 *
 * `transport: "beacon"` maps to posthog-js's `sendBeacon`, which hands the
 * request to the browser to deliver after the document is gone. An event fired
 * immediately before a top-level navigation needs it: the default batching
 * transport would still be holding the payload when the page unloads.
 */
export function captureEvent(
  event: string,
  properties?: Record<string, unknown>,
  options?: { transport?: "beacon" },
) {
  if (!initialized) return;
  if (options?.transport === "beacon") {
    posthog.capture(event, properties, { transport: "sendBeacon" });
    return;
  }
  posthog.capture(event, properties);
}

/** Associate the session with a PostHog group (platform seam `analytics.group`). */
export function groupIdentify(type: string, key: string, properties?: Record<string, unknown>) {
  if (!initialized) return;
  posthog.group(type, key, properties);
}

export function resetPostHog() {
  if (!initialized) return;
  identified = undefined;
  posthog.reset();
}

export { posthog };
