import posthog from "posthog-js";
import { initPostHogSurface } from "@neokapi/ui";

const POSTHOG_KEY = import.meta.env.VITE_POSTHOG_KEY as string | undefined;
const POSTHOG_HOST = (import.meta.env.VITE_POSTHOG_HOST as string) || "https://eu.i.posthog.com";

let initialized = false;

export function initPostHog() {
  if (initialized) return;
  // initPostHogSurface registers the mandatory {surface, environment} taxonomy
  // and key-gates init (keyless builds stay silent).
  initialized = initPostHogSurface(posthog, {
    surface: "web-app",
    environment: import.meta.env.MODE,
    key: POSTHOG_KEY,
    host: POSTHOG_HOST,
    init: {
      // SPA route changes never trigger a full document load, so automatic
      // pageviews would only cover the first hit. All $pageview events —
      // including the initial one — are fired from the TanStack Router
      // subscription in BowrainApp (via the platform seam), which also attaches
      // the params-scrubbed route pattern.
      capture_pageview: false,
      capture_pageleave: true,
      autocapture: true,
      // Session replay — the best tool for reproducing a user-reported error:
      // watch exactly what they did. Privacy-first (GDPR / EU PostHog): every
      // text input is masked by default; mark extra-sensitive DOM with
      // [data-sensitive] to blackout, or [data-ph-no-capture] to drop entirely.
      disable_session_recording: false,
      session_recording: {
        maskAllInputs: true,
        maskTextSelector: "[data-sensitive]",
      },
      // Core Web Vitals (LCP / INP / CLS) as $web_vitals events — real-user
      // performance, and the metrics Google ranks on.
      capture_performance: { web_vitals: true },
      // When api_host is our first-party reverse proxy (app.bowrain.cloud/ph, set
      // via VITE_POSTHOG_HOST), ui_host must still point at the real PostHog cloud
      // so links generated by the SDK (toolbar, replay) resolve correctly.
      ui_host: "https://eu.posthog.com",
    },
  });
}

export function identifyUser(id: string, properties?: Record<string, unknown>) {
  if (!POSTHOG_KEY) return;
  posthog.identify(id, properties);
}

/**
 * Fire-and-forget product event (platform seam `analytics.capture`).
 *
 * `transport: "beacon"` maps to posthog-js's `sendBeacon`, which hands the
 * request to the browser to deliver after the document is gone. An event fired
 * immediately before a top-level navigation needs it: the default batching
 * transport would still be holding the payload when the page unloads.
 */
export function captureEvent(
  event: string,
  properties?: Record<string, unknown>,
  options?: { transport?: "beacon" },
) {
  if (!POSTHOG_KEY) return;
  if (options?.transport === "beacon") {
    posthog.capture(event, properties, { transport: "sendBeacon" });
    return;
  }
  posthog.capture(event, properties);
}

/** Associate the session with a PostHog group (platform seam `analytics.group`). */
export function groupIdentify(type: string, key: string, properties?: Record<string, unknown>) {
  if (!POSTHOG_KEY) return;
  posthog.group(type, key, properties);
}

export function resetPostHog() {
  if (!POSTHOG_KEY) return;
  posthog.reset();
}

export { posthog };
