import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  ad: [
    "README",
    "001-vision",
    "002-content-model",
    "003-content-store",
    "004-processing-engine",
    "005-connector-system",
    "006-tool-system",
    "007-plugin-system",
    "008-ai-integration",
    "009-translation-memory",
    "010-terminology",
    "011-automation",
    "012-bowrain",
    "013-cli-and-server",
    "014-testing-and-docs",
    "015-auth-and-workspaces",
    "016-kapi-project-model",
    "017-cli-output-format",
    "018-multi-module-architecture",
    "019-mt-providers",
    "020-collaborative-editor",
    "021-mcp-integration",
    "022-entity-term-extraction",
    "023-identity-system",
    "024-streams",
    "025-brand-voice-governance",
    "026-graph-concept-management",
    "027-activities-tasks-notifications",
    "028-bravo-agent",
    "029-media-asset-localization",
    "030-billing-plans",
    "031-billing-implementation-plan",
    "032-permissions-and-access-control",
    "033-pulse-public-activity-dashboard",
    "034-translator-workflow",
    "035-automation-run-visibility",
    "036-distributed-event-bus",
    "037-async-content-ingestion",
    "038-sync-protocol",
    "039-admin-control-plane",
    "040-rest-api-redesign",
    "040-tool-parameter-schemas",
    "041-kapi-desktop",
    "042-project-context",
    "043-tool-io-model",
    "044-klf-klz-integration",
    "045-klf-klz-spec",
  ],
};

export default sidebars;
