//go:build integration

package okf_xliff2

// Code generated by gen-test-stubs from Surefire XML. DO NOT EDIT.
// To implement a test, move it to the appropriate test file and
// replace t.Skip("pending") with test logic.

import "testing"

// ---- XLIFF2CodeFinderRoundTripTest (5 tests) ----

// okapi: XLIFF2CodeFinderRoundTripTest#testCodeFinderCreatesInlineCodes
func TestRoundTrip_CodeFinderCreatesInlineCodes(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2CodeFinderRoundTripTest#testCodeFinderWithEscapedHtmlTags
func TestRoundTrip_CodeFinderWithEscapedHtmlTags(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2CodeFinderRoundTripTest#testFullMergePreservesEscapedText
func TestRoundTrip_FullMergePreservesEscapedText(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2CodeFinderRoundTripTest#testFullRoundTripPreservesEscapedText
func TestRoundTrip_FullRoundTripPreservesEscapedText(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2CodeFinderRoundTripTest#testSubfilterCodeFinderOnly
func TestRoundTrip_SubfilterCodeFinderOnly(t *testing.T) {
	t.Skip("pending")
}

// ---- XLIFF2FilterTest (20 tests) ----

// okapi: XLIFF2FilterTest#handleInvalidCodeTypes
func TestExtract_HandleInvalidCodeTypes(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#roundTripTests
func TestExtract_RoundTripTests(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testDedupeCodeFinderCodes
func TestExtract_DedupeCodeFinderCodes(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testDoubleExtraction
func TestRoundTrip_DoubleExtraction(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testFromEscapedFile
func TestExtract_FromEscapedFile(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testFromFile
func TestExtract_FromFile(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testFromFile2
func TestExtract_FromFile2(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testIgnoreable
func TestExtract_Ignoreable(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testInlineCopyOf
func TestExtract_InlineCopyOf(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testMetadataXLIFF2intoXliff12
func TestExtract_MetadataXLIFF2intoXliff12(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testSegmentStateAndSubstateXLIFF2intoXliff12
func TestExtract_SegmentStateAndSubstateXLIFF2intoXliff12(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testStateChangeInitial
func TestExtract_StateChangeInitial(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testStateChangeTranslated
func TestExtract_StateChangeTranslated(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testSubFilterWithAllOptionsIcu
func TestExtract_SubFilterWithAllOptionsIcu(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testSubFilterWithAllOptionsIcuRoundtrip
func TestExtract_SubFilterWithAllOptionsIcuRoundtrip(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testSubFilterWithDefaultIcu
func TestExtract_SubFilterWithDefaultIcu(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testSubflows
func TestExtract_Subflows(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testWriteOriginalDataOption
func TestExtract_WriteOriginalDataOption(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#testWriteXLIFF2AsXliff12
func TestExtract_WriteXLIFF2AsXliff12(t *testing.T) {
	t.Skip("pending")
}

// okapi: XLIFF2FilterTest#updateTarget
func TestExtract_UpdateTarget(t *testing.T) {
	t.Skip("pending")
}

// ---- Xliff2FilterWriterTest (1 tests) ----

// okapi: Xliff2FilterWriterTest#testWriteHTMLAsXliff2
func TestWrite_WriteHTMLAsXliff2(t *testing.T) {
	t.Skip("pending")
}
