package main

import (
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestRecallCountsMultiplicity is the property the whole metric rests on.
//
// A set would score the second case perfect: every distinct word survives. A
// converter that dropped two of three identical paragraphs would look flawless,
// which is the exact failure this eval exists to catch.
func TestRecallCountsMultiplicity(t *testing.T) {
	truth := []string{"alpha beta", "alpha beta", "alpha beta"}

	full := score(truth, "alpha beta alpha beta alpha beta")
	assert.Equal(t, 6, full.TruthWords)
	assert.InDelta(t, 1.0, full.Recall, 1e-9, "nothing lost")

	oneCopy := score(truth, "alpha beta")
	assert.InDelta(t, 1.0/3, oneCopy.Recall, 1e-9, "two of three copies dropped")
	assert.Len(t, oneCopy.Missing, 2)
	assert.Equal(t, 2, oneCopy.Missing[0].Times)
}

// TestExtraOutputIsNotPunished: recall measures loss. A converter that adds a
// heading, a caption or its own boilerplate is doing something different from
// one that drops a paragraph, and scoring both as error would rank a lossy
// converter above a verbose one.
func TestExtraOutputIsNotPunished(t *testing.T) {
	r := score([]string{"alpha beta"}, "title alpha beta footer generated by something")
	assert.InDelta(t, 1.0, r.Recall, 1e-9)
	assert.Greater(t, r.OutputWords, r.TruthWords)
}

// TestCaseAndPunctuationDoNotCount: converters disagree about where a full stop
// attaches and whether a heading is capitalised, and neither is content loss.
func TestCaseAndPunctuationDoNotCount(t *testing.T) {
	r := score([]string{"Blizzard Entertainment."}, "blizzard, entertainment")
	assert.InDelta(t, 1.0, r.Recall, 1e-9)
}

// TestOneCharacterWordsAreDropped.
//
// A single letter matches something in nearly any output, so counting them
// pushes every converter's score toward every other and hides the differences
// the table is for.
func TestOneCharacterWordsAreDropped(t *testing.T) {
	assert.Equal(t, []string{"of", "the"}, words("a b of I the"))
}

// TestMissingIsOrderedAndCapped: the dataset is committed, so a rerun over the
// same corpus has to produce the same bytes.
func TestMissingIsOrderedAndCapped(t *testing.T) {
	var truth []string
	for i := range 40 {
		truth = append(truth, "word"+string(rune('a'+i%26))+string(rune('a'+i/26)))
	}
	r := score(truth, "")
	assert.LessOrEqual(t, len(r.Missing), maxMissingReported)
	for i := 1; i < len(r.Missing); i++ {
		a, b := r.Missing[i-1], r.Missing[i]
		if a.Times == b.Times {
			assert.Less(t, a.Word, b.Word, "ties break on the word, or two runs differ")
		} else {
			assert.Greater(t, a.Times, b.Times)
		}
	}
}

// TestGroundTruthReadsTheDocument.
//
// The independence claim is that the answer comes from the file rather than
// from a converter, so it is worth checking that the reader gets text out of a
// real document and that entities survive the XML decoder.
func TestGroundTruthReadsTheDocument(t *testing.T) {
	root, err := repoRoot()
	require.NoError(t, err)
	f := filepath.Join(root, "core/formats/openxml/testdata/simple.docx")

	got, err := groundTruth(f, ".docx")
	require.NoError(t, err)
	require.NotEmpty(t, got, "no text nodes read from a document that has text")

	joined := ""
	for _, g := range got {
		joined += g
	}
	assert.NotContains(t, joined, "&amp;", "entities are decoded by the XML reader, not left raw")
	assert.NotContains(t, joined, "<w:t", "markup is not text")
}

// TestGroundTruthRefusesWhatItCannotRead: a format with no spec entry has no
// ground truth, and guessing one would be the thing this eval exists to avoid.
func TestGroundTruthRefusesWhatItCannotRead(t *testing.T) {
	_, err := groundTruth("whatever.pdf", ".pdf")
	assert.Error(t, err)
}

// TestEveryConverterDeclaresWhatItReads: a converter asked for a format it has
// no target for scores failures that belong to the harness. LibreOffice was
// asked for .pptx in the first version and failed every one, because
// `--convert-to txt` has no Impress target.
func TestEveryConverterDeclaresWhatItReads(t *testing.T) {
	for _, c := range available(t.Context(), "") {
		t.Run(c.ID, func(t *testing.T) {
			assert.NotEmpty(t, c.Exts, "a converter that reads nothing should not be listed")
			for _, e := range c.Exts {
				assert.True(t, readable(e),
					"%s claims %s, which no ground-truth reader handles, so nothing could score it", c.ID, e)
			}
			assert.NotEmpty(t, c.Note, "say what kind of tool this is, or four numbers read as four attempts at one thing")
		})
	}
}

// TestLibreOfficeHasAFilterForEveryFormatItClaims: the two lists are edited
// separately and drift silently — a format in Exts with no filter fails every
// document with an error that reads like the tool's fault.
func TestLibreOfficeHasAFilterForEveryFormatItClaims(t *testing.T) {
	for _, c := range available(t.Context(), "") {
		if c.ID != "libreoffice" {
			continue
		}
		for _, e := range c.Exts {
			assert.Contains(t, loFilters, e, "no LibreOffice filter declared for %s", e)
		}
	}
}
