// GENERATED by scripts/walkthrough-gen from web/docs/walkthroughs/kapi-word-count.scene.yaml.
// Do not edit by hand — change the .scene.yaml and regenerate.
import type { WalkthroughEmbedConfig } from "./types";

const config: WalkthroughEmbedConfig = {
  id: "kapi-word-count",
  scene: "word-count",
  mode: "interactive",
  seed: ["messages.json"],
  files: [],
  steps: [
    {
      command: "kapi word-count messages.json",
      narration: "Reports blocks and source words — the number you paste into a quote.",
    },
  ],
};

export default config;
