// Command coordinatereport produces the data behind the /coordinate dashboard:
// what governs each point a recipe declares, which of a block's prior answers
// are offered as reference and which are withheld, and the two prompts side by
// side.
//
// Everything here is DETERMINISTIC. It calls the real resolver, the real
// corpus and the real prompt builder, and spends no model calls — so it runs on
// every pull request and its numbers are facts rather than samples. That is the
// half of this system that can be proven rather than measured, and proving it
// is what makes the measured half worth paying for.
//
//	go run ./scripts/coordinatereport                       # write the dashboard data
//	go run ./scripts/coordinatereport -out /dev/stdout      # inspect it
//
// A companion test regenerates it and fails on drift, so the committed file
// cannot silently disagree with the code it describes.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/neokapi/neokapi/core/project"
	"github.com/neokapi/neokapi/core/tools"
	"gopkg.in/yaml.v3"
)

// DefaultOut is the committed dashboard data.
const DefaultOut = "web/src/pages/coordinate/_coordinate.json"

func main() {
	out := flag.String("out", DefaultOut, "where to write the report")
	flag.Parse()

	report, err := Build(context.Background())
	if err != nil {
		fmt.Fprintln(os.Stderr, "coordinatereport:", err)
		os.Exit(1)
	}
	data, err := Marshal(report)
	if err != nil {
		fmt.Fprintln(os.Stderr, "coordinatereport:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "coordinatereport:", err)
		os.Exit(1)
	}
	fmt.Printf("coordinatereport: %d points, %d chains, %d prompt pairs, %d ladder rungs, %d sentences → %s\n",
		len(report.Points), len(report.Chains), len(report.Prompts),
		len(report.Ladder.Rungs), len(report.Segments.Segments), *out)
}

// Marshal renders the report as the exact bytes committed: 2-space indented,
// trailing newline, HTML escaping off, so the generator and the drift test
// produce identical files.
func Marshal(r *Report) ([]byte, error) {
	var b strings.Builder
	enc := json.NewEncoder(&b)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(r); err != nil {
		return nil, err
	}
	return []byte(b.String()), nil
}

// Report is the whole dashboard payload.
type Report struct {
	Note   string `json:"_note"`
	Recipe string `json:"recipe"`
	// Points is what governs each place the recipe declares content at.
	Points []Point `json:"points"`
	// Axes is every coordinate value the recipe declares, so a map can tell a
	// crossing that has no content from one the recipe never declared.
	Axes Axes `json:"axes"`
	// Chains is a block's prior answers and the verdict on each.
	Chains []Chain `json:"chains"`
	// Prompts is the same block rendered with and without its prior version.
	Prompts []PromptPair `json:"prompts"`
	// Ladder is what the matcher scores the edits an author actually makes, and
	// what each policy writes into the target file.
	Ladder *EditLadder `json:"ladder"`
	// Segments is the same edit measured as one block and as three sentences.
	Segments *SegmentSplit `json:"segments"`
}

const reportNote = "GENERATED by `go run ./scripts/coordinatereport`. Do not edit by hand: " +
	"every number here is computed by calling the real resolver, corpus and prompt builder, so a " +
	"claim typed in by hand would keep asserting itself after the code stopped supporting it."

// Axes is the coordinate space the recipe declares.
type Axes struct {
	Products []string `json:"products"`
	Channels []string `json:"channels"`
	// ChannelsByProduct is the channels each product declares. A crossing
	// outside this is not a place content could sit.
	ChannelsByProduct map[string][]string `json:"channelsByProduct"`
}

// Point is one place content sits, and the complete governance resolved there.
type Point struct {
	Slug        string            `json:"slug"`
	Label       string            `json:"label"`
	Coordinates map[string]string `json:"coordinates,omitempty"`
	Profile     string            `json:"profile,omitempty"`
	Channel     string            `json:"channel,omitempty"`
	VoiceFile   string            `json:"voiceFile,omitempty"`
	VoiceField  string            `json:"voiceField,omitempty"`
	TermStore   string            `json:"termStore,omitempty"`
	Collections []string          `json:"collections,omitempty"`
	// Default marks the point content sits at when it declares no coordinates.
	Default bool `json:"default,omitempty"`
}

// Version is one prior answer in a block's chain.
type Version struct {
	Source      string `json:"source"`
	Target      string `json:"target"`
	Fingerprint string `json:"fingerprint,omitempty"`
	ApprovedAt  string `json:"approvedAt"`
	// Governed reports whether this answer was approved under the context
	// currently in force.
	Governed bool `json:"governed"`
}

// Chain is one block's history at one point, and what the gate decides.
type Chain struct {
	Case        string    `json:"case"`
	Unit        string    `json:"unit"`
	Point       string    `json:"point"`
	InForce     string    `json:"inForce"`
	CurrentText string    `json:"currentText"`
	Versions    []Version `json:"versions"`
	// Diff is how the source moved since the prior answer was approved. The
	// gate does not read it — governance decides this, not wording — but a
	// reader cannot judge a verdict without seeing what it was passed.
	Diff tools.Diff `json:"diff"`
	// Offered is the reference the prompt would carry, or nil when the gate
	// withheld it. Withheld says why, in the terms a reader needs.
	Offered  *Version `json:"offered,omitempty"`
	Withheld string   `json:"withheld,omitempty"`
}

// PromptSection is one attributed block of a rendered prompt.
type PromptSection struct {
	Kind    string `json:"kind"`
	Origin  string `json:"origin"`
	Heading string `json:"heading,omitempty"`
	Text    string `json:"text"`
}

// PromptPair is the same block rendered two ways, so the difference the prior
// version makes is visible rather than described.
type PromptPair struct {
	Case     string          `json:"case"`
	Source   string          `json:"source"`
	Without  []PromptSection `json:"without"`
	With     []PromptSection `json:"with"`
	Digests  DigestPair      `json:"digests"`
	Withheld string          `json:"withheld,omitempty"`
}

// DigestPair is the cache key each rendering produces. They must differ, or a
// translation produced with a prior version would be served after the chain
// moved.
type DigestPair struct {
	Without string `json:"without"`
	With    string `json:"with"`
}

// reportRecipe is the context space the report is built over. It carries the
// shapes that break resolvers: two profiles sharing a channel name, a
// profile-level termstore only one of them declares, and a collection bound to
// nothing.
const reportRecipe = `version: v1
name: coordinate-report
defaults:
  source_language: en
  target_languages: [nb]
  voice:
    profile_file: .kapi/voice.yaml
profiles:
  acme:
    channels: [web, support]
    voice: .kapi/profiles/acme/voice.yaml
    termstore: .kapi/profiles/acme/terms.json
  other:
    channels: [web, email]
    voice: .kapi/profiles/other/voice.yaml
collections:
  - name: acme-web
    channel: acme/web
    content:
      - path: sites/acme/**/*.mdx
  - name: acme-support
    channel: acme/support
    content:
      - path: support/acme/**/*.md
  - name: other-web
    channel: other/web
    content:
      - path: sites/other/**/*.mdx
  - name: loose
    content:
      - path: README.md
`

// Build assembles the whole report by running the real code.
func Build(ctx context.Context) (*Report, error) {
	var p project.KapiProject
	if err := yaml.Unmarshal([]byte(reportRecipe), &p); err != nil {
		return nil, fmt.Errorf("parse recipe: %w", err)
	}
	if err := p.Validate(); err != nil {
		return nil, fmt.Errorf("validate recipe: %w", err)
	}

	points, err := buildPoints(&p)
	if err != nil {
		return nil, err
	}
	chains, prompts, err := buildChainsAndPrompts(ctx)
	if err != nil {
		return nil, err
	}

	ladder, err := buildEditLadder(ctx)
	if err != nil {
		return nil, err
	}
	segments, err := buildSegmentSplit(ctx)
	if err != nil {
		return nil, err
	}

	return &Report{
		Note:     reportNote,
		Recipe:   reportRecipe,
		Points:   points,
		Axes:     buildAxes(&p),
		Chains:   chains,
		Prompts:  prompts,
		Ladder:   ladder,
		Segments: segments,
	}, nil
}

// buildPoints resolves the governance at every point the recipe declares, plus
// the default point content falls to when it declares nothing.
func buildPoints(p *project.KapiProject) ([]Point, error) {
	out := make([]Point, 0, len(p.Collections)+1)
	seen := map[string]int{}

	for _, c := range p.Collections {
		rc, err := p.ResolveGovernance(c.Name)
		if err != nil {
			return nil, fmt.Errorf("resolve %s: %w", c.Name, err)
		}
		pt := Point{
			Profile:    rc.Profile,
			Channel:    rc.Channel,
			VoiceField: rc.VoiceField,
			TermStore:  rc.TermStore,
			Default:    rc.Profile == "" && rc.Channel == "",
		}
		if rc.Voice != nil {
			pt.VoiceFile = rc.Voice.ProfileFile
		}
		pt.Coordinates = map[string]string{}
		if rc.Profile != "" {
			pt.Coordinates[project.ProductAxis] = rc.Profile
		}
		if rc.Channel != "" {
			pt.Coordinates[project.ChannelAxis] = rc.Channel
		}
		pt.Slug = pointSlug(pt.Coordinates)
		pt.Label = pointLabel(pt.Coordinates)

		if at, ok := seen[pt.Slug]; ok {
			out[at].Collections = append(out[at].Collections, c.Name)
			continue
		}
		pt.Collections = []string{c.Name}
		seen[pt.Slug] = len(out)
		out = append(out, pt)
	}

	sort.Slice(out, func(a, b int) bool { return out[a].Slug < out[b].Slug })
	return out, nil
}

func pointSlug(coords map[string]string) string {
	if len(coords) == 0 {
		return "default"
	}
	axes := make([]string, 0, len(coords))
	for a := range coords {
		axes = append(axes, a)
	}
	sort.Strings(axes)
	parts := make([]string, 0, len(axes))
	for _, a := range axes {
		parts = append(parts, a+"~"+coords[a])
	}
	return strings.Join(parts, ".")
}

func pointLabel(coords map[string]string) string {
	if len(coords) == 0 {
		return "the default point"
	}
	axes := make([]string, 0, len(coords))
	for a := range coords {
		axes = append(axes, a)
	}
	sort.Strings(axes)
	parts := make([]string, 0, len(axes))
	for _, a := range axes {
		parts = append(parts, coords[a])
	}
	return strings.Join(parts, "-")
}

// buildAxes reads the coordinate space straight off the recipe, so the map
// shows what was declared rather than what happened to have content.
func buildAxes(p *project.KapiProject) Axes {
	axes := Axes{ChannelsByProduct: map[string][]string{}}
	channels := map[string]bool{}
	for name, prof := range p.Profiles {
		axes.Products = append(axes.Products, name)
		declared := make([]string, 0, len(prof.Channels))
		for _, c := range prof.Channels {
			declared = append(declared, c.ID)
		}
		sort.Strings(declared)
		axes.ChannelsByProduct[name] = declared
		for _, c := range declared {
			channels[c] = true
		}
	}
	sort.Strings(axes.Products)
	for c := range channels {
		axes.Channels = append(axes.Channels, c)
	}
	sort.Strings(axes.Channels)
	return axes
}
